### ISSUE TITLE
Remove retain_cm3_bug in interpolator

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#1004]
**Describe the bug**
The namelist variable retain_cm3_bug should be removed from FMS

**To Reproduce**
`retain_cm3_bug=.true.` is set by default.  Do we still want to keep this?

**Expected behavior**
This should either be the default behavior and the namelist variable should be removed

**System Environment**

**Additional context**
This is for the AM5 code prune clean up

**Comment by mlee03** [comment]
`retain_cm3_bugs` is set to .false. in the xmls  (did not check all the xmls though) and is used/found in 

- atmos_phys, particularly in atmos_shared/tracer_driver 

- mom6/coupled_AM2_LM3_SIS/CM2G63L/static_input.nml 

- mom6/coupled_AM2_LM3_SIS/CM2G63L/input.nml

I'll remove it and test it.

**Comment by thomas-robinson** [comment]
@mlee03 Have you made progress on this?

**Comment by mlee03** [comment]
@thomas-robinson, there's another variable in atmos_shared that is also called retain_cm3_bugs.   Though the one in atmos_shared is part of a different nml, I assume they're correlated.  I was planning on removing it from atmos_shared also and testing it before making the PR to FMS.

**Comment by thomas-robinson** [comment]
The project set for this is 2022.04, so this would need to be ready in about 2 weeks to make it in.  Do you think that's possible?  If so, I will leave it.  If not, we can change it to a later release.
