### ISSUE TITLE
Spack updates for 2022.03

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FMS#1014]
**Is your question related to a problem? Please describe.**
This is to track the spack updates and discussion needed for the emc group since they eventually plan on using a spack install.

See https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/163 for the original discussion

Spack PR:
https://github.com/spack/spack/pull/31901

**Comment by thomas-robinson** [comment]
@climbfuji and @junwang-noaa This is an FMS issue for tracking the spack update that @bensonr suggested we open in https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/163

**Comment by rem1776** [comment]
@climbfuji @junwang-noaa The [pull request](spack/spack#31901) to add the new fms version to spack has been merged, so I'll close this issue.
