### ISSUE TITLE
New DM functions should be public through type bound procedures

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#1021]
**Is your feature request related to a problem? Please describe.**
The functions and subroutines in the new diag manager are public and are type bound procedures.  

**Describe the solution you'd like**
We will make the actual function/subroutine private and force users to use the type bound procedures.

**Describe alternatives you've considered**

**Additional context**

**Comment by uramirez8707** [comment]
Fixed in #1505
