### ISSUE TITLE
Messages about "new" IO

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#1026]
**Is your feature request related to a problem? Please describe.**
While running the GFDL aquaplanet model, I noticed this message:
```
NOTE from PE     0: lw_gases_stdtf_mod: Reading NetCDF formatted input data file with new io: INPUT/cns_co2_348_HITRAN2012_10701200_495lyr.nc
```
The data is read with the **new** io, which is a relative term, and I assume it's referring to fms2_io.

**Describe the solution you'd like**
I would like the message to say that it was read with **fms2_io** instead of **new io**.

**Describe alternatives you've considered**

**Additional context**
Messages and code should not be referred to as new or old because this is not descriptive of what is being used.

**Comment by thomas-robinson** [comment]
@j-lentz Please take a look at this also

**Comment by uramirez8707** [comment]
This is not an FMS issue, this has to fixed in the atmosphere physics:
https://gitlab.gfdl.noaa.gov/fms/atmos_phys/-/blob/main/atmos_param/radiation/longwave/lw_gases_stdtf.F90#L5629
https://gitlab.gfdl.noaa.gov/fms/atmos_phys/-/blob/main/atmos_param/radiation/longwave/lw_gases_stdtf.F90#L5642
