### ISSUE TITLE
5D variable support and remapping in new diag manager

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#1027]
**Is your feature request related to a problem? Please describe.**
The diag manager will support a 5d remapped buffer array.  It will need to be remapped because the math functions of the diag manager use 4D arrays
**Describe the solution you'd like**
```fortran
class(*),target :: a5(ii,jj,kk,ll,mm) !< 5D buffer array
class(*), pointer :: p(:,:,:,:) !< 4D buffer remapped pointer
! Combine the inner 2 dimensions
 p(1:size(a5,1)*size(a5,2) , 1:size(a5,3) , 1:size(a5,4) , 1:size(a5,5) ) => a5
! mapping is dim1 = i+(ii*j-1)
i=3;j=4
write (6,*) p(i+(size(a5,1)*(j-1)),2,3,2) , a5(i,j,2,3,2)
write (6,*) p(i+(size(a5,1)*(j-1)),2,3,2) - a5(i,j,2,3,2)
```
This will write 0.0 as the answer.

**Describe alternatives you've considered**
We could alternatively combine the last two indices

**Additional context**

**Comment by uramirez8707** [comment]
Fixed in #1505
