### ISSUE TITLE
data compression in fms2_io

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-GFDL/FMS#1035]
**Is your question related to a problem? Please describe.**
Currently we are using fms2_io to write out MOM6 history/restart files in the UFS weather model. There is a request on compressing the data to reduce the data size. I am wondering if there is still an option to do the data compression with fms2_io.

**Describe what you have tried**
With fms_io, we have been setting the deflate_level in the mpp_io to compress the data. But it is not clear to me if there is a way to compress the data in fms2_io and how to set the namelist for it in fms2_io. 

Thanks for your help.

**Comment by junwang-noaa** [comment]
@jiandewang @yangfanglin @pjpegion @yuejianzhu-noaa FYI.

**Comment by bensonr** [comment]
@junwang-noaa - Are you looking for lossy or lossless compression?  While it is possible the history/diagnostics data could tolerate being lossy, the restarts must be lossless.  There would need to be clear benefit for the time spent compressing vs. the reduction in size in both cases.  I would suggest an offline test for the cost-benefit analysis and would serve as a prototype for implementation.

**Comment by junwang-noaa** [comment]
@bensonr Thanks for the suggestion. Would you confirm that we can still use the deflate_level in mpp_io library for the fms2_io for data compression? I thought the mpp_io is going to be removed and we can't use it for fms2_io.

**Comment by jiandewang** [comment]
I just checked MOM6-example infra/FMS2 code, deflate_level still exists 
https://github.com/NOAA-GFDL/FMS/blob/0721d5969734e6a5240a75120d0b25b1269541b7/mpp/mpp_io.F90#L1075-L1079

I will do some offline testing on this

**Comment by bensonr** [comment]
@junwang-noaa - _mpp_io/fms_io_ and _fms2_io_ are independent IO systems with no interconnections.  The future of I/O support has described multiple times.  A coming release will remove _mpp_io/fms_io_ from the default compile of FMS, though one still include it within the library via a compile-time macro.  A subsequent release will remove the logic completely.

 If you compile MOM6 with the _infra/FMS1_ bindings, you should still be able to use the existing compression from within mpp_io/fms_io layer.  If one chooses _infra/FMS2_ for MOM6, all I/O will be performed via the _fms2_io_ layer.

**Comment by junwang-noaa** [comment]
@bensonr @thomas-robinson We still hope to get the compression feature in fms2 io. Would you mind provide us a test version of fms? We'd like to run some tests to see the impact on the data size and computation performance. For ufs weather-model, with current resolution MOM6 does not dominate the computation time, so we have a little space to get smaller data size. Thank you very much!

**Comment by thomas-robinson** [comment]
@mcallic2 will work on this and get back within a week.  @junwang-noaa do you have a repo you would like her to submit a PR to when it's ready?  She will be working off of the tag 2022.04-alpha4 unless there is some other recent starting point you would like her to work from.

**Comment by junwang-noaa** [comment]
@rem1776 Thank you very much for the code updates! It looks to me we also need to update the restart writing code to use the option. @bensonr is there a plan to update the dycore restart code to add the compression and chunksize option? Thank you!

**Comment by bensonr** [comment]
Please open an issue or start a discussion within the
GFDL_atmos_cubed_sphere repo to have the dialogue in the proper place.
