### ISSUE TITLE
travis CI uses old version of gcc/gfortran

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#105]
The version of gcc used by travisCI is old.  It needs to be updated to handle newer fortran features.

**Comment by thomas-robinson** [comment]
@underwoo is there a way to run an update to [.travis.yml](../blob/master/.travis.yml) without submitting a pull request?

**Comment by underwoo** [comment]
You can create your own travis-ci.com account and have it run commits on your fork.
