### ISSUE TITLE
mpp_alltoall test crash with intel 2022.3.0/1

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FMS#1071]
**Describe the bug**
the mpp_alltoall test causes some internal compiler errors with the intel 2022.3.0 and 3.1 when run in the CI.

i made a intel thread [here](https://community.intel.com/t5/Intel-Fortran-Compiler/ifort-internal-compiler-error-starting-with-2022-3-0-and-2022-3/m-p/1430982#M163603)

**To Reproduce**
make check with oneapi 2022.3.1 or 2022.3.0 on the inte/oneapi-hpckit container

**Expected behavior**
test should compile successfully

**System Environment**
CI container (intel/oneapi-hpckit:latest, 2022.03.01 and 2022.03) 

**Additional context**
came up with #1069  but then intel fixed the initial update issue.

**Comment by rem1776** [comment]
Intel response: https://community.intel.com/t5/Intel-Fortran-Compiler/ifort-internal-compiler-error-starting-with-2022-3-0-and-2022-3/m-p/1450857/highlight/true#M164723

Looks like it is a bug and only in the (new?) ifort, not ifx. Coming from an import so moving it around might be a quick fix for now until intel fixes it.

**Comment by bensonr** [comment]
The comment in Ron's test case for Intel suggests that it happens when importing specific symbols from mpp_mod, basically the 'only' is specified.  Can you try it with 'use mpp_mod' and include everything?

**Comment by rem1776** [comment]
@bensonr Tried that but unfortunately didn't seem to fix it, even changing the module imported to the global libfms one still results in the ICE.
