### ISSUE TITLE
mpp test failures with gcc 11

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FMS#1101]
**Describe the bug**
Two mpp tests fail on our development machines, test_mpp_checksum.3 (mixed prec checksum) and test_mpp_domains.14(check parallel). One fails on amd and the other on skylake

**To Reproduce**
make check with gcc 11.2.0 + mpich on the development machines

**Expected behavior**
tests should run successfully

**System Environment**
Describe the system environment, include:
- OS: centos
- Compiler: gcc
- MPICH
- netCDF Version: 4.8.0

**Comment by rem1776** [comment]
mpp_checksum test failures are fixed with #1103. Domains still unresolved, only seems to happen on cent os 7 (skylake box).

**Comment by thomas-robinson** [comment]
The skylake box no longer exists.  Can this be reproduced anywhere else?

**Comment by rem1776** [comment]
> The skylake box no longer exists.  Can this be reproduced anywhere else?

Yeah the remaining test for this issue test_mpp_domains #14 is a common failure with other compilers as well. @laurenchilutti is working on it I believe.

**Comment by laurenchilutti** [comment]
yes, I am working on the test_mpp_domains check_parallel test failure - so this issue will be resolved with that fix.

**Comment by rem1776** [comment]
should be fixed with #1292, all mpp tests pass with gcc 11.4
