### ISSUE TITLE
Race condition in tridiagonal

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#1108]
**Describe the bug**
tridiagonal.F90 has a few module level variables
https://github.com/NOAA-GFDL/FMS/blob/main/tridiagonal/tridiagonal.F90#L63-64
These variables are deallocated, then allocated in the solver routine
https://github.com/NOAA-GFDL/FMS/blob/main/tridiagonal/tridiagonal.F90#L94-101
Then they are deallocated in the close routine
https://github.com/NOAA-GFDL/FMS/blob/main/tridiagonal/tridiagonal.F90#L137-140
causing a race condition if they are being deallocated before the threads are done in the if block.  This race condition needs to be resolved.

**To Reproduce**
This was encountered on HD ticket GFDL#5021882 .  This is not always repeatable, so it may be difficult to reproduce.  

**Expected behavior**
The race condition should be removed.  If these saved variables are necessary, then they should be stored elsewhere and passed in instead of allocated/deallocated in a non-thread safe manner like this.

**System Environment**
Describe the system environment, include:
- gaeac4 AM5 2022.01 c96L33_am5a0 with FRE using -r rts

**Additional context**

**Comment by thomas-robinson** [comment]
This isn't threadsafe because we are setting and unsetting and using module variables.  If the threads aren't in sync, then something can get deallocated while another thread is using it.

**Comment by rem1776** [comment]
> This isn't threadsafe because we are setting and unsetting and using module variables. If the threads aren't in sync, then something can get deallocated while another thread is using it.

@thomas-robinson @ganganoaa  I get the thread safety issue, but these module variables are used in the calculations after the first call so they need to be either statically saved somewhere or passed in each time. #1109 changes them to local which would fix the threading but make it lose the data that used to be stored and not work as intended when the optional arguments are not present.

I think moving `init_tridiagonal = .true.` to after the allocation and assignments are done and also making the `close_tridiagonal` check for allocations before deallocating would fix some of the race conditions.

**Comment by ganganoaa** [comment]
Tom,

I don't see any OpenMP directives in the module. So, I am confused how 
OpenMP parallization acts on those computations. Does each thread call 
its own copy of 'tri_invert'?


Ganga

**Comment by bensonr** [comment]
@ganganoaa - we put OpenMP at the highest levels possible within FMS models.  For this case, the OMP statements that would be invoked here are embedded in various routines within atmos_model.F90 starting at [Line 455](https://github.com/NOAA-GFDL/atmos_drivers/blob/main/coupled/atmos_model.F90#L455) and [Line 599](https://github.com/NOAA-GFDL/atmos_drivers/blob/main/coupled/atmos_model.F90#L599)

**Comment by thomas-robinson** [comment]
> > I think moving `init_tridiagonal = .true.` to after the allocation and assignments are done and also making the `close_tridiagonal` check for allocations before deallocating would fix some of the race conditions.
> 
> Something needs to be done here to make it thread safe. Adding the allocation check is a step in the right direction, but it doesn't fix the problem of one thread being in one routine and another thread being in the other routine, which is what appears to be happening in some of the errors.

@rem1776 it appears I edited your comment instead of replying to it.  I hope I didn't ruin the sentiment of it.  It said that you were working through this module and that the values need to be saved so that the inputs don't need to be put back into the solver each time you want to run in.  Then you call close when it's done.  

I think that's important to remember, but shouldn't it be on the calling routine to track these things and not on the solver routine?  Tridiagonal should do calculations, not track and store variables for the user.  We could pass them as output and they could be sent back in as input if you don't want them to be calculated every time.

**Comment by ganganoaa** [comment]
I was also thinking along the line what @rem1776 was suggesting. How about making 'init_tridiagonal' public and user will assign '.false.' if it is first time calling 'tri_invert'. Then the subroutine will assign '.true.' . Whenever 'init_tridiagonal' is '.false.' the subroutine will deallocate and allocate the module variables. And do we really need to deallocate those module variables?
