### ISSUE TITLE
AM4 crashes with invalid type in sat_vapor_pres_k_mod

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1111]
**Describe the bug**
AM4 is crashing with intel/intel-classic-2022.0.2, debug-openmp on c4 with the following error message:

/lustre/f2/scratch/Uriel.Ramirez/awg/2023.01-alpha1/c96L33_am4p0/ncrc4.intel22-debug-openmp/stdout/run/c96L33_am4p0_2x0m1d_192x2a.o269205698

```
FATAL from PE    14: sat_vapor_pres_k_mod::compute_qs_k_0d: temp is not one of the supported types of real(kind=4) or real(kind=8) OR temp and dqsdT types do not match

fms_cm4p12_2023.0  000000000BD8B6FC  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
fms_cm4p12_2023.0  000000000BD92846  mpp_mod_mp_mpp_er         149  mpp_util.inc
fms_cm4p12_2023.0  000000000DB114F8  fms_mod_mp_error_         478  fms.F90
fms_cm4p12_2023.0  000000000DD6B9C9  sat_vapor_pres_k_        1238  sat_vapor_pres_k.F90
fms_cm4p12_2023.0  000000000DA67DCB  sat_vapor_pres_mo        2067  sat_vapor_pres.F90
fms_cm4p12_2023.0  00000000004B9F83  atm_land_ice_flux        1706  atm_land_ice_flux_exchange.F90

```
The run is successful with with debug and it worked with intel18.
/lustre/f2/scratch/Uriel.Ramirez/awg/2023.01-alpha1/c96L33_am4p0/ncrc4.intel22-debug/stdout/run/c96L33_am4p0_2x0m1d_192x1a.o269205721

The run is successful if running with 1 thread:
/lustre/f2/scratch/Uriel.Ramirez/awg/2023.01-alpha1/c96L33_am4p0/ncrc4.intel22-debug-openmp/stdout/run/c96L33_am4p0_1x0m2d_216x1a.o269205717

This was likely happening since 2021.03.

**To Reproduce**
Run AM4 with intel/intel-classic-2022.0.2

**Expected behavior**
The run should not fail

**System Environment**
Describe the system environment, include:
- C4, bronx-20, intel/intel-classic-2022.0.2, debug-openmp

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by nikizadehgfdl** [comment]
@uramirez8707 your example for ncrc4.intel18 is using 1 thread. Does it run with 2 threads on ncrc4.intel18?

**Comment by nikizadehgfdl** [comment]
Got it, I get the same behavior on ncrc5.intel22
```
crashed
/lustre/f2/scratch/Niki.Zadeh/fre/FMS2023.01-alpha2_20220703_011223/c96L33_am4p0/ncrc5.intel22-debug-openmp/stdout/run/c96L33_am4p0_1x0m2d_216x2a.o134339118 
ran
/lustre/f2/scratch/Niki.Zadeh/fre/FMS2023.01-alpha2_20220703_011223/c96L33_am4p0/ncrc5.intel22-debug-openmp/stdout/run/c96L33_am4p0_2x0m1d_216x1a.o134339119
```

**Comment by bensonr** [comment]
Bitten by the Fortran automatic save yet again....
I just took a look at this and there is an error in sat_vapor_pres_k.F90.  The declaration for _valid_types_ sets a value in each of the class(*) routines.  This causes _valid_types_ to have a save attribute automagically added and hence it becomes a module scope variable, which is a bad thing in an OpenMP section.  If all of these declarations are changed to:

  logical :: valid_types
  valid_types = .false.

Things should work as expected.

**Comment by mlee03** [comment]
shouldn't eps and zvir also be declared as class(*)?
https://github.com/NOAA-GFDL/FMS/blob/main/sat_vapor_pres/sat_vapor_pres_k.F90#L1463

**Comment by mlee03** [comment]
Never mind, got it :grin:
