### ISSUE TITLE
unchecked sat_vapor_pres optional logical variables

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#1121]
**Describe the bug**
In subroutines such as `compute_qs_k_0d` in `sat_vapor_pres`, there are optional logical arguments.  The presence of these arguments are checked but their values are not.   If a user defines these optional arguments as `.false.`, the code will not execute as the user expects (https://github.com/NOAA-GFDL/FMS/blob/main/sat_vapor_pres/sat_vapor_pres_k.F90#L626)

**To Reproduce**

**Expected behavior**
The value of the logical variables should be checked. 

**System Environment**
Describe the system environment, include:

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by rem1776** [comment]
fixed with #1120
