### ISSUE TITLE
--disable-mpi configuration flag is documented, but does not exist

### ISSUE THREAD

**Issue by J-Lentz** [NOAA-GFDL/FMS#1126]
**Describe the bug**
`INSTALL.md` states that FMS can be built without MPI support, via a `--disable-mpi` configuration flag. However, this flag doesn't seem to exist. `./configure --disable-mpi` results in an "unrecognized option" warning; the configuration script ultimately checks for libmpi and fails if it's not found.

**To Reproduce**
`./configure --disable-mpi`

**Expected behavior**
FMS should build successfully without MPI support.

**Comment by bensonr** [comment]
@J-Lentz - I think the option you need to be using is --with-mpi, which defaults to 'yes' (see [here](https://github.com/NOAA-GFDL/FMS/blob/main/configure.ac#L63-L68))

**Comment by J-Lentz** [comment]
@bensonr - That seems to work, thank you.
