### ISSUE TITLE
travis-CI diag_manager test can't finding ensemble_manager.mod in diag_integral bulid

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#118]
In PR #117 with new 32-bit compiler flags added to the .travis.yml file, the travis-CI test (https://travis-ci.org/NOAA-GFDL/FMS/jobs/571517159#L1153) fails after building the diag_integral code at line 1153 with the following error: 

```Fatal Error: Can't open module file ‘ensemble_manager_mod.mod’ for reading at (1): No such file or directory```

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor this should be an easy fix.  I'm not sure why this didn't merge correctly.

You need to make drag_integral before coupler.  In your [Makefile.am](https://github.com/wrongkindofdoctor/FMS/blob/user/jml/fix_travis_yml/Makefile.am) move the drag_integral after coupler.  This is correctly done on in master's [Makefile.am](../blob/master/Makefile.am)
