### ISSUE TITLE
Wrong peset used in mpp_broadcast_

### ISSUE THREAD

**Issue by dkokron** [NOAA-GFDL/FMS#1243]
I suspect that the current_peset_num used in line 185 of mpp/include/mpp_transmit_mpi.fh should really be 'n'

I don't have a clean reproducer that demonstrates the issue.
I am testing the use of mpp_broadcast for communicating between parent and nested grids in the UFS/HAFS model.
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/272

I'm using a pelist in the mpp_broadcast() call.  The code in the above PR fails with "FATAL from PE    36: MPP_BROADCAST: broadcasting from invalid PE." unless I place mpp_set_current_pelist() calls judiciously around the mpp_broadcast() call.

While investigating the "broadcasting from invalid PE" message, I realized the error message is coming from a check to ensure "from_pe" is part of the "current_peset_num" NOT the peset that is retrieved via the call to get_peset().

**System Environment**
Describe the system environment, include:
- OS: Ubuntu and SLES15
- Compiler(s): Intel 2023.1 (aka 2021.9.0) and 19.1.3.304
- MPI type, and version OpenMPI-4.1.5 and Cray-MPICH
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

I have run the FMS (2023.01) internal test suite via "make check" with and without the 'fix' below and both give the same results.

      !if( .NOT.ANY(from_pe.EQ.peset(current_peset_num)%list) ) &
      if( .NOT.ANY(from_pe.EQ.peset(n)%list) )

**Comment by thomas-robinson** [comment]
@dkokron can you put in a PR and link this issue to it.  We can then evaluate what you want.

**Comment by dkokron** [comment]
https://github.com/NOAA-GFDL/FMS/pull/1246
