### ISSUE TITLE
FMS coupler request: blending capability for data_override

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-GFDL/FMS#125]
To support a flux-adjusted version of SPEAR, as well as many other future experiments throughout the lab, we'd like to request addition of a "data blending" capability to the FMS coupler.  This could be done as a simple extension of the existing data_override code, and would enable much greater control over the fluxes and fields passed between model components.  The proposal is as follows.

For each model field to be blended -- call it "var", e.g. sea surface temperature (SST) or zonal surface wind stress (tau_x) -- the user would provide up to three NetCDF files & variables:

a) var_data.nc, containing  the {lon,lat,time}-dimensioned variable "var": input data, e.g. satellite-observed surface zonal wind stresses (tau_x) in MKS units.  If var_data.nc were not provided, then the data would default to 0 everywhere.

b) var_data_coeff.nc, containing the {lon,lat}-dimensioned variable "coeff": a static field of coefficients to multiply the data read in from var_data.nc.  If this NetCDF file were not provided, then the data_coeff would default to 0 everywhere.

c)  var_coupler_coeff.nc, containing the {lon,lat}-dimensioned variable "coeff": a static field of coefficients to multiply the model-generated field at every coupling time step -- e.g. the tau_x produced by the atmospheric model.  If this NetCDF file were not provided, then the coupler_coeff would default to (1 - data_coeff) everywhere, easily allowing multi-region and tapering capability.

All three input variables (data, data_coeff, coupler_coeff) would consist of floating point values in the range (-inf,inf).

It would be the user's responsibility to provide the appropriate input data and coefficients, with any tapering etc. already applied.  So all the regional/blending magic would be pre-computed by the user.  The FMS coupler would just read the files, and then compute a simple weighted sum at each timestep.

Specifically: At initialization, the coupler would read and interpolate the data_coeff and coupler_coeff to the model's {lon,lat} grid.  Then during the model run, at each time step the coupler would read and interpolate the input data to the model {lon,lat,time} grid, using the existing time_interp_external() code which knows how to deal with calendars and modulo (climatological) time axes.  The coupler would then modify the var passed between model components (e.g. tau_x passed from atmos to ocean, or SST passed from ocean to atmos) as:

   var_blend = (var_coupler * var_coupler_coeff) + (var_data * var_data_coeff)

The coupler would also register the following diagnostics with the diag_manager, so that they could be requested via the diag_table:

   var_coupler_part = var_coupler * var_coupler_coeff
   var_data_part = var_data * var_data_coeff

The user could specify blends for more than one variable at a time -- e.g. SST, tau_x, tau_y, heat flux, and freshwater flux -- each with their own coupler_coeff and data_coeff.  This could be implemented using a data_blend_table (akin to a field_table).

This simple blending feature would enable and unify some powerful new capabilities that are not available with the existing data_override.  These include:

1) A spatially-varying override, with regional tapering from data toward model.  To do this the user would simply provide the input data, and their pre-computed spatial map of data coefficients:
   data_coeff = [0.0 .. 1.0]
It would be the user's responsibility to compute and provide the desired {lon,lat} map of data coefficients.  In this case the model_coeff.nc file would not be needed, and would default to 1.0-data_coeff.  At points where data_coeff=0.0, the model field would pass through unaltered.  At points where data_coeff=1.0, the model field would be completely overridden by the input data.  And at points where data_coeff=0.5, the result would be a mixture of half model and half data.

The existing data_override code only allows a 100% override in a rectangular lon-lat region specified via a namelist.  This old functionality could be replicated by the user setting data_coeff=1.0 in a rectangular {lon,lat} override region, setting data_coeff=0.0 everywhere else.  If need be, the existing namelist region-specification options could be retained for backward compatibility, or to provide a simpler interface in these special cases.

2) A spatially-varying "add" (this is a new feature).  For example, this could be used to impose a wind stress perturbation *in addition to* the model-generated stress, either to apply a climatological wind stress correction (flux adjustment), or to apply a transient regional wind burst to excite an El Nino event.  The user would provide the appropriate weightings:
   data_coeff = [0.0 .. 1.0]
   coupler_coeff = 1.0 everywhere

3) Override and add simultaneously (another new feature).  For example, this could be used to totally override the wind stress over the Indian & Atlantic oceans, and also add a climatological wind stress correction in the tropical Pacific that tapers toward zero in mid-latitudes.  These regions could be the same, different, or even partially overlapping; the user would just need to provide the appropriate coefficients for model and data.  The user would provide:
   data_coeff = [0.0 .. 1.0]
   coupler_coeff = [1.0 .. 1.0-data_coeff]

If at all possible, we would like to begin using these capabilities in October 2019.  Please let us know if any further information is needed to move forward with implementation.

Thank you for your help,

Andrew, Fanrong, Will, and Matt

PS: We had considered combining var_data*var_data_coeff into a single XYT input variable, but decided against it.  The var_data.nc will typically be a big XYT obs data file, while the var_data_coeff will be a small XY file.  If the coefficients ever needed to be modified, it'd be much easier if it was its own little entity.

**Comment by thomas-robinson** [comment]
@AndrewWittenberg What is the time line you want to see this deployed?

**Comment by AndrewWittenberg** [comment]
@thomas-robinson If at all possible, we would like to begin using these capabilities in October 2019.

**Comment by GFDL-Eric** [comment]
Closing, see #267 (a closed PR) for an example implementation
