### ISSUE TITLE
Select type blocks inside diag manager causing errrors with Nvidia 

### ISSUE THREAD

**Issue by marshallward** [NOAA-GFDL/FMS#1255]
**Describe the bug**
The `select type (weight)` block in the diag manager is causing errors in MOM6.  It fails to identify `weight` as either real32 or real64.  It is declared as `real` in MOM6.

**To Reproduce**
Compile with Nvidia 22.3 using FMS 2023.01.01, run the `global_ALE/z` experiment.  (For reproducibility, use 64 ranks, but probably not essential.)

https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ocean_only/global_ALE/z

**Expected behavior**
The model should not crash.

**System Environment**
On C5:
```
module load PrgEnv-nvhpc/8.3.3
module switch nvhpc/22.3

module unload darshan-runtime

module load cray-hdf5
module load cray-netcdf
```

Template: 
https://github.com/mom-ocean/mkmf/blob/c5/templates/ncrc5-nvhpc.mk

**Additional context**
These `select type` blocks have caused a man-year's worth of problems for us.  On top of that, they are pushing a compile-time decision to a runtime decision for no practical reason.

There is no context where we would change them at runtime.  Even if everything worked properly, they are causing the program to do more work, not less.  I fail to see any reason to use them.

I would strongly discourage their use in the future.

**Comment by thomas-robinson** [comment]
I reproduced this on gaea by doing
```
module load PrgEnv-nvhpc/8.3.3
module switch nvhpc/22.3
module unload darshan-runtime
module load cray-hdf5
module load cray-netcdf

cd $DEV/$USER
git clone --recursive --jobs=16 https://github.com/NOAA-GFDL/MOM6-examples.git -b dev/gfdl
cd MOM6-examples
cd src/FMS2
git checkout 2023.01.01
cd ..
rm FMS
ln -sf FMS2 FMS
cd ..

mkdir -p build/fms/
(cd build/fms; rm -f path_names; \
../../src/mkmf/bin/list_paths -l ../../src/FMS; \
../../src/mkmf/bin/mkmf -t ../../src/mkmf/templates/ncrc5-nvhpc.mk -p libfms.a -c "-Duse_libMPI -Duse_netCDF" path_names)
(cd build/fms/; make NETCDF=3 REPRO=1 libfms.a -j)

mkdir -p build/ocean_only/
(cd build/ocean_only/; rm -f path_names; \
../../src/mkmf/bin/list_paths -l ./ ../../src/MOM6/{config_src/infra/FMS1,config_src/memory/dynamic_symmetric,config_src/drivers/solo_driver,config_src/external,src/{*,*/*}}/ ; \
../../src/mkmf/bin/mkmf -t ../../src/mkmf/templates/ncrc5-nvhpc.mk -o '-I../fms' -p MOM6 -l '-L../fms -lfms' path_names)
(cd build/ocean_only/; make REPRO=1 MOM6 -j)

cd ocean_only/global_ALE/z
ln -sf /lustre/f2/pdata/gfdl/gfdl_O/datasets INPUT/.datasets
mkdir RESTART

salloc -N 1 -t 120 -n 128 -M c5

srun -n 64 ../../../build/ocean_only/MOM6

```

**Comment by thomas-robinson** [comment]
I tried with `module switch nvhpc/22.7` (and 22.5) instead of `22.3` and the run worked.  This isn't a code issue; it's a compiler issue which has been resolved with a newer version.  Can you confirm that this is working?  Is there any reason not to use the newer version of the compiler?

**Comment by marshallward** [comment]
I think it will be ok to use the newer compiler, but will need to confirm.

(There is also another unreported error, but if 22.7 fixes this one then we can close the issue.)

**Comment by marshallward** [comment]
Nvidia 22.7 seems to have fixed this one, thanks very much @thomas-robinson.  I'll close this one.

**Comment by marshallward** [comment]
22.7 seems to have also fixed the issue that I alluded to above.  So we're all good (... for now!)
