### ISSUE TITLE
land_null errors out with nvidia compiler  nvhpc/22.7 on c5    character buffer is too small; increase length: netcdf_read_data_0d: file:INPUT/grid_spec.nc- variable:lnd_mosaic

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#1326]
**Describe the bug**
Regression test fails with the latest nvidia compiler on c5 : 

 FATAL from PE     7: character buffer is too small; increase length: netcdf_read_data_0d: file:INPUT/grid_spec.nc- variable:lnd_mosaic

This is under FMS2023.02 release. In previous releases I could bypass the error by reverting land_null to pre-mosaic2 version. But older tags of land_null do not compile with  FMS2023.02 

**To Reproduce**
frerun -s -r basic -u --no-transfer -x /ncrc/home2/Niki.Zadeh/frerts/fre/FMS2023.02_mom6_20230828/_0/OM4_extra.xml.20230810143846 -p ncrc5.pgi227 -t prod MOM6_GOLD_SIS2_generics

**Expected behavior**
Not to crash.

**System Environment**
ncrc5   nvhpc22.7 

**Additional context**
None of the regression tests that use land_null run any more with nvidia compiler.

**Comment by bensonr** [comment]
@nikizadehgfdl - do you see this with the later versions we have installed on the dev box?  If not, we can use this to push ORNL to upgrade the installations on gaea.

**Comment by nikizadehgfdl** [comment]
This particular error does not happen with nvhpc/23.7 on the amdbox. 
However the ocean-ice model crashes without any hints somewhere else in land_null. Adding print statements  indicate the crash happens in the calls to [get_grid_cell_area](https://github.com/NOAA-GFDL/land_null/blob/master/land_model.F90#L278) . The ocean-ice models can be run without these calls and by just setting frac=1.0 instead. 
But that is all perhaps unrelated to this issue. Closing.

**Comment by nikizadehgfdl** [comment]
Just for future reference, here's the land_null PR that allows ocean-ice models to run with nvhpc/23.7 under FMS2023.03
https://github.com/NOAA-GFDL/land_null/pull/5
