### ISSUE TITLE
how to change diagnostics starting time in diag_table?

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1379]
### Discussed in https://github.com/NOAA-GFDL/FMS/discussions/1378

<div type='discussions-op-text'>

<sup>Originally posted by **junwang-noaa** September 29, 2023</sup>
Hello,  We are setting up an IAU test. It is a restart run from the previous cycle.  Now we want all the diagnostic fields especially those averaged or accumulated fields start to accumulate at a later forecast hour, in other words, not the model starting time. Currently in my diag_table I have:
```
20161003.00Z.C96.64bit.non-mono
2016 10 03 00 0 0
```
2016103000 is the starting time, the model restarts at fh=3, and I want all the averaged fields starts to accumulate at fh=6. Should I change the second line to 2016100306 in my case? e.g.
```
20161003.00Z.C96.64bit.non-mono
2016 10 03 06 0 0
```
I hope with this change the following two files:
```
"ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", 6, "hours", "1901 1 1 0 0 0"
"SST%4yr%2mo%2dy",      1,  "days",  1, "days",  "time", 1, "days",  "1901 1 1 0 0 0"
```
will give me 6 hourly diagnostic fields (e.g. 2016100306-2016100312) in ocn files and daily diagnostic fields (2016100306-2016100406) for SST files even though the model starting time is 2016100300 and restarts at fh=03 (2016100303). Thanks.</div>

**Comment by rem1776** [comment]
should be fixed by #1381 ( #1396 adds into main)
