### ISSUE TITLE
apply netcdf unpacking for data_override

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/FMS#1385]
netcdf surface files downloaded from ECMWF MARS server are packed using a scale_factor and add_offset. When read using the data_override functionality, it does not indicate an error but uses the packed values without first applying the scale_factor and add_offset.

It would be useful to have FMS data_override check for scale_factor and add_offset and apply them if present. At a minimum, an error should be thrown if the factors are present in the netcdf file but not applied.

The scale factor looks like this in a sample ECMWF file:
```
ubuntu@ip-172-31-30-18:~/OCN_data$ ncdump -h IFS_SFC_FCST_20231001_00Z.nc

netcdf IFS_SFC_FCST_20231001_00Z {

dimensions:
	longitude = 2880 ;
	latitude = 1441 ;
	time = UNLIMITED ; // (25 currently)
variables:
...
	short skt(time, latitude, longitude) ;
		skt:scale_factor = 0.00214011053621124 ;
		skt:add_offset = 271.246534314849 ;
		skt:_FillValue = -32767s ;
		skt:missing_value = -32767s ;
		skt:units = "K" ;
		skt:long_name = "Skin temperature" ;

	short sst(time, latitude, longitude) ;
		sst:scale_factor = 0.000611232633987838 ;
		sst:add_offset = 287.971496141495 ;
		sst:_FillValue = -32767s ;
		sst:missing_value = -32767s ;
		sst:units = "K" ;
		sst:long_name = "Sea surface temperature" ;
```

We have instead applied unpacking using NCO as a preprocessing step:
```
ncpdq --unpack IFS_SFC_FCST_${YYYY}${MM}${DD}_${HH}Z.nc IFS_SFC_FCST_${YYYY}${MM}${DD}_${HH}Z_unpacked.nc
```
This works, however the data files are about 4x larger after unpacking so require a considerably larger data footprint for a given forecast. 

Example:
Experiment run using packed data with no warnings provided by FMS. Instead there are warning of high temperature values and instabilities, e.g. in this case in FV3-SHiELD:
```
YSUPBL: Extreme temperature found T =    23    8  375.8264435218816
  383.1027212500884.9808536440805191.5877419879233967E-01
  .1000000000000000E+313.82553838187292120895.7835506315227 T T
  1000.0000000000001000.0000000000001000.000000000000
  389.0654395043251375.8264435218816362.9398752288105
  2488.5043748965252715.343750000000
  -51.83257891255882-1.120213618880217.1000000000000000E-01-.1193558674601653E-01
```
Baseline case, after 1 hour integration:
<img width="397" alt="Screen Shot 2023-10-06 at 12 23 20 PM" src="https://github.com/NOAA-GFDL/FMS/assets/11303168/c6fee9e0-301f-45e2-8380-1f2c6eca2a36">

Case using ingested ECWMF skin temperature before being unpacked (note change in colorbar range):
<img width="360" alt="Screen Shot 2023-10-06 at 12 24 25 PM" src="https://github.com/NOAA-GFDL/FMS/assets/11303168/2aabcf2a-75b2-4c35-bbdc-0926b26504ed">

Tagging @lharris4 for visibility.

**Comment by uramirez8707** [comment]
The unpacking of netcdf data was implemented in the 2023.02 release of FMS
https://github.com/NOAA-GFDL/FMS/pull/1231

Please let us know if you have any issues with it.

**Comment by lharris4** [comment]
Hi, @uramirez8707.  Sorry I hadn't realized that the latest FMS has these features.

@laurenchilutti Steve is running SHiELD version 202210 which I believe is using FV3 release 202210. Are any changes needed to FV3 or SHiELD to update to the latest FMS?

Thanks,
Lucas

**Comment by laurenchilutti** [comment]
There were definitely changes needed for FMS since Oct 2022.  Some I can remember:
Updates from fmsio to fms2io: FMS now has deprecated all fmsio routine calls, so we would need to make sure Steve's code does not reference any of the deprecated subroutines. https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/257
Updates to fms routines called from the libFMS module: coupler_main.F90 (in FMScoupler/SHiELD) accesses fms routines via the FMS module.  There were some subroutine name changes in this module https://github.com/NOAA-GFDL/FMScoupler/pull/86

**Comment by StevePny** [comment]
Thanks all - Since we can temporarily resolve this with nco preprocessing we will likely stick with that for now, so I'll close this issue. 

@lharris4 and @laurenchilutti, do you have a timeline for when you are planning the next tagged public release of SHiELD (SHiELD_physics, GFDL_atmos_cubed_sphere, SHiELD_build, FMScoupler)? We'd prefer to use a verified common version/tag, and minimize the number of custom changes from that base.

**Comment by lharris4** [comment]
Hi, Steve. I believe we had a tagged public release of all of our components back in June that we are now recommending for external users. @laurenchilutti @kaiyuan-cheng can confirm.

**Comment by laurenchilutti** [comment]
We had a release in May 2023 - Please try to use FMS and FMSCoupler tag 2023.02,  GFDL_atmos_cubed_sphere tag FV3-202305-public, SHiELD_physics tag FV3-202305-public, and the main branch of SHiELD_build,.

**Comment by lharris4** [comment]
Hi, Lauren. Thanks. I see that CHECKOUT_code pulls the 'main' branch for FV3 and the SHiELD Physics:

https://github.com/NOAA-GFDL/SHiELD_build/blob/main/CHECKOUT_code

This would be good for users wanting a 'cutting edge' release, but the latest stable release would be FV3-202305-public. Should the default be the stable release?

**Comment by laurenchilutti** [comment]
That is a good catch.  I think it would be a good idea to reference the latest release tags in the CHECKOUT_code script.  And users can always update this manually to point to main if they prefer.   I will put in a PR to SHiELD_build today to incorporate this as an update.
