### ISSUE TITLE
Bug with diag manager with diurnal24 diagnostic

### ISSUE THREAD

**Issue by jessluo** [NOAA-GFDL/FMS#1413]
I am getting a fatal error from `diag_manager_mod` with the diurnal24 diagnostic that happens on the second month of a 2-month regression run, but not in a 1-month regression run.

```FATAL from PE     0: diag_manager_mod::send_data_3d: module/output_field generic_cobalt_z/jnvmlgzc, write EMPTY buffer```

This seems to happen when the missing_value is passed into the register diag field call during the second write call.

If on gaea, my error can be reproduced using the following xml: 
```/autofs/ncrc-svm1_home2/Jessica.Luo/run_scripts/OM4_05_dvmCOBALT_era5_110823.xml```
If the 'basic' regression test is changed to 1 month, then it runs fine. If it is set to 2 months, then it crashes.

**Comment by uramirez8707** [comment]
The problem was that send_data was not called hourly for the `jnvmlgzc` diagnostic.
The error messages in the new diag manager should be less ambiguous ...
