### ISSUE TITLE
Is there a way to build FMS so that is works for AM4?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#142]
I am trying to build AM4, and it has some problems with FMS. (See the comments in https://github.com/NOAA-GFDL/AM4/pull/16).

I have heard that is because I am using the master branch of FMS and there is some other branch that might work for AM4. Is this true? If so, what branch? (A branch called "warsaw" was mentioned, but is not in the repo.)

I hope this sort of confusion can be killed by #102. Instead of a model building with some branch of FMS, which is not stable (because the branch can change too), AM4 can be targeted to build against a specific released version of FMS, which will work forever. This is how netcdf, HDF5, and every other software package works.

What I would like to do, if it is possible, is to learn what version/branch/voodoo magic for FMS works for AM4 now, and get you guys to tag that as version 1.0 of FMS. In any case, none of this will work until you start releasing versions of FMS. It's only a button press to do so.

**Comment by underwoo** [comment]
I added a comment in NOAA-GFDL/AM4#16.  I think your issue may be with the `-fdefault-real-8` flag that was likely added to the FMS build.  That flag will need to be added to all components as well.  We realize that setting the default real size to be double is not ideal, but remember we are dealing with some code that is multiple decades old.  We talk a lot about refactoring the code to do away with this.  However, that will require support from the scientists (we need their help to know which variables can be KIND=4 and which need to be KIND=8), and the required personnel to do the work.

**Comment by edwardhartnett** [comment]
OK, good tip. I will try that.

If that turns out to be the problem, this is something we can check in configure, and deliver a useful message to the builder that explains the problem.

**Comment by edwardhartnett** [comment]
As you have seen, I have added some macros to the FMS build to cope with these issues. When they have made it through review and been merged, I will add them to the AM4 configure as well, so this problem will not reoccur.
