### ISSUE TITLE
Peformance degradation between 2023.04 and current main

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1444]
**Describe the bug**

There is a small performance degradation between 2023.04 and the 2024.01-alpha2. 
For example, for ESM4.2, Main loop clocks are almost the same between 2024.01-alpha2 and 2023.04. The Initialization clock has increased a bit from 96secs to 125secs.

This is related to #1388. `nearest_index` is a bit slower than the indp (this was used in horiz_interp in 2023.04). Particularly the part of the code that checks that the array passed in is monotonically increasing/decreasing is not very efficient

**To Reproduce**
Compare initialization times between 2023.04 and 2024.01-alpha2. 

**Expected behavior**
Performance of FMS should be as best as possible.

**System Environment**
Describe the system environment, include:
This happens in any system, but I saw this in the amd box with the data_override unit tests and in GAEA.

**Additional context**
N/A

**Comment by uramirez8707** [comment]
closed in #1445

**Comment by thomas-robinson** [comment]
@uramirez8707 Do we need to reopen the original issue?
