### ISSUE TITLE
modern diag manager: remove non-standard time bounds

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FMS#1465]
**Is your feature request related to a problem? Please describe.**
FMS history output includes time bounds metadata both in CF standard and non-standard conventions.

The CF standard time bounds are:
```
	double time(time) ;
		time:units = "days since 1979-01-01 00:00:00" ;
		time:long_name = "time" ;
		time:axis = "T" ;
		time:calendar_type = "JULIAN" ;
		time:calendar = "julian" ;
		time:bounds = "time_bnds" ;
	double time_bnds(time, nv) ;
		time_bnds:units = "days since 1979-01-01 00:00:00" ;
		time_bnds:long_name = "time axis boundaries" ;
```

And the non-standard, duplicated, time bounds are:
```
	float loadpoa(time, grid_yt, grid_xt) ;
		loadpoa:_FillValue = 1.e+20f ;
		loadpoa:missing_value = 1.e+20f ;
		loadpoa:units = "kg m-2" ;
		loadpoa:long_name = "Load of Dry Aerosol Primary Organic Matter" ;
		loadpoa:cell_methods = "time: mean" ;
		loadpoa:cell_measures = "area: area" ;
		loadpoa:time_avg_info = "average_T1,average_T2,average_DT" ;
		loadpoa:standard_name = "atmosphere_mass_content_of_primary_particulate_organic_matter_dry_aerosol" ;
	double average_T1(time) ;
		average_T1:_FillValue = 1.e+20 ;
		average_T1:missing_value = 1.e+20 ;
		average_T1:units = "days since 1979-01-01 00:00:00" ;
		average_T1:long_name = "Start time for average period" ;
	double average_T2(time) ;
		average_T2:_FillValue = 1.e+20 ;
		average_T2:missing_value = 1.e+20 ;
		average_T2:units = "days since 1979-01-01 00:00:00" ;
		average_T2:long_name = "End time for average period" ;
	double average_DT(time) ;
		average_DT:_FillValue = 1.e+20 ;
		average_DT:missing_value = 1.e+20 ;
		average_DT:units = "days" ;
		average_DT:long_name = "Length of average period" ;
```

**Describe the solution you'd like**
The `average_(T1|T2|DT)` variables should not be included in modern diag manager history output.

(FRE-NCtools needs two corresponding updates tracked in https://github.com/NOAA-GFDL/FRE-NCtools/issues/273 and https://github.com/NOAA-GFDL/FRE-NCtools/issues/274.

**Describe alternatives you've considered**
Most standard Netcdf tools respect the CF standard time bounds but not the FMS time bounds, so it would make FMS output more usable to omit the non-standard time bounds.

**Additional context**
We previewed doing this at the MI meeting on 2024-02-14 and there were no protests.

**Comment by uramirez8707** [comment]
Fixed in #1505
