### ISSUE TITLE
Can we extend the size of this buffer so it doesn't cut off file paths?

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/FMS#1467]
**Is your question related to a problem? Please describe.**
Can the length of [this string](https://github.com/NOAA-GFDL/FMS/blob/main/interpolator/include/interpolator.inc#L130) be made larger?  Maybe `len=128`.   I have run into cases where this buffer is not large enough and it causes the code to crash.

**Describe what you have tried**
I have tried making this buffer `len=128` and that solved my issue.

**Comment by thomas-robinson** [comment]
Can you put in a PR with your solution?

**Comment by menzel-gfdl** [comment]
Sure. https://github.com/NOAA-GFDL/FMS/pull/1469
