### ISSUE TITLE
Option to use grid indexes for subsetting diagnostics 

### ISSUE THREAD

**Issue by theresa-morrison** [NOAA-GFDL/FMS#1485]
**Is your feature request related to a problem? Please describe.**
Within the diag_table, there is an option to specify only a subset of the domain to be saved in a diagnostic file, such as:
```
"ocean_bersea", 1, "days",  1, "days", "time"
"ocean_model", "MLD_003",   "MLD_003",   "ocean_bersea", "all", "mean",  "240.0  241.0  39.0  40.0  -1  -1",2
```
where the `240.0  241.0  39.0  40.0 ` defines the bounding Latitudes and Longitudes. This feature is extremely useful when saving data with high temporal frequency to avoid generating extremely large output files by only saving the relevant portion of the domain.

However, this feature uses the nominal Latitude and Longitude rather than the "true" Latitude and Longitude. This makes subsetting on a gird without regular spacing challenging. For domains with nonmonotonic Latitude, such as the Arctic regional grid, this subsetting scheme does not work at all. 

If the bounding box is outside the nominal Latitude and Longitude of the domain the error message is:
`FATAL from PE     0: diag_util_mod::get_subfield_size: can not find gstart_indx/gend_indx for MLD_003, check region bounds for axis  1`

Within the ocean model there is an option to specify `USE_GRID_SPACE_DIAGNOSTIC_AXES` which would allow us to use i and j instead of a bounding Latitudes and Longitudes: 
```
"ocean_bersea", 1, "days",  1, "days", "time"
"ocean_model", "MLD_003",   "MLD_003",   "ocean_bersea", "all", "mean",  "10 20 100 115  -1  -1",2
```
However this produced an error when I tested it:
```
 buffer_includes_halos: F  data_xsize:          23  xc_size:          24
  data_ysize:          27  yc_size:          28
```
which seems to come from `fms_netcdf_domain_io.F90`. 

**Describe the solution you'd like**
While this tool works using the nominal Latitude and Longitude, options to use the true Latitude and Longitude or the grid indexes will be extremely useful as we continue to develop regional models with complex grids.

**Additional context**
I am not sure if this is an issue for other model components or if the root of the problem is within FMS or MOM6. If using grid indexes was previously supported by FMS it should be restored. This will prevent the creation of unnecessarily large output files when saving high frequency diagnostics. 

To illustrate how important subsetting diagnostics is, we can consider the data that is needed to understand tidal mixing on the Bering shelf within the regional North East Pacific (NEP) model.  We need to save hourly data, but only for the locations corresponding to moorings within the Bering Sea. Two days of 3D u velocity data for the entire NEP domain is 320 MB, so we could expect ~58 GB for 1 year of the simulation. The subsetting a 1x1 degree region consistent with the mooring location reduces the size of the files to 76 KB which would be less than 15 MB for an entire year. These values are from a single 3D variable in a single netcdf file. Using subsetting reduces the amount of data saved by 99.97%. Saving 3D u velocity data with the hourly frequency necessary to resolve the tidal cycle would produce even larger files, two days of hourly 3D velocity data is 1.5MB even for the subset region. Currently this tool does not work with the regional Arctic grid, which uses nonmonotonic Latitude.

**Comment by thomas-robinson** [comment]
@theresa-morrison Using grid indicies is a feature in the new version of the diag manager.  We are currently in the testing phase before release.  I will contact you for further details.
