### ISSUE TITLE
Have configure check for Fortran handling of cray pointers

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#149]
The code uses cray pointers (see https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gfortran/Cray-pointers.html)

This requires a Fortran flag (-fcray-pointer for gfortran).

This should be checked by configure, so the user gets a good error message from configure instead of a compile time error.

**Comment by underwoo** [comment]
PR #181 has a check for this.
