### ISSUE TITLE
missing registered fields in diag_field_log.out

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FMS#1496]
**Describe the bug**
The diag_manager has a nml variable that will create a output log of all register_*_field calls, but during SPEAR runs the output log is missing some register calls in the FV3 code.

**To Reproduce**
Run the spear regression xml with `do_diag_field_log` set to true in the diag_manager namelist.

**Expected behavior**
the log should have every registered field.

**System Environment**
gaea c5 with intel23-classic

**Additional context**
It seems like the mom code is likely the culprit. i had the code print the pe for every write to the log, mom starts calling with a different root pe and that seems to erase whatever was in the file up to that point.

Thanks @wfcooke for spotting this!

**Comment by thomas-robinson** [comment]
@marshallward is there a MOM wrapper for this?

**Comment by wfcooke** [comment]
Ryan
Nice find.
Have you tried this with CM4? It shouldn't just be a SPEAR thing. I'll
guess that it is pe0 writing to the file and then pe2304 (or whatever the
MOM root-pe is) opening and clobbering the file.
Do we need two diag_field output files? MOM actually writes out its own
diag field output regardless (to available_diags.002304 in one of my runs)

Will

**Comment by marshallward** [comment]
@wfcooke I was under the impression that `available_diags.*` was a MOM6 product separate from the diag manager.  (i.e. it is created by the "diag mediatior" which uses the FMS diag manager).

Your explanation seems plausible, although I always had the impression that MOM6 was using the same diag manager as the other components.  (That is, all submodels were using the same module-level variables.)

**Comment by wfcooke** [comment]
Marshall
That's my impression too. MOM is producing the available_diags file of its
own accord.
With do_diag_field_log = true, there will be two copies of the MOM6 (and
SIS2?) in the output.

Does the code at
https://github.com/NOAA-GFDL/FMS/blob/7f585284f1487c0629f8075be350385e6e75dd2f/diag_manager/diag_manager.F90#L3928
try to open the same file with write permissions for ATM_ROOT_PE and
OCN_ROOT_PE?
Should that be append?

Will

**Comment by rem1776** [comment]
@wfcooke Yeah I believe thats the problem. The ATM root pe opens the file, and then the OCN root pe opens it again as a new file when it calls `diag_manager_init`. 

I have a PR in (#1497) to include the root pe number at the end of the filename, similar to what we do with stdlog. My first thought was to just open it in append mode as well, but as Rusty pointed out this way we won't run into any race conditions from two root pe's writing to the same file.

**Comment by marshallward** [comment]
You could just check if the file has already been opened before reopening it.  There is still a slight possibility of a TOCTOU race condition, but it would be much safer than the current approach.
