### ISSUE TITLE
`test_mpp_gatscat` causes compilation error with oneapi 2024.1

### ISSUE THREAD

**Issue by rem1776** [NOAA-GFDL/FMS#1504]
**Describe the bug**
ifort in the newest oneapi version runs into a (new?) compiler error when compiling one of the mpp tests
```
../../../test_fms/mpp/test_mpp_gatscat.F90(794): error #9156: Inquiring about the size, shape, or bounds of a local deferred-shape variable is not permitted in a specification expression.   [SBUFF]
     real :: sbuff1D(size(sbuff))
--------------------------^
```

**To Reproduce**
make check -C test_fms/mpp with oneapi 2024.1 and ifort

**Expected behavior**
tests should all compile successfully

**System Environment**
AMD box, oneapi 2024.1

**Additional context**
ifort is now deprecated, so this probably won't get fixed from the intel side

**Comment by bensonr** [comment]
I am surprised the test code compiles and works correctly with the current in place logic for any version of ifort.  How is one supposed to automatically size a variable based on a allocatable that hasn't been allocated.  

790  &emsp; real,allocatable,dimension(:,:) :: gather_data, cdata, sbuff,rbuff
794  &emsp; real :: sbuff1D(size(sbuff))
795  &emsp; real :: rbuff1D(size(rbuff))
