### ISSUE TITLE
Regional subsetting based on grid indices

### ISSUE THREAD

**Issue by ashao** [NOAA-GFDL/FMS#154]
The discussions about #93 bifurcated with one branch about a bug based when using the current geographically-specified subsetting with an irregular grid. Another branch, (which is where this issue comes from), is a feature request for the ability to specify the indices of the output arrays directly. 

Summarizing that discussion here:
@ashao: argues for the additional utility due to more accurate specification of transects, noting that `diag_tables` in `OM4_025` and `OM4_05` are 'tricking' the `diag_manager` to get the correct transects. An additional case where this level of control is necessary would be to provide output for open boundaries in regional models.
@thomas-robinson: notes potential portability issues due to ambiguity of integer, kind specifications in the Fortran standard leading to potential compiler-dependent behavior

The proposed way (from the MOM6 side) is to parse the 6-member tuple associated with the regional subset line of `diag_table` and if all 6 are integers, to assume that the user intended to specify the global indices of the array and NOT a geographic bounding box [minlon maxlon minlat maxlat mindepth maxdepth].

**Comment by wrongkindofdoctor** [comment]
Great! Thanks for opening this issue, @ashao. I (and the rest of the FMS crew) would prefer not to assume user intent based on whether the diag_table lines correspond to integers. It would be safer to have the user pass a flag (e.g., `use_global_indices` or `use_regional_indices`), that the diag_manager would interpret to determine the which routine to call.

**Comment by ashao** [comment]
I like that as well to make it less ambiguous.

**Comment by uramirez8707** [comment]
Fixed in #1505 
See [documentation]( https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/diag_yaml_format.md#26-sub_region-section) for more details
