### ISSUE TITLE
GEOS, FMS, and Constants

### ISSUE THREAD

**Issue by mathomp4** [NOAA-GFDL/FMS#155]
Dear GFDL,

This is more of a "meta" issue rather than a "real" issue, but since I don't know if you have a mailing list, this was my first choice for advice.

I work with Goddard's GEOS model which uses FMS for the FV3 dycore (and MOM5/MOM6). We've recently moved to GitHub and so we are trying to be good Git citizen. 

As such, we forked off your fine repo and placed our code on our fork in a branch on that fork. However, talking with Rahul Mahajan and Dan Holdaway (who work with JCSDA/JEDI who have _another_ fork), they are fairly certain we could work off your old `dev/master` which now seems to be `master`.

The only issue is to use FMS with GEOS requires changes to two or three files. The major one is `constants/constants.F90` because GEOS' constants are not exactly the same as the default constants and we want FV3/MOM (using FMS) to use the same constants as the rest of GEOS (physics, etc.).

So I guess my question is: is there a "best practices" path for constants? The lazy part of me would love to have our `MAPL_MODE` constants in your `constants.F90` a la `GFS_PHYS` but in a way that's the purpose of a fork! But I didn't know if perhaps there is a way to feed external constants to FMS in case the default ones are not consistent? (I'm doubting it since they are `parameter`.) And, since our `CMakeLists.txt` might be different from any you create, that's a good reason for a fork, too.

(Now beyond the constants, we have a couple of other changes we carry/are testing. One seems to be because we compile FMS at both 32-bit and 64-bit because we run FV3 at 32-bit, but MOM needs 64-bit and FMS isn't fully-overloaded. This caused an issue compiling `fms_io.F90` so I will file an issue about that. And we are testing a bug fix for the adjoint as I'm pretty sure there is a codepath that can never be reached...and we seem to be trying to use it! Now whether we should...)

**Comment by wrongkindofdoctor** [comment]
Hello, @mathomp4. Congrats on moving to github!  It can be a bumpy transition (as we know all too well at GFDL), but the ability to track development history and easily share your code with everyone else is worth it.

FMS (and FMScoupler) development is completely on github, and you can update your fork to the latest development stream by pulling from the master branch. Please note that we have not tagged a stable release yet, and that all updates in master are experimental (i.e., have not been fully-tested for reproducibility, etc... on the ORNL Gaea machine). 

While we have not created a formal guide of best practices for FMS development, I can generally recommend creating a separate module file for the GEOS constants that you can include where needed with a `module use statement`, and making sure that all constants are defined in the comments with units where applicable, even if it seems obvious what they are. While this is not as easy as adding what you need to the existing constants module in your fork, it will make debugging and updating easier down the line (e.g., if we update the constants module on our end, the changes are less likely to create merge conflicts in your code). 

As for the issue the 32-bit compilation, yes, please open another issue with your proposed fix. We welcome solutions for problems like this where the current code can be extended to accommodate GEOS needs, and that would benefit users and developers at GFDL.

**Comment by underwoo** [comment]
@mathomp4 do you still require assistance with the _correct way_ to add alternate constants to the FMS library, or have you decided to simply use your fork to have these additional constants?

**Comment by mathomp4** [comment]
@underwoo I suppose we'll just have to fork. The correct solution would probably be for constants to be supplied by a dictionary or the like, so none are ever defined, but for now I guess we fork.

**Comment by underwoo** [comment]
We understand keeping your fork separate.  We would be interested in coming up with a way to allow the GEOS constants in our FMS repository, and then allowing something at build time to determine which constants to adopt.  We are also interested in adding a CMake build process to the library (as this is something we have been asked about from several groups).  If you have time, and would like to discuss merging our two code bases into one usable repository, please let us know.
