### ISSUE TITLE
Make define_blocks warning a note

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1570]
**Describe the bug**
Whenever you don't have even blocks, you will get this warning

```
"WARNING from PE     0: atmos_modeldefine_blocks: domain (  16  12) is not an even divisor with definition (   1   8) - blocks will not be uniform
```

Because this is warning, every PE outputs that warning, which causes the stdout to be very lengthy

**To Reproduce**
Use an uneven block size and you will get that warning

**Expected behavior**
This should be a NOTE, so that only the root pe outputs that warning

**System Environment**
This happens in any system

**Additional context**
N/A

**Comment by bensonr** [comment]
For cases like the one you mention, everyone prints the warning and it isn't ideal.  But there may be cases where you do a non-even domain layout divisor and only certain mpi-ranks will be uneven.  For example, a c48 with a layout of 4,5 will give you 8 total domains of (12x9) and 12 total domains (12x10).  Using block size of 1,5 will only print warnings for those 8 (12x9) domains where the block sizes won't be equal.  

Let's modify the logic and message to output  "_N out of M total  domains have non-uniform blocks for layout (p,q) and blocksize (r,s)_"
