### ISSUE TITLE
FMS ignores coupler_nml calendar in favor of coupler.res calendar

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/FMS#1582]
**Describe the bug**
If there is a mismatch between the calendar specified in the coupler.res file and the coupler namelist, FMS uses coupler.res.

It would be less surprising to hard-fail when that happens.

**To Reproduce**
Set calendar to "noleap" in the coupler namelist and use a restart file with "julian".

**Expected behavior**
It would be less surprising to hard-fail when that happens.

**System Environment**
any

**Additional context**
https://helpdesk.gfdl.noaa.gov/otrs/index.pl?Action=AgentTicketZoom;TicketID=25039;ArticleID=285861#285201

**Comment by bensonr** [comment]
@ceblanton - that was the way it was designed such that coupler.res is dominant when in place.  If not, then the namelist will be used, i.e. for startup of a run.  

It's no different than having basedate in three, yes three, different places.  There is one in the namelist (lowest priority), one in the coupler.res, and yet another one in the diag_table.  Each location serves a purpose and right now I forget what happens (who wins) when the basedate in coupler.res and diag_table differ.  I know the one in the namelist gets completely ignored.

**Comment by ceblanton** [comment]
I sort of suspected that was desired behavior not a bug... Thanks!
