### ISSUE TITLE
namelist files should not be CLEANed in Makefile.am of tests

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#160]
When I tried to push my changes to the configure.ac for #159 , I see this:

```
ed@mikado:~/noaa/FMS$ git commit -m "now check for bats utility" -a && git push
[ejh_test f17fc7f] now check for bats utility
 15 files changed, 6 insertions(+), 271 deletions(-)
 delete mode 100644 test_fms/axis_utils/input.nml
 delete mode 100644 test_fms/drifters/input.nml
 delete mode 100644 test_fms/fft/input.nml
 delete mode 100644 test_fms/field_manager/field_table
 delete mode 100644 test_fms/field_manager/input.nml
 delete mode 100644 test_fms/horiz_interp/input.nml
 delete mode 100644 test_fms/interpolator/diag_table
 delete mode 100644 test_fms/interpolator/input.nml
 delete mode 100644 test_fms/monin_obukhov/input.nml
 delete mode 100644 test_fms/mpp/input.nml
 delete mode 100644 test_fms/mpp/input.nml_base
 delete mode 100644 test_fms/mpp_io/input.nml
 delete mode 100644 test_fms/time_interp/input.nml
 delete mode 100644 test_fms/time_manager/input.nml
```

Well that's not good! What is happening is that the namelist files are listed as EXTRA_DIST (which is correct) and also as CLEANFILES (which is incorrect).

CLEANFILES should never list anything in EXTRA_DIST, that's going to break the build. What will happen is that developers will do a "make clean" in the course of their work, and then they will commit the results, and if they do not notice, they will commit a delete of all the namelist files, which will break their build.

Why were we trying to clean the namelist files? Are they changed during the tests?

**Comment by underwoo** [comment]
Thank you for pointing this out.  What should be in each is a base namelist file (e.g. input.nml_base as in diag_manager), and the `input.nml` will be deleted, as it does need to change for each test --- a bad design, but we simply yanked these tests out of the main Fortran modulefiles and put them in their own test files; we do have plans to update the tests during our rewrite of the FMS library components.

We will work on correcting this.

**Comment by edwardhartnett** [comment]
I have a PR that I'll be putting up.

If they change during testing, does that mean "make check" will fail if I run it twice?

**Comment by edwardhartnett** [comment]
OK, just rereading your comment. Do you want the repo namelist to be called something like input_base.nml, and then have that copied to an input.nml which can be changed during testing and then cleaned?

That can be easily done with configure. If I have explained it correctly, let me know and I will add it to my PR. No need to change your tests, this can work fine.

**Comment by underwoo** [comment]
It is more complicated than that.  The way the tests are written (we didn't change them when we put them in place) the same source is used to run multiple tests.  Each requires a slight change in a base `input.nml` file which indicates which test to run.  Currently no way to tell FMS which file to read --- it always reads `input.nml`.  Thus, what is done is a `sed` is performed before each test to change the namelist parameter.

I think getting the tests into a better state might be quite a bit of work, especially since the tests are run in parallel.

I didn't notice this since I always build in a separate directory.  Doing so does not remove the files on a `make clean`.  I'll take a look to see what I can do to correct this (and possibly remove the `bats` requirement) over the weekend.

**Comment by edwardhartnett** [comment]
OK, I have a pr up for the axis_util (#164).

Is that correct?

I have been looking at these, and I haven't yet seen any use of sed in any of the scripts.

Getting the tests into better shape (at least in this regard) is something I hope to contribute today. ;-)

I suggest we should get this working today, with bats, and then tackle bats removal as a separate problem. I suggest that when you remove bats, you switch to the way that netcdf-c and netcdf-fortran do tests with shell scripts, it is simple and easy.

**Comment by edwardhartnett** [comment]
OK, I am starting to apply this to other directories. There are some twists and turns here, so I'm not going to do it all in one PR. I will isolate the changes so they can be reviewed.

@wrongkindofdoctor, now that this PR has been approved, if you can merge it to master, it will make some of the other PRs more clear to review.
