### ISSUE TITLE
Issues with dt < 1

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/FMS#168]
I have a MOM6 test case with dt = 0.2. I can see that it's running fine in the debugger, with the Time incrementing by 1 second every fifth timestep. The Time ticks remain at zero, for what it's worth.

The problems I'm having are:

- No ocean.stats.gnu output - should be every second.
- No prog.nc output - should be once a minute.
- The run fails to stop after 120 seconds, but eventually dies with:

> FATAL: diag_manager_mod::send_data_3d: module/output_field ocean_model/u is skipped one time level in output data

**Comment by underwoo** [comment]
@kshedstrom I can think of several reasons this would happen.  It is possible you have in your diag_table a variable going to one of the files that doesn't have a `send_call` frequently enough to be output at the frequency you have specified.  Looking through the MOM6 source code, I see calls like:

```Fortran
            call step_MOM(forces, fluxes, sfc_state, Time2, dtdia, MOM_CSp, &
                          do_dynamics=.false., do_thermodynamics=.true., &
                          start_cycle=(n==1), end_cycle=.false., cycle_length=dt_forcing)
```

The `do_dynamics=.false.` will keep the MOM dynamics from being sent to `diag_manager` for output.  Thus, I think this is more than likely your issue.

**Comment by kshedstrom** [comment]
Thanks for pointing that out. It was the dt_forcing that was too long, inherited from some other run. All is well now!
