### ISSUE TITLE
MOM6 variable checksum in the restart file has the first bit missing

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#176]
MOM6 restart variable u was flagged as different in a restart test:
```
DIFFER : VARIABLE : u : ATTRIBUTE : checksum : VALUES : "8948FCDFB62AA35C" <> " 948FCDFB62AA35C"
```

However the data was identical upon inspection of the files. 

Note that the 2nd checksum has the left-most bit missing (' '). How could this happen?

```
nccmp -d  /lustre/f2/scratch/Niki.Zadeh/tmp/ardiff.gaea15.49071.0b1mNHE0s1/first/MOM.res_3.nc /lustre/f2/scratch/Niki.Zadeh/tmp/ardiff.gaea15.49071.0b1mNHE0s1/second/MOM.res_3.nc
```

**Comment by wrongkindofdoctor** [comment]
It looks like there's a typo being introduced somewhere before or during the file read or write procedure. Did someone change the calls to restore_state or save_restart, or anything in those routines? Or, is this an issue with frecheck if you are using it to compare the restarts?

**Comment by nikizadehgfdl** [comment]
This is not a frecheck issue. The second restart file really has a missing character in the checksum.
```
 % ncdump -h /lustre/f2/scratch/Niki.Zadeh/tmp/ardiff.gaea15.49071.0b1mNHE0s1/first/MOM.res_3.nc | grep u:checksum
                u:checksum = "8948FCDFB62AA35C" ;
% ncdump -h /lustre/f2/scratch/Niki.Zadeh/tmp/ardiff.gaea15.49071.0b1mNHE0s1/second/MOM.res_3.nc | grep u:checksum
                u:checksum = " 948FCDFB62AA35C" ;
```

I doubt this is due to any recent code change, this test was done with xanadu_esm4_20190304 release and mom6_2019.08.08. 

I have a feeling this might not be a reproducible issue since this test has run without such issues before.

**Comment by wrongkindofdoctor** [comment]
All right. We'll file this under 'probably nothing, but will investigate further if it occurs again'.
