### ISSUE TITLE
Warning about argument aliasing in fms_io.F90

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/FMS#18]
It is only a warning but nevertheless I think it is bad practice to alias arguments with conflicting intents. The compiler could legitimately do exactly the wrong thing and overwrite file_out before reading file_in.

```
../../../../../MOM6-examples/src/FMS/fms/fms_io.F90:7385.33:

       call get_mosaic_tile_file(actual_file, actual_file, is_no_domain, domain, tile_count)
                                 1
Warning: Same actual argument associated with INTENT(IN) argument 'file_in' and INTENT(OUT) argument 'file_out' at (1)
```

**Comment by adcroft** [comment]
I should have said I was trying commit 03b40242f003b04b4225a7884aeb15d3d7407f83 on branch user/z1l/dev but I see this line in the tagged code too.

**Comment by underwoo** [comment]
@adcroft is this still an issue? (Not sure why I hadn't noticed this before).

**Comment by wrongkindofdoctor** [comment]
Closing this issue since the new IO will eliminate this behavior.
