### ISSUE TITLE
DIfferent values in MOM diagnostic files generated by old and new I/O

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#180]
@thomas-robinson, @menzel-gfdl 
**Describe the bug**
There are small discrepancies in single values of some variables in the MOM diagnostic files generated by the new I/O and old I/O routines. Most of the files only have differences in the coordinate variables _yh_ and _yq_, but one file has differences for the time coordinate variables _average_T1_, _average_T2_, and _Time_bnds_. There are also differences in initial values of some fields that likely originate from different definitions/uses of the netCDF _fillValue_ and _missingvalue_ attributes in the old and new IO routines.

**To Reproduce**
The files were generated running the MOM6_solo_globabl_ALE_z experiment on 36 pes compiled with gnu7 in debug. All experiments were run for 2 days using the MOM6 dev/gfdl code pulled on 09/27/2019.  

**Expected behavior**
The following table shows the diffs in diagnostic files from a continuous (non-restart) 2-day run:

variable [position] | old value | new value | file name(s)

yh [172 (final value)]  |  65.4642  |  64.9737 |  ave_prog.nc, cmor2.nc, cmor.nc, cmor_z.nc, cont.nc, forcing.nc, ocean_static_cmor.nc, ocean_static.nc, prog.nc, prog_z.nc, sfc_avg.nc, surface.nc, tracer.nc, visc.nc

yq [172 (final value) | 65.9494 | 64.9737 | ave_prog.nc, cmor2.nc, cmor.nc, cmor_z.nc, cont.nc, forcing.nc, ocean_static_cmor.nc, ocean_static.nc, prog.nc, prog_z.nc, sfc_avg.nc, surface.nc, tracer.nc, visc.nc

salt_flux [0,0,0] (first value) | 0  |  1e20 |  forcing.nc

total_salt_flux [0,0] (first value) | 0  |   1e20 |  forcing.nc

average_T1 [0] (first value) | 1.5 |  1  | forcing.nc

average_T2 [0] (first value) | 2 |  1.5  | forcing.nc

time_bnds [1,0] | 1.5, 1 | forcing.nc

**System Environment**
Describe the system environment, include:
- OS: RHEL 7
- Compiler(s): Gnu 7
- MPI
- netCDF Version: netcdf-c [4.4.0], netcdf-fortran [4.4.2]
- Configure options: -Duse_netCDF3  

**Additional context**
The calls to diag_manager originate [here ](https://github.com/wrongkindofdoctor/MOM6/blob/7add72bd787691401925de23a6c84f2f147f4570/src/core/MOM.F90#L788)

The routine calls the diag_manager wrapper functions in [MOM_diag_mediator](https://github.com/wrongkindofdoctor/MOM6/blob/user/jml/operation_fms2_the_reckoning/src/framework/MOM_diag_mediator.F90). 

The above routines add extra layers of complexity, but don't seem to be the source of the problem at first glance.

**Comment by wrongkindofdoctor** [comment]
The last values in the _lath_ and _latq_ coordinate variable arrays in the MOM_restart files are also slightly off, which suggests that there is an issue with the _domain_position_ values passed to the _register_axis_ routine.

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor can you point me to an XML or experiment set configuration so I can run it?  Does it require a lot of cores?  Does this problem show up with the intel compiler?

**Comment by wrongkindofdoctor** [comment]
Yes, this problem occurs with the intel compiler, too. The experiment only requires 36 cores (1 C4 or 2 C3 nodes). I'll email you the files and build paths.

**Comment by wrongkindofdoctor** [comment]
I have implemented a [procedure](https://github.com/wrongkindofdoctor/MOM6/blob/3b2f162a54843d003b05f6a2dc677ff448b2e06f/src/initialization/MOM_grid_initialize.F90#L460) to search for a longitude in the temporary global data array that corresponds to the full range of used to define lath and latq in the restart and diagnostic files. The [original procedure](https://github.com/NOAA-GFDL/MOM6/blob/4bcd442096007032b3bdf91b1fe2b5bd40f9d19e/src/initialization/MOM_grid_initialize.F90#L396) assumes that the first longitude value contains the full latitude (y) range, but this is not the case for the the new IO.

**Comment by edwardhartnett** [comment]
Is this new I/O branch to be merged soon?

One thing that will really speed development is to have tests before you do large refactorings. I understand the programmer view of "why should I write tests for code that I'm going to re-write?" The answer is that with good tests refactoring is much faster and safer.

Once you get it merged, perhaps I can contribute some basic I/O code tests which can help ensure that future changes to the I/O code proceed safely and quickly. 

Or, even better, perhaps you have written a bunch of I/O code unit tests as part of your refactor?

**Comment by wrongkindofdoctor** [comment]
The Gaea outage in October delayed development for several weeks, but we are able to start in-depth testing on the land code. FMS will be tagged with an alpha release either today or tomorrow. MOM6 has a projected alpha tag date range some time in the final two weeks of November. We have some tests in the test_fms directory in the fms-io-dev branch, and will likely add more as we refine the requirements. We appreciate efforts to contribute to tests, so please submit PRs for tests you think would be valuable.

**Comment by edwardhartnett** [comment]
OK, when you say tagged with release, do you mean you are doing an actual release on github?

Or is this one of those things where you just give all the repos the same tag?

The difference is that in the first scenario, the FMS will be built from versioned tarball. (Like netCDF). In the second scenario, everyone is still cloning from github, but they are cloning a branch.

If this is an actual release, you need to decide a version number, and you can start using the libtool shared library versioning, which enables shared libraries to work portably and very usefully.

If you are doing the second scenario, you will be releasing a bunch of shared libraries into the wild, and then later, releasing more with different code but the same share library version info. This will break shared libraries.

**Comment by wrongkindofdoctor** [comment]
All of the relevant repos (FMS, ice_amip, ocean_amip for land, MOM6, FMS, ocean_BGC for the ocean) will receive the tags 1.0-alpha-yyyymmdd when ready. These tags are intended primarily for GFDL developers to run extensiveend-to-end tests on the production system and report any bugs or request additional features (though external users may also run their own tests with the tags if they wish). 

FMS will release a final 'Z' version using old tagging nomenclature likely before the end of the year, and the offical release with new IO in all repos is planned for early February 2020 provided that the production system is operating as expected, and the team has access to necessary resources for the next few months.

**Comment by edwardhartnett** [comment]
When you tag your 1.0 (not alpha, but the actual 1.0 release), you will be doing a github release at that time - is that correct? 

And that's what your are mentioning as the "official release" with new I/O scheduled for February?

**Comment by wrongkindofdoctor** [comment]
I don't think there are plans to include a tarball, but I'll cede to @underwoo to confirm.

**Comment by edwardhartnett** [comment]
You must do an autotools release as well as tagging the code, or shared libraries will not work correctly.

You need to update the shared library version-info numbers for each release, and if you don't then shared libraries will not work correctly for FMS. This is a significant cost.

Also there may be plenty of HPC and other science systems which do not have autotools installed, so those systems could not build your code as a clone of a tagged release. (Also git is not installed or may be hard to use on many HPC systems due to security issues.)

When you build from tarball, you don't need autotools, you don't run the "autoreconf -i" command, you just untar and ./configure && make check.

To create a release:
* update your version number in configure.ac as you wish.
* update your version-info number in accordance with strict shared library rules.
* add some optional release notes, hit the release button on github (identifying your tag), 
* checkout that tag and do a "make dist" which builds the tarball: fms-1.0.tar.gz
* upload that tarball to the github release page under binary resources.

This will not affect whatever internal systems you have based on a cloned tag. Those will still work exactly the same.

You can create the tag and then do a release, or github will tag master for you if you want, when you do a release. Either way, you get whatever tag you want.

**Comment by wrongkindofdoctor** [comment]
This issue originates in the MOM_grid_initialize module where temporary arrays are allocated to read in slices of the _x_ and _y_ data corresponding to the full ranges of latitude and longitude coordinates that are used to define the diagnostic _lath_, _latq_, _lonh_, and _lonq_ axes. Referencing the original ranges using the indices for the slices does not match the locations in the temporary array holding the _y_ values read in with the new_io, causing incorrect _lath_ and _latq_ values downstream. 

A workaround for this issue  is to search each row of the temporary array holding the _x_ data for the full range of longitudes, and use the result to define _G%gridLatT_ and _G%gridLatB_.  This procedure will be implemented in a MOM_read_data interface routine specifically for this scenario (not ideal, but meets the MOM6 requirement for unchanged interfaces for the reading/writing).
