### ISSUE TITLE
Travis CI `make distcheck` not passing configure options

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#202]
**Describe the bug**
When testing the `--without-openmp` build in Travis CI, it was discovered the `make distcheck` does not pass the configure options to the distribution check call to configure.

**To Reproduce**
autoreconf -if
./configure --without-openmp
make distcheck

**Expected behavior**
Both builds should build without openmp support.

**System Environment**
All systems running `make distcheck` if passed in configure options

**Comment by edwardhartnett** [comment]
This can be accomplished by setting environment var DISTCHECK_CONFIGURE_FLAGS before running make distcheck.

I thought this had been resolved but apparently not. Do you want me to submit a PR adding openmp testing to the existing travis testing?

**Comment by edwardhartnett** [comment]
Is this not working for you?

**Comment by underwoo** [comment]
It is.  I thought the commit that changes this was in (but this issue didn't get closed).  The PR that has the fix will be merged after a few other PRs are merged as I'll need to do some additional work on the autotools PR.  Hopefully by the end of the week that PR will be merged.
