### ISSUE TITLE
What is test issue that prevents tests from running on Darwin?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#209]
I believe someone explained it to me at one point, but I can't find the explanation, so I have to ask again...

What is the reason we see this in bats files?

```
setup () {
  if [ "x$(uname -s)" = "xDarwin" ]
  then
    skip_test=true
  else
    skip_test=false
  fi
}
```

What is it about Darwin that causes these tests to fail?

Instead of just identifying Darwin as the culprit, can we drill a little deeper to what actual feature is missing on Darwin? Then we can test for that feature in configure.ac, and use that to determine whether these tests can be run.

Also, I would expect that if Darwin breaks so many tests, that the code does not really work on Darwin. So instead of just turning off tests, maybe you should give the user an error message at configure time, saying that Darwin does not work?

**Comment by edwardhartnett** [comment]
This seems to have morphed into #241 

I will close this issue and continue with this under #241

**Comment by edwardhartnett** [comment]
OK, I was wrong this was not resolved. In test_fms/mpp/test_mpp_domains2.sh I see:
```
if [ "x$(uname -s)" = "xDarwin" ]
then
    skip_test=true
else
    skip_test=false
fi

```

Then later, the skip_test var is checked and tests are skipped on Darwin. So again, why is this happening? Let's put a proper fix in place for this...

We want to detect what the problem is (not just that we are on a Darwin system, but what is the actual problem with that system). Then we want to handle that problem in a standard way. It seems unlikely that we just want to skip all these tests. What's the point of that?

**Comment by underwoo** [comment]
I am now looking into why we still need to skip the Darwin tests.  Originally, it was due to Darwin not having a specific C routine, but that has been addressed.  I am working through all the tests to check if they work on Darwin and if not, why.

**Comment by underwoo** [comment]
While looking through the tests, I managed to fix two tests that were skipped which are in #650.  Other work on getting more tests on darwin (and hopefully under GitHub Actions) to run is going well.  I'm updating the tests to output in TAP to hopefully give us a better idea on which specific test failed.  This will be useful as some of the test scripts run many tests.
