### ISSUE TITLE
block_control.F90 does not have IMPLICIT NONE

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#210]
**Describe the bug**
block_control.F90 does not have `IMPLICIT NONE` in the source, and therefore may have implicitly defined variables.

**To Reproduce**
Compile with `-fimplicit-none` (for GFortran).

**Expected behavior**
The block_control.F90 file should compile if `-fimplicit-none` is given on the compile command line.

**System Environment**
All systems/compilers affected

**Comment by bensonr** [comment]
I will add this in as part of a pull request fixing #214
