### ISSUE TITLE
Axes attribute initialisation

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/FMS#22]
Axes%num_attributes is not initialised. Since it can take any value this can cause problems such as array bounds overruns.

**Comment by nicjhan** [comment]
Example failure output:

https://climate-cms.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=gnu,experiment=ocean_only-benchmark,memory_type=dynamic/28/console

**Comment by underwoo** [comment]
Thank you for reporting this. We will get it fixed and update the dev/master branch.

**Comment by underwoo** [comment]
#23 merged.
