### ISSUE TITLE
CRAY variable in configure.ac should be more descriptive

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#239]
**Is your feature request related to a problem? Please describe.**
The automake conditional variable `CRAY` should be more descriptive, as it can lead individuals to think this is a problem on Cray systems, and not just Cray systems that use the Cray Programming Environment, and do static linking by default.  

**Describe the solution you'd like**
A name like: `CRAY_PRGENV_STATIC` may work.

**Other things to consider**
Where `CRAY` is used in the Makefiles will also need to be updated with the new name.

**Comment by edwardhartnett** [comment]
OK, the AM_CONDITIONAL CRAY is actually not used anywhere in any Makefile.am. So it can be removed.

Where is there special handling for CRAY?

**Comment by underwoo** [comment]
It does appear that the `CRAY` variable in `configure.ac` is no longer used.  After some testing on gaea to verify it is not needed, I'll remove it.

**Comment by underwoo** [comment]
While working on #651, I remembered the reason for the `CRAY` autoconf variable.  Some cray systems default to link in static libraries.  However, the default library used when building the tests is a shared library, which the Cray system attempts to link in statically -- causing a link error.  The `CRAY` variable was used (at some time) to force static linking for the test programs.

I believe I have an update that will resolve this issue, with an explication.  The update should also allow users to override the update if they know doing so is safe on a given Cray system.
