### ISSUE TITLE
Should the FMS build work without MPI?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#242]
**Describe the bug**
I have heard from @underwoo that the FMS should build without MPI (as well as with it). But when I try, configure fails, telling me that MPI is required. If I remove this check, the build will fail in the drifters code, which requires MPI.

**To Reproduce**
Build without setting CC and FC to mpi compilers.

**Expected behavior**
If it is supposed to build without MPI, then the configure should detect whether an MPI compiler is provided, and, if not, should succeed in building without MPI. 

**System Environment**
All.

**Additional context**
If you can give me direction on what to do about components like drifters which don't build without MPI, I would be happy to make these changes.

**Comment by uramirez8707** [comment]
@edwardhartnett What error(s) are you getting?

**Comment by underwoo** [comment]
Issue #635 and PR #637 will allow FMS to build w/o MPI.  Since we now have discussions (https://github.com/NOAA-GFDL/FMS/discussions), that is a better place for questions like this.  I'm closing this issue.
