### ISSUE TITLE
Can I add some tests for fms2_io and other modules in support of PIO integration?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#244]
**Is your feature request related to a problem? Please describe.**
To support future IO work, I would like to add some tests for the I/O code, mpp/mpp_io.F90.

**Describe the solution you'd like**
I will add a .F90 test program, and unit test some of the functions in mpp_io.mod. Preferably with and without using MPI.

**Describe alternatives you've considered**
There is no alternative to good testing, if you want your code to be correct.

**Additional context**
I'm happy to keep these tests up to date with the upcoming new IO code, or else to write these tests on that branch, for the new code.

This is in support of #100

**Comment by underwoo** [comment]
It might be best to use the new FMS code in branch `fms-io-dev`.  @wrongkindofdoctor can help direct your efforts in writing these tests, as they may already have some written.

**Comment by underwoo** [comment]
The new fms_io code is now in the master branch.  We will do some cleanup on the MPP code, but feel free to write whatever check tests you would like.

**Comment by edwardhartnett** [comment]
OK great! At the moment I am adding some new compression options to netcdf. (Look for them soon!)

I will circle around to this again and add some tests...

**Comment by edwardhartnett** [comment]
This should not be closed. THere are more tests coming.
