### ISSUE TITLE
affinity/test_affinity not tested with`make check` under autotools

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#252]
As part of the updates for the thread affinity code, a [test_affinity.F90](../blob/master/affinity/test_affinity.F90) was created.  However, this file was not added to the autotools `make check` tests.  This should be included in the suite of tests.

**Comment by uramirez8707** [comment]
@underwoo I can work on this.

**Comment by underwoo** [comment]
Thank you @uramirez8707.  An FYI, it looks like the test_affinity.F90 will not compile/link due to a possible renaming of `fms_set_affinity` to `fms_affinity_set` in [affinity/fms_affinity.F90](../blob/master/affinity/fms_affinity.F90).  Please correct that and add in the bits to test affinity.  The following lines of code added to the [affinity/Makefile.am](../blob/master/affinity/Makefile.am) should be sufficient:

```Makefile
check_PROGRAMS = test_affinity
test_affinity_SOURCES = test_affinity.F90
test_affinity_LDADD = ${top_builddir}/libFMS/libFMS.la

TESTS = test_affinity
```

Note, an 'input.nml' will need to be created as well.  Please work with @bensonr to find out if there are any additional settings that should be tested (e.g. with/with out hyperthreads).
