### ISSUE TITLE
FMS does not allow more that 1024 diagnostic files

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/FMS#27]
The diag_manager_nml has a max_files options however once this is over 1024 it has no effect. This is because the maximum number of netcdf files is hard-coded in mpp/include/mpp_io_misc.inc:42 to 1024.

When doing MOM6 diagnostic testing we currently write each diagnostic to a separate file. We have reached this limit.

If we write many diags to the same file then we exceed MAX_FIELDS_PER_FILE which is hard-coded to 300 at diag_data.F90:78

**Comment by underwoo** [comment]
Thank you for reporting this.  We have started an internal discussion to see how/if we will address this.
