### ISSUE TITLE
Remove platform/platform.F90 and use iso_fortran_env instead.

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/FMS#271]
**Feature request**
The only purpose of the platform/platform.F90 module is to provide kind parameters.
Fortran now provides intrinsic modules that can be used instead.

**Proposed solution**
Replace lines that contain:
```use platform_mod, only: r8_kind, etc.```
with
```use, intrinsic :: iso_fortran_env, only: real64, etc.```

**Additional context**
This can also be used to eliminate lines that contain:
```#include "fms_platform.h"```
in many modules.

**Comment by underwoo** [comment]
We have plans to modify how fms_platform.h and the platform_mod are used.  We may not eliminate them, but will likely use the platform_mod to _wrap_ the iso_fortran_env.  This will eliminate the possibility of one module in FMS using a different real, int, etc from another.

**Comment by GFDL-Eric** [comment]
Does the mixed precision work impact this at all? I know within that project we've already eliminated most instances of platform.h, but would it just be better to use the fortran intrinsic, or is that going to throw problems with some of our compilers?

**Comment by menzel-gfdl** [comment]
I'm not sure why it would impact the mixed precision work?  My opinion is that using the intrinsic module is better, but
I did not test which compilers support it.

**Comment by GFDL-Eric** [comment]
Seth mentioned using the same real, int in the same modules... I thought this was a reference to precision but maybe I misunderstood.

**Comment by wrongkindofdoctor** [comment]
@menzel-gfdl The mixed-precision work includes replacing the #include platform.h lines with use platform_mod, and replacing all of the type definitions in the mpp code. Switching to the iso fortran types would mean that someone (probably me) would have re-do the work (not a huge deal, just tedious). I have no preference about the choice of type definitions, but would like a decision before January if at all possible.

**Comment by menzel-gfdl** [comment]
@wrongkindofdoctor @GFDL-Eric ok I see.  I like using the parameters from `platform_mod` much more than
the `#include`.  Can we just have `platform_mod` point it's kind parameters to the ones defined in `iso_fortran_env`?
And if a compiler doesn't support the intrinsic module, then we could wrap the statements in an `#ifdef`?

**Comment by rem1776** [comment]
Closing this since it looks like it was resolved by the mixed precision work, platform_mod now points to intrinsic kind values.
