### ISSUE TITLE
Time_interp_external does not read times correctly

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#278]
**Describe the bug**
In time_interp_external2.F90, [L360](https://github.com/NOAA-GFDL/FMS/blob/24005637ff5faf10c4d946bf8e732da5d239b395/time_interp/time_interp_external2.F90#L360), the code is reading `average_T1` as `tstart`, `tend` and `tavg` ...

```F90
      if(variable_att_exists(fileobj, fieldname, 'time_avg_info')) then
        if(variable_exists(fileobj, 'average_T1')) call read_data(fileobj, 'average_T1', tstart)
        if(variable_exists(fileobj, 'average_T2')) call read_data(fileobj, 'average_T1', tend)
        if(variable_exists(fileobj, 'average_DT')) call read_data(fileobj, 'average_T1', tavg)
      endif
```

**To Reproduce**
Run any experiment that doesn't use an empty diag_table and you would see answer changes

**Expected behavior**
The code should read `average_T2` as `tend` and `average_DT` as `tavg` ...

**System Environment**
Describe the system environment, include:
Any system

**Additional context**
This is one(?) of the reasons why answers are diffing from xanadu.

**Comment by uramirez8707** [comment]
Also `tavg` is not used anywhere in the code so we can *probably* get rid of it

**Comment by wrongkindofdoctor** [comment]
@underwoo Can we merge this now since it's critical for regression testing?
