### ISSUE TITLE
Regional diag output needs update for non-domain decomposed write

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#281]
**Describe the bug**
Regional diagnostic output does not work because it is it being opened as a domain decomposed file.  In the case of regional output, every core should be writing its own file.

**To Reproduce**
Run with regional diagnostic output

**Expected behavior**
The files should be written on a per-core basis and not using the io_domain

**System Environment**
This is all environments.

**Additional context**

**Comment by thomas-robinson** [comment]
@menzel-gfdl @nikizadehgfdl please add any context that I have missed to this issue for tracking.

**Comment by nikizadehgfdl** [comment]
The symptoms are
```
FATAL from PE    12: input domain does not have an io_domain.
```

@thomas-robinson Here's a xml/experiment that let's you reproduce this issue on a 64 pes.
However before that you'll need to merge Ray's and Eric's updates to FMS/master (which this xml checks out). You'll also need to merge PR #284 . 

```
git clone -b RTS git@gitlab.gfdl.noaa.gov:mdt/xml.git mdt_xml_RTS
cd mdt_xml_RTS
module load fre/bronx-15
fremake -x OM4_extra_postxanadu.xml -p ncrc4.intel16 -t prod MOM6_SIS2_compile
frerun -x OM4_extra_postxanadu.xml -p ncrc4.intel16 -t prod MOM6_GOLD_SIS2_bergs -r debug --no-transfer
```

**Comment by thomas-robinson** [comment]
@nikizadehgfdl which updates specifically need to be merged in?

**Comment by nikizadehgfdl** [comment]
@thomas-robinson  #283  #284  #285

**Comment by thomas-robinson** [comment]
@nikizadehgfdl `MOM6_GOLD_SIS2_bergs` ran to completion.  Is there a different experiment I should try?

**Comment by nikizadehgfdl** [comment]
@thomas-robinson  Do you mean after you fixed  the regional diagnostics or before any such fix?
Please make sure there is the following lines in the diag_table:
```
"ocean_Drake_Passage",           1, "days",   1, "days", "time"
"ocean_model_z", "thetao","thetao",  "ocean_Drake_Passage",    "all", "mean", "-70. -70. -71. -54.5 -1 -1",2
"ocean_model_z", "so",   "so",       "ocean_Drake_Passage",    "all", "mean", "-70. -70. -71. -54.5 -1 -1",2
"ocean_model_z", "umo",  "umo",      "ocean_Drake_Passage",    "all", "mean", "-70. -70. -71. -54.5 -1 -1",2
"ocean_model_z", "uo",   "uo",       "ocean_Drake_Passage",    "all", "mean", "-70. -70. -71. -54.5 -1 -1",2
```

If you fixed it and want to try other tests then you can try the other xml/experiment
```
frerun -x OM4_COBALT_postxanadu.xml -p ncrc4.intel16 -t prod OM4p5_CORE2_IAF_COBALT_abio_csf_mle200 -r debug -u --no-transfer
```

**Comment by thomas-robinson** [comment]
@nikizadehgfdl are the files supposed to come out like 00010101.ocean_Barents_opening.nc.**0054** or 00010101.ocean_Barents_opening.nc.**54**?  What is the format of the numbers on the end?
