### ISSUE TITLE
Replace `#include <mpif.h>` with `use mpi` on default platforms

### ISSUE THREAD

**Issue by marshallward** [NOAA-GFDL/FMS#30]
Some hiccups on our system's wrapper scripts revealed that FMS models are still doing `#include <mpif.h>` to import the MPI symbols, even though the standard recommends the module (`use mpi`).

Currently only the `sgi_mipspro` flag enables `use mpi`.  The default is to use the CPP `#include` statement.

----

To be annoyingly pedantic (sorry!), here are some quotes from the MPI 3.1 standard.

p605:

> **INCLUDE ’mpif.h’:** This method is described in Section 17.1.4.  The use of the include file `mpif.h` is strongly discouraged starting with MPI-3.0, because this method neither guarantees compile-time argument checking nor provides sufficient techniques to solve the optimization problems with nonblocking calls, and is therefore inconsistent with the Fortran standard.  It exists only for backwards compatibility with legacy MPI applications.

p611:

> The use of the `mpif.h` include file is strongly discouraged and may be deprecated in a future
version of MPI.

The comments above refer to the Fortran include statement (`include 'mpif.h'`); the standard doesn't even consider using the CPP include, which is probably even more strongly discouraged.

----

Rather than send a patch, I figured that you guys might be more aware of any odd platforms that still require this and would be in a better position to make the change.

**Comment by underwoo** [comment]
@marshallward apologies for missing this until now.  I have taken your suggestion into our internal issue tracker.  We will let you know of our decision to switch to `use mpi` instead of `#include <mpif.h>` in Fortran sources.
