### ISSUE TITLE
Add option for the user to specify the mpi launchers they want to use?

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#300]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The configure script should allow the user to specify what mpi launcher they want to use, something like `./configure --mpi_launcher="mpirun"`

The configure script will then check that the launcher is in the path and use it ...

**Describe alternatives you've considered**
Currently the configure script "picks" the launcher for you 

**Additional context**
N/A

**Comment by uramirez8707** [comment]
@underwoo is this what you had in mind?

**Comment by rem1776** [comment]
Closing because this can be manually set now with the MPI_LAUNCHER environment variable
