### ISSUE TITLE
cannot recompile if source files are modified

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#301]
**Describe the bug**
When I modify FMS source code (to debug) the recompile fails with internal compiler error (Intel16,18) like:
```
ftn -DINTERNAL_FILE_NML -g -Duse_libMPI -Duse_netCDF -DMAXFIELDMETHODS_=500 -D_FILE_VERSION=\"`git-version-string /lustre/f2/dev/Niki.Zadeh/master_20200210_mom6_ESM4_v1.0.3/20200128/esm4.1_libs_compile/src/FMS/fms2_io/fms_netcdf_domain_io.F90`\" -Duse_netCDF -DHAVE_SCHED_GETAFFINITY -Duse_LARGEFILE -fpp -Wp,-w  -I/opt/cray/pe/netcdf/4.4.0/INTEL/15.0/include -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O3 -debug minimal -fp-model source -qopenmp -xsse2            -c -I/lustre/f2/dev/Niki.Zadeh/master_20200210_mom6_ESM4_v1.0.3/20200128/esm4.1_libs_compile/src/FMS/fms2_io/include /lustre/f2/dev/Niki.Zadeh/master_20200210_mom6_ESM4_v1.0.3/20200128/esm4.1_libs_compile/src/FMS/fms2_io/fms_netcdf_domain_io.F90
ifort: error #10236: File not found:  'status:Modified'
ifort: error #10236: File not found:  'blob:b1428455d68c36c7c6039fb3ab7e0b92448562b6'"'
ifort: command line warning #10121: overriding '-xCORE-AVX2' with '-xsse2'
/tmp/ifortpiux4K.i90: catastrophic error: Internal Compiler Error: No filename given on the command-line
compilation aborted for /lustre/f2/dev/Niki.Zadeh/master_20200210_mom6_ESM4_v1.0.3/20200128/esm4.1_libs_compile/src/FMS/fms2_io/fms_netcdf_domain_io.F90 (code 1)
Makefile:89: recipe for target 'fms_netcdf_domain_io.o' failed
```

**To Reproduce**
After a successful build, modify a source file (may be particularly fms2_io/fms_netcdf_domain_io.F90) and then try to recompile.

**Expected behavior**
If  the modifications are valid Fortran code it should recompile successfully.

**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Intel16 and Intel18
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by nikizadehgfdl** [comment]
Chris says this has to do with fre/test. Indeed  I can recompile with fre/bronx-15.
This is a FRE bug. Closing.

**Comment by thomas-robinson** [comment]
For reference, the issue they are working on is NOAA-GFDL/mkmf#33
