### ISSUE TITLE
AMIP4.1 crashes with size of x dimension of input buffer does not match size of x dimension of data or compute domain

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#302]
**Describe the bug**
The AMIP4.1 model is again crashing  (used to run sometime last week):
```
FATAL from PE   153: size of x dimension of input buffer does not match size of x dimension of data or compute domain.

traceback is:

fms_am4.1_compile  0000000003106986  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
fms_am4.1_compile  0000000003571280  fms_io_utils_mod_         145  fms_io_utils.F90
fms_am4.1_compile  0000000003717C79  fms_netcdf_domain         710  fms_netcdf_domain_io.F90
fms_am4.1_compile  000000000371D2A0  fms_netcdf_domain         558  domain_write.inc
fms_am4.1_compile  00000000036133A3  diag_output_mod_m        1247  diag_output.F90
fms_am4.1_compile  000000000319F13C  diag_util_mod_mp_        2565  diag_util.F90
fms_am4.1_compile  000000000319E515  diag_util_mod_mp_        2702  diag_util.F90
fms_am4.1_compile  0000000003182ED3  diag_manager_mod_        3766  diag_manager.F90
fms_am4.1_compile  0000000000416696  coupler_main_IP_c        1995  coupler_main.F90
fms_am4.1_compile  000000000040C20D  MAIN__                   1151  coupler_main.F90
```

I added a print statement in fms_netcdf_domain_io.F90 :
```
  if (.not. buffer_includes_halos .and. data_xsize .ne. xc_size .and. data_ysize &
      .ne. yc_size) then
print*,data_xsize,xd_size,xc_size,data_ysize,yd_size,yc_size
    call error("size of x dimension of input buffer does not match size" &
               //" of x dimension of data or compute domain.")
  endif

```
and got
```
33          38          32           9          14           8
```
So it seems data_xsize=1+xc_size and data_ysize=1+yc_size 
**To Reproduce**
Run AMIP4.1 (or probably AMIP4) experiments with master and the land update 
https://gitlab.gfdl.noaa.gov/fms/lm4P/merge_requests/32

**Expected behavior**
Should run to end

**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Intel16 and 18
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by nikizadehgfdl** [comment]
@menzel-gfdl , didn't you solve a similar issue last week?

**Comment by menzel-gfdl** [comment]
@nikizadehgfdl My first guess would be that some domain position arguments are missing for a few calls to ```diag_axis_init```.  Calls to ```diag_axis_init``` for longitudinal(latitudinal) axes that are on cell edges must include the ```pos=EAST```(```pos=NORTH```) argument.

**Comment by thomas-robinson** [comment]
`pos` changes to `domain_position` in #270 .

**Comment by nikizadehgfdl** [comment]
Thanks @thomas-robinson , I was using dev/master of cubed-sphere rather than master in the xml by mistake. Retrying.
