### ISSUE TITLE
Clean up MPP code

### ISSUE THREAD

**Issue by underwoo** [NOAA-GFDL/FMS#303]
**Is your feature request related to a problem? Please describe.**
The code in MPP has many different paths, depending on the type of build: MPI, non-MPI, ShaMEM.  The ShaMEM option has not been used in many years, and has likely not received required updates that were made in the MPI.  The non-MPI build, at this time, is not possible.  This is due to new _template_ preprocessor macros not placed in the `nocomm` files.  

**Describe the solution you'd like**
MPP needs to be cleaned up to remove unused code, and combine as much code into fewer files as possible.  The final version of MPP in libFMS should contain only build options that will be supported moving forward.

**Describe alternatives you've considered**
None

**Additional context**
This will modify many parts of MPP, and may be easier to deal with in smaller chunks.  This issue can be used an epic issue.

* [ ] #306 - Remove shmem build configuration

**Comment by rem1776** [comment]
Closing since shmem has already been removed. The serial build option can compile and still gets some usage apparently.
