### ISSUE TITLE
diag_manager regional output test

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#304]
**Is your feature request related to a problem? Please describe.**
There is currently no test in FMS to test the diag_manager with regional output.

**Describe the solution you'd like**
[test_diag_manager.F90](https://github.com/NOAA-GFDL/FMS/blob/master/test_fms/diag_manager/test_diag_manager.F90) should get another test added to it that runs with a regional diagnostic output, and a new diag_table needs to be created

**Describe alternatives you've considered**
The test could be written to a new file

**Additional context**

**Comment by thomas-robinson** [comment]
See #281 for an example diag_table entry for regional output.  I think the send_data and register_diag_field calls are the same for global and regional output.  It's just how the internal diag_manager handles the output is different.

**Comment by thomas-robinson** [comment]
@colingladueNOAA have you worked on this at all?

**Comment by colingladueNOAA** [comment]
I have not. I can start if you'd like.

**Comment by thomas-robinson** [comment]
@ngs333 is starting to work on it I think, so it's alright.  I just don't want you guys to both do the same thing.
