### ISSUE TITLE
test_mpp_memuse.F90 error

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#305]
**Describe the bug**
When I run a `make check` with an intel compiler, I encounter the following error:
```
test_mpp_memuse.F90(133): error #6345: Either a PAUSE, STOP or ERROR STOP statement has an invalid argument.   [RETURN_VAL]
  stop return_val
-------^
```

**To Reproduce**
On the lscsky50-d 
```bash
module load intel/2019_up2 impi/2019_up2 netcdf/4.6.1
autoreconf -i
./configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"
make check
```

**Expected behavior**
This test should compile

**System Environment**
Describe the system environment, include:
- OS: 
- Compiler(s): intel19
- MPI type, and version: impi
- netCDF Version: 4.6.1
- Configure options: FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"

**Additional context**
The git hash I'm using is 7788b781ac4e7fecf0d6cebc239206242305ac36

**Comment by thomas-robinson** [comment]
@uramirez8707 can you reproduce this?  If you do, I will add it to the 2020.01 project.

**Comment by uramirez8707** [comment]
@thomas-robinson yep, make check fails on skylake now. I also tried it with intel20 and get the same error

**Comment by thomas-robinson** [comment]
How is this passing make distcheck?

**Comment by underwoo** [comment]
Discovered the problem.  I didn't realize the Fortran `STOP` intrinsic only accepted constant integers or character strings.  GNU Fortran appears to not honor that restriction.  I'll have an update for this.

**Comment by thomas-robinson** [comment]
#310 worked for me when I tried it.
