### ISSUE TITLE
libsat_vapor_pres_k.la and libsat_vapor_pres.la missing from libFMS.la?

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/FMS#316]
**Describe the bug**
I think the libraries `libsat_vapor_pres_k.la` and `libsat_vapor_pres.la` are not included in `libFMS.la.`  When I try to build an executable and link in `libFMS.a`, I get undefined references if I
try to call routines from those modules.

**To Reproduce**
Build an executable, link in `libFMS.a`, and try to call routines from those modules.

**Expected behavior**
Linking in `libFMS.a` should provide the necessary routines.

**System Environment**
- OS: Linux 3.10.0-1062.9.1.el7.x86_64
- Compiler: Intel 18.0.3

**Comment by underwoo** [comment]
This appears to be correct.  We will get this corrected.
