### ISSUE TITLE
MOM6+SIS2+diag_manager w/new IO sometimes crashes when writing scalars

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#319]
**Describe the bug**
The [2 first calls](https://github.com/wrongkindofdoctor/MOM6/blob/7e2ccc1dd837e4f82ff22d4cd38d3bc8bde87930/src/diagnostics/MOM_sum_output.F90#L887) to to the fms2_io write_data interface by MOM6_sum_output:write_energy is routed to [compress_write_0d](https://github.com/NOAA-GFDL/FMS/blob/e1c0d9d01d844938adc0d18afa09532f336bcdfe/fms2_io/include/compressed_write.inc#L5). Randomly, the experiment will crash after hitting the  the final time-step of a MOM6-SIS2 experiment because the [compressed dimension index for one of the scalar variables does not equal 0](https://github.com/NOAA-GFDL/FMS/blob/e1c0d9d01d844938adc0d18afa09532f336bcdfe/fms2_io/include/compressed_write.inc#L29). 
**To Reproduce**
1) compile FMS/master, FMScoupler/master, ice_null, atmos_null, icebergs, ice_param,  [SIS2/user/jml/add_new_fms_io](https://github.com/wrongkindofdoctor/SIS2/tree/user/jml/add_new_fms_io), and [MOM6/user/jml/operation_fms2_the_reckoning ](https://github.com/wrongkindofdoctor/MOM6/tree/user/jml/operation_fms2_the_reckoning) with gnu v7.3.0 using the MOM6 [gitlab-ci](https://github.com/wrongkindofdoctor/gaea_ci) Makefile on gaea
2) run the symmetric-dynamic executable in on Gaea in debug with gnu 7.3 or repro with intel 19 with 60 pes 
**Expected behavior**
The simulation completes successfully after 1 model day.
**System Environment**
Describe the system environment, include:
- OS: SUSE Linux 4.4.143-94.47.1.16060.2.PTF.1107299-default
- Compiler(s): gnu 7.3, intel/19.0.5.281

- MPI type, and version: cray-mpich/7.4.0
- netCDF Version: 4.4.0
- Configure options: -Duse_libMPI -Duse_netCDF -DSPMD -Duse_AM3_physics -D_USE_LEGACY_LAND_

**Additional context**
write_energy writes to the ocean.stats.nc file. The variables that trigger the error are either `Ntrunc` or `En`, which are appended along the `Time` dimension. The file is generated by a call to [create_file](https://github.com/wrongkindofdoctor/MOM6/blob/7e2ccc1dd837e4f82ff22d4cd38d3bc8bde87930/src/framework/MOM_io.F90#L225), which never registers a compressed dimension to the netCDF file object.

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor Do you know what the value equals?  Is the variable being registered with multiple axes?

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor do you have more explicit instructions for compiling and running?

**Comment by wrongkindofdoctor** [comment]
This can be resolved by leaving file open while sequential calls are made to write_data. Note that the user has to ensure that the file object does not go out of scope between calls to write data. See an example of the workaround implemented in the MOM_io write_field interfaces is [here](https://github.com/wrongkindofdoctor/MOM6/blob/018c062255d23104c45f5584b31a150d5af590b4/src/framework/MOM_io.F90#L1175).
