### ISSUE TITLE
mpp_do_global_field does not appear to check for masked procs

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/FMS#32]
I'm surprised that this hasn't come up before, maybe there's something unusual about my setup. I'm doing processor masking on a 1 degree config and getting segfaults within FMS on this line of code: 

https://github.com/NOAA-GFDL/FMS/blob/master/mpp/include/mpp_do_global_field.h#L146

There is no check in this code to see whether from_pe is NULL_PE (-3), i.e. it may have been masked when setting up the domains.

**Comment by underwoo** [comment]
@nicjhan I see the mom-ocean/MOM5#183 issue was closed.  Should this issue also be closed?

**Comment by aidanheerdegen** [comment]
Only if you patched `cpp_do_global_field.h` with @nicjhan's commit I guess?

https://github.com/mom-ocean/MOM5/commit/4745c52aeb8bfb702635113d4e724d12bf9c67bd

We (Aus contingent that seem to be de-factor supporting MOM5 these days) are planning to move to a model where we use FMS directly (either CMake or `git submodule`) so hopefully we'll be firing off pull requests for stuff like this.

**Comment by underwoo** [comment]
We have taken the patch you mentioned (mom-ocean/MOM5@4745c52) into our internal repository for review and testing.  We are targeting this to be applied in our next release (due out soon).
