### ISSUE TITLE
Make Check fails in skylake box 

### ISSUE THREAD

**Issue by colingladueNOAA** [NOAA-GFDL/FMS#322]
**Describe the bug**
Make check fails in test_mpp_domains2 with the following crash:

```
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to     131072.

FATAL from PE     1: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage

Abort(1) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

FATAL from PE     0: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage

FATAL from PE     0: fms_affinity_set: test_mpp_domains cpu_set size > allocated storage
```

**To Reproduce**
Fails this way specifically while testing pull request #310 in skylake with intel. 
With shell commands:
```
autoreconf -i 
 module load intel impi netcdf 
 ./configure FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc" 
 make check
```

**Expected behavior**
Make check should pass.

**System Environment**
Describe the system environment, include:
- OS: [Skylake Box
- Compiler(s): Intel2020
- MPI type, and version: impi2020
- netCDF Version: netcdf4.6.1
- Configure options:  FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="mpiifort" CC="mpiicc"

**Additional context**
Reverting Pull #249 fixes the issue.

**Comment by colingladueNOAA** [comment]
If PR #310 and PR #311 are run together, the make check does pass, but largely because the computer is told to skip the previously failing test.

**Comment by underwoo** [comment]
@colingladueNOAA, are you still working on this?

**Comment by colingladueNOAA** [comment]
@underwoo, I am currently working on fixing all of the skipped unit tests in the FMS make check, and test_mpp_domains2.sh is one of them.

**Comment by underwoo** [comment]
Just wanted to know so I could move this from the 2020.01 project to 2020.02.
