### ISSUE TITLE
Problem writing sub-hour forecast outputs.

### ISSUE THREAD

**Issue by nickcctong** [NOAA-GFDL/FMS#325]
I've been trying to output forecast fields in 15 or 30 minute intervals, but neither of them worked.
What I did was specifying the header part of the diag_table as:
"fv3_history",            30,  "minutes",    1, "hours", "time"
"fv3_history2d",          30,  "minutes",    1, "hours", "time"  
I requested a total integration length of 5 hours, but the model always died at the 7200 sec with error:
**FATAL from PE     0: diag_manager_mod::send_data_3d: module/output_field gfs_dyn/U is skipped one time level in output data**
Can somebody help me with idea about the possible cause of this problem?
Hourly output works just fine, but not these sub-hourly outputs.
Many thanks!

**Comment by thomas-robinson** [comment]
@nickcctong did you find a solution?  If yes, what was the problem?

**Comment by nickcctong** [comment]
@thomas-robinson Unfortunately, no. I deleted the issue because I figured it is actually the EMC version of FV3 that runs into this problem. So I reopened an issue at the NCAR/NEMSfv3gfs repository.

**Comment by thomas-robinson** [comment]
@nickcctong Alright then.  The first thing I would check is if your time step actually lands on the interval you're trying to write to.  Good luck.  If it's related to the diag_manager at all, let us know.
