### ISSUE TITLE
Method to check if an axis is registered to a netCDF file object

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#327]
**Is your feature request related to a problem? Please describe.**
There is no way for the user to check whether an axis is registered to a netcdf file object in the new fms IO code. Checking for axis registration is necessary for cases when domain-decomposed variables are written to the same file without opening and closing the file in between writes, as the MOM6 code does [here](https://github.com/NOAA-GFDL/MOM6/blob/75772280614bc4ff5ef53a0e1e35382b0e3d1422/src/initialization/MOM_shared_initialization.F90#L1275) and [here](https://github.com/NOAA-GFDL/MOM6/blob/75772280614bc4ff5ef53a0e1e35382b0e3d1422/src/diagnostics/MOM_sum_output.F90#L885) via wrappers to the write_data routines.

**Describe the solution you'd like**
I have written a function [is_dimension_registered ](https://github.com/wrongkindofdoctor/FMS/blob/34acd1603507e36f19f594944a78f672175c63a4/fms2_io/fms_netcdf_domain_io.F90#L273) in fms_netcdf_domain_io.F90 that uses the same procedure in [add_domain_attribute](https://github.com/wrongkindofdoctor/FMS/blob/34acd1603507e36f19f594944a78f672175c63a4/fms2_io/fms_netcdf_domain_io.F90#L462) to call get_domain_decomposed_dimension_index on the the dimension passed to the function. It returns _.true._ if the result is /= to the `dimension_not_found` parameter for the x-dimension or y-dimension, and _.false._ otherwise.

Here is an example of the implementation in MOM_io after the domain-decomposed file object `fileobj_write_field_dd` has been opened for writing :
`num_dims` is the number of dimensions associated with the variable, `dim_names` are the dimension names, `dim_lengths` are the lengths of each dimension, and `MOM_register_diagnostic_axis` wraps the fms io `register_axis` routine.
```
! register the horizontal diagnostic axes associated with the variable
  do i=1,num_dims
    if (.not.(is_dimension_registered(fileobj_write_field_dd, trim(dim_names(i))))) &
      call MOM_register_diagnostic_axis(fileobj_write_field_dd, trim(dim_names(i)), dim_lengths(i))
  enddo
```

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor are you running this through the diag_manager?

**Comment by wrongkindofdoctor** [comment]
No. It's currently only needed in MOM_io.
