### ISSUE TITLE
Error in buffer_pos size after MOM calls mpp_do_group_update

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#330]
**Describe the bug**
A call to mpp_do_group_update in a coupled ice-ocean run with FMS master produces the following error 
`set_group_update: update_buffer_pos .NE. unpack_buffer_pos`
The message originates in [mpp_domains_util.h:set_group_update](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_util.inc#L1929)

**To Reproduce**
Compile[ MOM6+new IO](https://github.com/wrongkindofdoctor/MOM6/tree/user/jml/operation_fms2_the_reckoning) , FMS master , FMScoupler, [SIS2+new IO](https://github.com/wrongkindofdoctor/SIS2/tree/user/jml/add_new_fms_io), with gnu 7.3.2 or intel 18 in debug (no threads), then run ice_ocean_SIS2 [Baltic experiment](https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ice_ocean_SIS2/Baltic) with 60 pes on gaea

**Expected behavior**
5 day test simulation completes successfully

**System Environment**
Describe the system environment, include:
- OS: SUSE Linux Enterprise  4.4.103-6.38_4.0.95-cray_ari_c
- Compiler(s): gnu 7.3.0, intel/ 8.0.6.288
- MPI type, and version: Intel MPICH Update 5 Build 20190404
- netCDF Version: 4.4.0
- Configure options: -Duse_libMPI -Duse_netCDF -DSPMD -Duse_AM3_physics -D_USE_LEGACY_LAND

**Additional context**
MOM6 calls MPP directly via wrapper routines in MOM_domains.F90. The call to mpp_do_group_update is wrapped in the MOM [do_group_pass routine](https://github.com/wrongkindofdoctor/MOM6/blob/144f713bb259aeeef594845a319106883822ed80/src/framework/MOM_domains.F90#L1090.)

The experiment is run as part of the MOM gitlab CI test framework, so I will provide further instructions for replication if needed.

The stack trace for the Intel 18 debug run is here:
```
MOM6               0000000005CBA91E  Unknown               Unknown  Unknown
MOM6               0000000005733D80  Unknown               Unknown  Unknown
MOM6               0000000005C95D0B  Unknown               Unknown  Unknown
MOM6               0000000005D9457A  Unknown               Unknown  Unknown
MOM6               0000000005AF19E2  Unknown               Unknown  Unknown
MOM6               0000000005AD51E9  Unknown               Unknown  Unknown
MOM6               0000000005AD6415  Unknown               Unknown  Unknown
MOM6               0000000003E5819D  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
MOM6               0000000003FC9218  mpp_domains_mod_m        1929  mpp_domains_util.inc
MOM6               00000000046D356B  mpp_domains_mod_m         471  mpp_group_update.h
MOM6               00000000033D19A4  mom_domains_mp_do        1104  MOM_domains.F90
MOM6               00000000026F52CB  mom_dynamics_spli        1226 MOM_dynamics_split_RK2.F90
MOM6               00000000013D3D31  mom_mp_initialize        2326  MOM.F90
MOM6               0000000000759418  ocean_model_mod_m         271  ocean_model_MOM.F90
MOM6               00000000022E19B8  coupler_main_IP_c        1795  coupler_main.F90
MOM6               00000000022CCE9E  MAIN__                    614  coupler_main.F90
MOM6               000000000040A1BE  Unknown               Unknown  Unknown
MOM6               0000000005D8E339  Unknown               Unknown  Unknown
MOM6               000000000040A0A9  Unknown               Unknown  Unknown

``` 
Any insight on this problem @menzel-gfdl, @bensor?

**Comment by menzel-gfdl** [comment]
@wrongkindofdoctor @bensonr 

Looking in the debugger, in the `set_group_update` subroutine in `mpp_domains_mod` the variables
`update_s%recv(m)%msgsize(n)`, `update_x%recv(m)%msgsize(n)`, `update_y%recv(m)%msgsize(n)` sometimes contain negative values.  The `update_buffer_pos` variable depends on these values through calls to
```
get_mesgsize(update_s%recv(m), recv_s)
get_mesgsize(update_x%recv(m), recv_x)
get_mesgsize(update_y%recv(m), recv_y)
```
, but is calculated inside a `if (msgsize .gt. 0)` conditional, and thus ignores the negative values.  The variable `unpack_buffer_pos` also depends on these msgsize values, but is not inside an analogous `if (msgsize .gt. 0)` conditional, so it includes the negative values, leading to the `FATAL` error noted above.

I'm not sure why negative message sizes (if the variable name is accurate) are allowed at all.  Maybe we should add an error check when these msgsize variables are set?

**Comment by wrongkindofdoctor** [comment]
@menzel-gfdl, @bensonr 
The problem does not appear to originate from the `group` structure passed to `mpp_do_group_update`. Instead, the `msgsize` attributes of the `update_y` structures is initially a negative integer on some of the  pes. `update_y` is a pointer initialized to NULL(), and points to the result from[ `search_update_overlap(domain, group%whalo_v, group%ehalo_v, group%shalo_v, group%nhalo_v, position_y)`](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_util.inc#L891), which calls [`set_overlaps`](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_define.inc#L4934), which calls[ `add_update_overlap`](https://github.com/NOAA-GFDL/FMS/blob/b68de5382a5ce631ddd6167de8d85f7c9ae54351/mpp/include/mpp_domains_define.inc#L7920) where `msgsize` is **finally** set:
```
do n = count_out+1, count
     overlap_out%msgsize(n) = (overlap_out%ie(n)-overlap_out%is(n)+1)*(overlap_out%je(n)-overlap_out%js(n)+1)
  enddo
```
A sample from a pe with an overlap%mesgsize of -3 occurs because is=7, ie=5, js=1; msgsize=(5-7+1)x(3-1+1)= -3x1
So, the next questions are:
* why is ie < is?
* is it valid to have ie<is, je<js? If so, then we need to implement checks for negative values in the `set_group_update` routine.

**Comment by wrongkindofdoctor** [comment]
Update: the same behavior occurs in this experiment compiled with FMS/master but without any of the new IO implemented in MOM or SIS2.

**Comment by uramirez8707** [comment]
@wrongkindofdoctor Do you know if this behavior is present in FMS/xanadu? (or any of the previous releases)

**Comment by wrongkindofdoctor** [comment]
I'm not sure, but I'm going to test the last 2 releases today.

**Comment by wrongkindofdoctor** [comment]
As Niki pointed out [here](https://github.com/NOAA-GFDL/MOM6-examples/issues/305#issuecomment-600191068), this issue occurs with a larger amount of pes than the small physical domain can handle. Using -n <= 8 causes the run to complete successfully.
