### ISSUE TITLE
Record tag hashes in changelog

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#336]
**Is your feature request related to a problem? Please describe.**
We will delete the alpha and beta tags from the repository at each release.  The hash for each tag should be recorded for reference.

**Describe the solution you'd like**
Record the hash for each tag used for testing in the CHANGELOG

**Describe alternatives you've considered**

**Additional context**

**Comment by underwoo** [comment]
@colingladueNOAA @thomas-robinson I think in the future, it would be better to create a GitHub wiki page that records this information.  Knowing this information, in my opinion, is really for short term need (on the order for no more than a year or so).  

The wiki, like the repository is a git repository.  But unlike the repository, doesn't carry with it the overhead.

**Comment by thomas-robinson** [comment]
@colingladueNOAA don't forget to do this

**Comment by colingladueNOAA** [comment]
Could anyone direct me to the git repository for the wiki so I can create this?

**Comment by thomas-robinson** [comment]
@rem1776 Are you doing this now?  Can we close this issue?

**Comment by rem1776** [comment]
@thomas-robinson yeah I always do this I'll close it
