### ISSUE TITLE
fms2io: Opening a file that is already open leaves the fileobj rootless 

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#340]
**Describe the bug**
When opening a file, `fileobj%is_root` is initialize as false: https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/fms2_io/netcdf_io.F90#L410

`fileobj%is_root` is then set later in the subroutine: https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/fms2_io/netcdf_io.F90#L447

However, if you call `open_file` on a file that is already opened: 
It is going to first set `fileobj%is_root` to false and then enter this if block: 
```F90
  if (allocated(fileobj%is_open)) then
    if (fileobj%is_open) then
      success = .true.
      return
    endif
  endif 
```
and exit the function, leaving it rootless, which will cause the data to be not read at all. 

**To Reproduce**
I created a program that opened a file, read data from the file, opens the file again, read the same data again and the data was not read correctly the second time. 

**Expected behavior**
The file_obj should have a root that will do the reading and broadcast it to the rest of the Pes
The line `fileobj%is_root = .false. ` should be after the if block or even removed. 

**System Environment**
Describe the system environment, include:
Any systems

**Additional context**
N/A

**Comment by uramirez8707** [comment]
@menzel-gfdl

**Comment by thomas-robinson** [comment]
You shouldn't be opening a file that's already open. That would cause some crazy behavior.

There are a few routines/functions that check if a file is opened before opening.  Here is the implementation in the (diag_manager)[https://github.com/NOAA-GFDL/FMS/blob/master/diag_manager/diag_output.F90#L204].  If checks if the file is open, and if it isn't opened, then the file is opened.

**Comment by uramirez8707** [comment]
ok, but `open_file` allows the user to do this in 
```F90
  if (allocated(fileobj%is_open)) then
    if (fileobj%is_open) then
      success = .true.
      return
    endif
  endif 
```

Also, the functions that checks if the file is open do the same thing as that ^

**Comment by thomas-robinson** [comment]
The checks should be run when opening a file anyway.  You shouldn't just be running open_file without checking if it's opened first.

I don't see any problem with moving https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/fms2_io/netcdf_io.F90#L410 Down lower to right above where the root PEs are set up https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/fms2_io/netcdf_io.F90#L447

**Comment by wrongkindofdoctor** [comment]
@thomas-robinson is correct: I implement this check as:

`if (.not.(check_if_open(fileObj))) call open_file(fileobj,...)`

**Comment by menzel-gfdl** [comment]
@thomas-robinson I disagree with "You shouldn't just be running open_file without checking if it's opened first."  It doesn't make much sense to me to check if the file is open if I already know that it isn't.  I agree with @uramirez8707 that there is an issue with how the code is currently written.  If you do not want to allow multiple calls to` open_file` on the same file object, then change the `open_file` routine to error if the file is already open instead of returning `.true.`.  Either way I think the first line that sets 'fileobj%is_root = .false.` is not necessary.
