### ISSUE TITLE
Failure in compiling FMS with GNU compiler and autotools on Gaea

### ISSUE THREAD

**Issue by GFDL-Eric** [NOAA-GFDL/FMS#345]
**Describe the bug**
The configure script fails when checking to see if "CC" can compile a C program. The error is `configure: error: C compiler cannot create executable`. 

**To Reproduce**
I've tried to replicate the environment created by FRE to the best of my ability in terms of replicating env.defaults.gnu and gnu.mk. This is the script I run:

```module unload cray-netcdf cray-hdf5 fre
module unload PrgEnv-pgi PrgEnv-intel PrgEnv-gnu PrgEnv-cray
module unload intel
module load PrgEnv-gnu/6.0.3
module swap gcc/7.3.0 (I've also tried with the default gcc)
module load fre/bronx-16
module load cray-hdf5/1.8.16
setenv KMP_STACKSIZE 512m
setenv NC_BLKSZ 1M
setenv F_UFMTENDIAN big
setenv MAIN_PROGRAM coupler/coupler_main.o
setenv XTPE_LINK_TYPE dynamic
setenv CRAYPE_LINK_TYPE dynamic
setenv FC ftn
setenv FCFLAGS "-O2 -fno-expensive-optimizations `nf-config --fflags` -fcray-pointer -fdefault-real-8 -fdefault-double-8 -Waliasing -ffree-line-length-none -fno-range-check -msse2 -fopenmp -fPIC"
setenv CC cc
setenv CPPFLAGS "-D__IFC -DINTERNAL_FILE_NML -Duse_libMPI -Duse_netCDF -Duse_LARGEFILE `nc-config --cflags`"
setenv CFLAGS "-O2 -fopenmp"
setenv LDFLAGS "-no-install -lnetcdff -lnetcdf -lhdf5_hl -lhdf5"
```

**Expected behavior**
At a minimum, I would expect the C compiler check to pass. Note that on the Skylake Box with similar settings (not using the LINK_TYPE setenvs, and the compiler executables are mpif90 and mpicc), I'm able to run through my unit test without failures.

**System Environment**
Describe the system environment, include:
- OS: Gaea's standard OS
- Compiler(s): GNU 7.3.0 or 5.2.0
- MPI: loaded by PrgEnv-gnu (I think)
- netCDF Version: As per script and fre/bronx-16
- Configure options: See above script

**Additional context**
I was testing my own fork, but this seems to be an issue with NOAA-GFDL master as well. Here's hoping I'm just forgetting something simple, since I have a runtime error with Intel18 on Gaea (I'll save that for a different issue!)

**Comment by wrongkindofdoctor** [comment]
pulling @uramirez8707 into the conversation for his autotools wisdom. I'll see if I can replicate the problem since I'm testing stuff on Gaea.

**Comment by thomas-robinson** [comment]
@GFDL-Eric do you have mpich loaded?

**Comment by GFDL-Eric** [comment]
@thomas-robinson cray-mpich/7.4.0 is loaded from the `module use -a ~fms/local/modulefile` line in my .cshrc... should I not have that line in there?

**Comment by GFDL-Eric** [comment]
I took out `-no-install` in the LDFLAGS and everything is golden! Thanks @uramirez8707 @wrongkindofdoctor @thomas-robinson !!
