### ISSUE TITLE
fsm2io: compute_global_checksum.inc doesn't support `kind=real32`

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#347]
**Describe the bug**
@laurenchilutti  reported the following error when implementing the new io into GFDL_atmos_cube_sphere master: 

`
FATAL from PE     7: unsupported type
`

The fatal happens in `compute_global_checksum.inc`. 
The variable that it is trying to calculate the checksum for is a `kind=real32`. 
The part of the code that handles this is type is commented out: https://github.com/NOAA-GFDL/FMS/blob/8f3d7ab3184495fc0bfac7fc1e9a1a951c98c144/fms2_io/include/compute_global_checksum.inc#L90-L98

Uncommenting this lines, gets us pass this issue ...

**To Reproduce**
Run the GFDL_atmos_cube_sphere test with [atmos_cube_sphere with new io](https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/tree/fms2_io_update), [FMS with nesting changes ](https://github.com/bensonr/FMS/tree/zhi_nest_merge)+ #342 

**Expected behavior**
The code should be able to calculate checksums for floats. 

**System Environment**
Describe the system environment, include:
This happens in every system. 

**Additional context**
N/A

**Comment by thomas-robinson** [comment]
@laurenchilutti is this required for the nesting updates #227

**Comment by uramirez8707** [comment]
@thomas-robinson no this is just for you are using the new_io to write `kind=real32` 
#227 without the new io changes to cube_sphere works

**Comment by laurenchilutti** [comment]
@thomas-robinson #227 worked fine before I implemented fms2 io.  This issue came up when I made changes to GFDL_atmos_cubed_sphere to implement fms2 io. 

I wouldn't say that this is "required" for the nesting updates in #227.
