### ISSUE TITLE
Gaea autotools compile on Gaea fails on configure when checking for cray pointers 

### ISSUE THREAD

**Issue by GFDL-Eric** [NOAA-GFDL/FMS#353]
**Describe the bug**
When attempting to compile FMS on Gaea with autotools, configure fails when the check for cray pointers is attempted. 

**To Reproduce**
Clone FMS, set up the environment to compile with Cray, run autoreconf and then configure.

**Expected behavior**
I sure do expect the Cray compiler to support Cray pointers. I've noticed a couple odd things in the test that's performed, and would like to get a sense if some of the proposed changes would conflict with the original design.

**System Environment**
Describe the system environment, include:
- OS: Gaea 9-14 (NOT Gaea16, which has its own autotools issue presently)
- Compiler(s): Cray 8.6.5, though GNU Fortran was tested for comparison purposes
- MPI type, and version: cray-mpich/7.7.3
- netCDF Version: For both C and Fortran
- Configure options: Here is my script to set the environment:

module unload cray-netcdf cray-hdf5 cray-mpich fre
module unload PrgEnv-pgi PrgEnv-intel PrgEnv-gnu PrgEnv-cray
module unload intel gcc cce
module load PrgEnv-cray/6.0.3
module swap craype/2.5.13
module swap cce/8.6.5
module load fre/test
module load cray-hdf5
module load cray-mpich/7.7.3
setenv KMP_STACKSIZE 512m
setenv NC_BLKSZ 1M
setenv F_UFMTENDIAN big
setenv MAIN_PROGRAM coupler/coupler_main.o
setenv FC ftn
setenv FCFLAGS "-O3 -O fp2 -G2 `nf-config --fflags` -I/opt/cray/pe/mpt/7.7.11/gni/mpich-cray/8.6/include -s real64 -s integer32 -h byteswapio -h nosecond_underscore -e m -h keepfiles -e0 -ez -N1023 -fPIC"
setenv CC cc
setenv CPPFLAGS "-DINTERNAL_FILE_NML -Duse_libMPI -Duse_netCDF -Duse_LARGEFILE `nc-config --cflags` -I/opt/cray/pe/mpt/7.7.11/gni/mpich-cray/8.6/include"
setenv CFLAGS "-O2 -I/opt/cray/pe/mpt/7.7.11/gni/mpich-cray/8.6/include"
setenv LDFLAGS "-lnetcdff -lnetcdf -lhdf5_hl -lhdf5"

**Additional context**
I've tried to dive a bit deeper into the "test" program that determines whether or not the compiler can handle Cray pointers. The actual test is run here: https://github.com/NOAA-GFDL/FMS/blob/bbc6f8d33cfb75a411bbcd3f8423fa74b8b7cdfd/m4/gx_fortran_options.m4#L200-L204

A few points:

- There is no implicit none statement, is this by design?
- There is a mismatch between the variables `iarri` and `iarr`
- Finally, according to my albeit limited reading on Cray pointers, and the error that came up when I ran this test program outside the configure environment, setting `integer(kind=8) :: ipt` does not allow ipt to be a pointer because it has already been defined as an integer (again, this was the Cray compiler's complaint).

Given the verbiage in the lines preceding the test, it seems like an "unknown" if a specific flag must be passed to the Cray compiler in order to enable Cray pointers. I was not able to find anything in reference to a flag being required, so the test within configure should work without any additional "-fcray-pointer" type clauses in FCFLAGS.

**Comment by GFDL-Eric** [comment]
@bensonr @underwoo any thoughts on which direction to take?

**Comment by underwoo** [comment]
I'm looking at this now.  I believe I have a solution.  I'll let you know when my tests are complete.

**Comment by underwoo** [comment]
I have a fix for the Cray compiler check for the cray pointer.  However, due to the Cray compiler naming all modulefiles with capital letters: e.g. `MPP_DOMAINS_MOD.mod`, the autotools Makefile rebuilds all source since it cannot find a compiled module file.

I'll get a push with the initial fix for the cray pointer with CCE.
