### ISSUE TITLE
master fails make check in fms2_io with "test_atmosphere_io.sh - missing test plan"

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#356]
When I check out current master and build, make check fails.

I am building like this:

`FC=mpifort CC=mpicc CPPFLAGS="-I/usr/local/netcdf-c-4.7.4-development_hdf5-1.10.6_mpich/include -I/usr/local/netcdf-fortran-4.5.3-development_netcdf-c-4.7.4_mpich/include" FCFLAGS="-I/usr/local/netcdf-c-4.7.4-development_hdf5-1.10.6_mpich/include -I/usr/local/netcdf-fortran-4.5.3-development_netcdf-c-4.7.4_mpich/include" LDFLAGS="-L/usr/local/netcdf-c-4.7.4-development_hdf5-1.10.6_mpich/lib -L/usr/local/netcdf-fortran-4.5.3-development_netcdf-c-4.7.4_mpich/lib" ./configure`

I have not yet done any investigation - I wanted to first see if this was an expected problem.

**Comment by wrongkindofdoctor** [comment]
This test is expected to break for now, but I'm not sure about the error message. I'll get a 'skip' in there for the test.

**Comment by colingladueNOAA** [comment]
I am having a similar problem.

This seems to be the only testing directory with bats files and the only that doesn't use an input_base.nml, which may contribute to my error upon make distcheck: 
make[3]: stat: input.nml: Too many levels of symbolic links
make[3]: *** No rule to make target `input.nml', needed by `distdir'.  Stop.

It appears to me that PR #280  does a good job remedying those concerns. 

@wrongkindofdoctor  @menzel-gfdl

**Comment by menzel-gfdl** [comment]
Is there any reason not to accept #280?

**Comment by edwardhartnett** [comment]
@wrongkindofdoctor perhaps you are getting a different output because you have bats installed and I don't?  So for you the test skips, and for me it fails. ;-)
