### ISSUE TITLE
Remove use of BATS in fms_io2 testing

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#358]
Some time ago, with the approval of @underwoo , I removed the use of the BATS utility in FMS testing. This was done because BATS is an unusual dependency, which caused a lot of configure problems for very little benefit. See #221 

However, I notice bats is still being used in the fms_io2 directory.

Shall I remove bats from there as well?

**Comment by colingladueNOAA** [comment]
I believe @wrongkindofdoctor is working on this in PR #280 .
