### ISSUE TITLE
fms2_io files missing license header

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/FMS#359]
**Describe the bug**
Newly created fms2_io files are missing the LGPL  license header block.

**To Reproduce**
N/A

**Expected behavior**
FMS LGPL header block included in all files.

**System Environment**
N/A

**Additional context**
Please check all files to ensure the license header block is present.

**Comment by colingladueNOAA** [comment]
Would you like every file in the FMS/test_fms/fms2_io/ directory to have the header, or only certain file extensions?

**Comment by bensonr** [comment]
Every source file (.h, .inc, .F90, etc) should have the header.  I think the rest of the repository is clean, but please double-check.

**Comment by edwardhartnett** [comment]
@bensonr should this apply to the Makefile.am files? If so I can add these while doing some other changes...

**Comment by bensonr** [comment]
Sorry for the late reply, I was waiting for one of the maintainers to
return from leave to provide consensus.  We'd like all files to have a
license header are in the process of finding and fixing those that
currently don't have one.

>

**Comment by edwardhartnett** [comment]
OK, sounds good. We all have to please the lawyers in our lives...
