### ISSUE TITLE
FMS2 send_data crashes when ocean has mask_table, NetCDF: Index exceeds dimension bound

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#362]
**Describe the bug**
When we use a mask_table for the ocean the model crashes like this:
```
FATAL from PE  1152: NetCDF: Index exceeds dimension bound
Rank 1152 [Thu Mar 26 02:34:39 2020] [c5-0c1s12n0] application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1152
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
fms_esm4.1_sis2_c  000000000364C3D6  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
fms_esm4.1_sis2_c  00000000031D8020  fms_io_utils_mod_         145  fms_io_utils.F90
fms_esm4.1_sis2_c  000000000327CA6B  netcdf_io_mod_mp_         238  netcdf_io.F90
fms_esm4.1_sis2_c  00000000030B2E9A  fms_netcdf_domain         672  domain_write.inc
fms_esm4.1_sis2_c  00000000036748FF  diag_output_mod_m        1341  diag_output.F90
fms_esm4.1_sis2_c  000000000322F4F8  diag_util_mod_mp_        2629  diag_util.F90
fms_esm4.1_sis2_c  0000000003099090  diag_manager_mod_        3518  diag_manager.F90
fms_esm4.1_sis2_c  00000000030873B3  diag_manager_mod_        2008  diag_manager.F90
fms_esm4.1_sis2_c  000000000307742D  diag_manager_mod_        1550  diag_manager.F90
fms_esm4.1_sis2_c  000000000238480A  mom_diag_mediator         901  MOM_diag_mediator.F90
fms_esm4.1_sis2_c  000000000255E5C1  mom_diagnostics_m        1141  MOM_diagnostics.F90
fms_esm4.1_sis2_c  0000000002221B0B  mom_mp_step_mom_          836  MOM.F90
fms_esm4.1_sis2_c  000000000219BB7F  ocean_model_mod_m         556  ocean_model_MOM.F90
```

**To Reproduce**
Run either ESM4 or OMIP experiment that uses a mask_table for the ocean.

**Expected behavior**
Here are the stdouts for the same ocean layout with and without a mask_table

crash with mask_table
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3uu_1/ESM4_piControl_D/ncrc3.intel18-prod-openmp/stdout/run/ESM4_piControl_D_1x0m2d_216x4a_442x1o.o202928844 
```
Expected without mask_table
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3uu_1/ESM4_piControl_D/ncrc3.intel18-prod-openmp/stdout/run/ESM4_piControl_D_1x0m2d_216x4a_512x1o.o202928845
```
**System Environment**
Describe the system environment, include:
- OS: c3 and c4 with fre/test
- Compiler(s): Intel18
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

There is a similar issue with ocean-ice runs (which are smaller and easier to debug):
```
/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o.o202928898

/lustre/f2/scratch/Niki.Zadeh/FMS2020.01_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel18-prod/stdout/run/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_512x1o.o202928897
```

**Comment by thomas-robinson** [comment]
@nikizadehgfdl are you looking into the details of this, or do you need me/ @ngs333 / @menzel-gfdl to look into this as well?

**Comment by nikizadehgfdl** [comment]
@uramirez8707 offered and is working on this issue.

**Comment by uramirez8707** [comment]
@thomas-robinson @nikizadehgfdl @menzel-gfdl 
After getting through the error, I can reproduce the Xanadu restarts, but I am getting differences in the **some** of the history files. 

For example, for `19480101.ocean_Agulhas_section.nc`, I get these differences using nccmp (it only displays the first difference for each variable)
```
DIFFER : VARIABLE : volcello : POSITION : [0,0,16,0] : VALUES : 2.17554e+09 <> 1e+20
DIFFER : VARIABLE : thetao : POSITION : [0,0,16,0] : VALUES : 0.459173 <> 1e+20
DIFFER : VARIABLE : so : POSITION : [0,0,16,0] : VALUES : 33.6821 <> 1e+20
DIFFER : VARIABLE : umo : POSITION : [0,0,16,0] : VALUES : 2.23415e+06 <> 1e+20
DIFFER : VARIABLE : uo : POSITION : [0,0,16,0] : VALUES : 0.0220705 <> 1e+20
```
The first value is the xanadu answers, the second is the answer from current FMS, "1e+20" is the FillValue. Data at that point is just not written. It is different in both cases (with and without mask table)

I think @thomas-robinson and I were seeing something similar in AM4 with the `c*_am4p0_cmip6Diag` experiment (?)

**Comment by thomas-robinson** [comment]
Is this the only point that is giving an error?  I'm curious if this happens for all points or just a few points.  How many vertical levels are there?  (0,0,16,0) seems like it's consistent across all of the variables.  Are they all using the same axes?  Is it all of the points on the edge of the mask?  Can you plot the data and see how different it looks?

**Comment by nikizadehgfdl** [comment]
These are the notorious regional (ocean choke points) diagnostics that Tom worked on before.

**Comment by uramirez8707** [comment]
> Is this the only point that is giving an error? I'm curious if this happens for all points or just a few points. 

This is not for all points, but (0,0,16,0) is not the only point. In fact, it is different for (:, :, 16:129,:) Note that the indices are outputted this way: `volcello(time, z_l, yh_sub01, xh_sub01)`
  
>How many vertical levels are there? (0,0,16,0) seems like it's consistent across all of the variables. 

```
        xh_sub01 = 1 ;
        yh_sub01 = 132 ;
        z_l = 35 ;
        z_i = 36 ;
        time = UNLIMITED ; // (2 currently)
        nv = 2 ;
        xq_sub01 = 1 ;
```
>Are they all using the same axes? 

No, but the third indices `yh_sub01` is the same for all. 

```
volcello(time, z_l, yh_sub01, xh_sub01)
thetao(time, z_l, yh_sub01, xh_sub01)
so(time, z_l, yh_sub01, xh_sub01)
umo(time, z_l, yh_sub01, xq_sub01) ;
uo(time, z_l, yh_sub01, xq_sub01) ;
```

>Is it all of the points on the edge of the mask? Can you plot the data and see how different it looks?

No sure where they are relative to the mask.

**Comment by thomas-robinson** [comment]
If you make a diag table with one variable, you can put it in the debugger, stop where the write is called, and check the data to see what's happening.

Are these regional diagnostics?  Can you run without combining the output and then do the nccmp?

**Comment by uramirez8707** [comment]
These are regional diagnostics. @menzel-gfdl has a fix for the `NetCDF: Index exceeds dimension bound` crash 

I simplified the diag_table to only write `volcello`. I ran it interactively with xanadu and current code + Ray's fix. This creates 8 files: `19480101.ocean_Agulhas_section.nc.XXXX`. 

**For Xanadu Code:** 
In each file the `yh_sub01` is equal to {16,18,18,18,18,18,18,8}
(which totals 132)

**For Current Code:**
In each file the  `yh_sub01` is **ALWAYS** equal to 132
and the file that gets written by fre, after combing everything is the exactly the same as the first one!

----

I set a break point just before the call to `write_data`: https://github.com/NOAA-GFDL/FMS/blob/59fe6497b1fe45d18baf8741b851d08b0380620c/diag_manager/diag_output.F90#L1264

The size of `buffer` is correct for the 8 ranks that make it there: {16,18,18,18,18,18,18,8}

So this is probably an issue with the way that `yh_sub01` is defined (wherever that happens)

**Comment by thomas-robinson** [comment]
@uramirez8707 can you give us instructions on how to reproduce the problem?

**Comment by uramirez8707** [comment]
```
git clone - b RTS git@gitlab.gfdl.noaa.gov:mdt/xml.git mdt_xml_RTS
cd mdt_xml_RTS

fremake -x OM4_COBALT_postxanadu.xml -p ncrc3.intel18 -t prod MOM6_SIS2_compile
```
cd to your FMS src directory to get the code with the fix to the other issue: 
```
git pull https://github.com/uramirez8707/FMS.git domain_write_fix
fremake -x OM4_COBALT_postxanadu.xml -p ncrc3.intel18 -t prod MOM6_SIS2_compile —execute
frerun -s -x OM4_COBALT_postxanadu.xml -p ncrc3.intel18 -t prod  -r debug1 OM4p5_CORE2_IAF_COBALT_abio_csf_mle200 --unique --no-transfer
```
This is a reference tar from xanadu: 
/lustre/f2/scratch/gfdl/Uriel.Ramirez/master_20200123_mom6_2019.08.08/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_442x1o/history/19480101.nc.tar

————————————
This is my work dir, fms_debug.x is the executable with current code and fms_debug_oldio.x is the executable with xanadu code. This directory also has the diag_table that I used. The REF_HIST folder has the un-combined history files generated from xanadu. 
 
/lustre/f2/scratch/Uriel.Ramirez/work/FMS2020.01_mom6_ESM4_v1.0.3/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o1.o202963317

Oh the code crashes (obviously) with a div by 0 (obviously) issue in ocean_shared on debug, so to get over that, I did: 
```
cd /lustre/f2/dev/gfdl/Uriel.Ramirez/FMS2020.01_mom6_ESM4_v1.0.3/MOM6_SIS2_compile/src/ocean_shared
Git diff 
```

**Comment by thomas-robinson** [comment]
@uramirez8707 this experiment doesn't have any diagnostics.  What was the diag table for your run with the single regional diagnostic?

**Comment by uramirez8707** [comment]
/lustre/f2/scratch/Uriel.Ramirez/work/FMS2020.01_mom6_ESM4_v1.0.3/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200_1x0m2d_442x1o1.o202963317/diag_table

**Comment by thomas-robinson** [comment]
@uramirez8707 Can you set up a new issue for the regional diagnostics?
