### ISSUE TITLE
Repetitive #ifdef statements in FMS repo

### ISSUE THREAD

**Issue by colingladueNOAA** [NOAA-GFDL/FMS#366]
**Describe the bug**
There are at least 3 #ifdef testing statements in FMS, that should be removed as their function is now handled in test FMS. These #ifdefs can be found in:
axis_utils_mod2.F90
mosaic2.F90
time_interp_external2.F90
drifters.F90
interpolator.F90
horiz_interp.F90

**To Reproduce**
N/A

**Expected behavior**
No duplicate code. 

**System Environment**

**Comment by thomas-robinson** [comment]
@colingladueNOAA can you list all of the files whose tests you removed.
