### ISSUE TITLE
More files need LGPL headers

### ISSUE THREAD

**Issue by colingladueNOAA** [NOAA-GFDL/FMS#378]
**Is your feature request related to a problem? Please describe.**
Need to add LGPL headers to makefiles and others that were previously missed.

**Describe the solution you'd like**
LGPL headers added.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by bensonr** [comment]
@colingladueNOAA can you add the license header block into the fortran example in the CODE_STYLE.md file

**Comment by colingladueNOAA** [comment]
Absolutely.
