### ISSUE TITLE
mpp_chksum does not work for all types

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#381]
**Describe the bug**
 [mpp_chksum](https://github.com/NOAA-GFDL/FMS/blob/master/mpp/mpp.F90#L1227) is an interface that has an `#ifdef OVERLOAD_R4` in it.  This does not allow users to do mpp_chksum for `real(kind=4)` if they compile with a flag to make the default for `real`s `real(kind=8)`

**To Reproduce**
Try to call mpp_chksum with a real*4 not compiling with the -DOVERLOAD_R4 flag.

**Expected behavior**
mpp_chksum should work no matter what is passed to it

**System Environment**
Compile with `-r8` flag and no `-DOVERLOAD_R4`.

**Additional context**

**Comment by thomas-robinson** [comment]
@uramirez8707 and @menzel-gfdl can you look at this issue and make sure I have the details correct.  Please add any additional context that you can think of.

**Comment by thomas-robinson** [comment]
@bensonr I think you fixed this.  Can we close it?

**Comment by bensonr** [comment]
@thomas-robinson - in the current top of the trunk, the OVERLOAD_R4 is still gating the interfaces, so the macro definition is needed to allow r4 checksums when the compile default is for 64-bit reals.  If you want to always have the r4 interfaces, you will need to permanently remove the #ifdef/#endif pairs for the mpp_chksum interfaces in mpp.F90 and function creation in mpp_comm.inc.  PR #492 was to fix a bug when using OVERLOAD_R4, not to enable them all the time.

**Comment by rem1776** [comment]
closing because the mixed precision work included the #ifdef removal described above
