### ISSUE TITLE
Fms2 I/O crash in interpolator.F90

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/FMS#384]
**Describe the bug**
About 10 months into a year-long run of the `c96L33_am4p0` experiment, the model crashed
using `fms2_io` with the following errors:
```
FATAL from PE   552: Input/output error
FATAL from PE   567: Cannot send after transport endpoint shutdown
```
with backtrace:
```
Image              PC                Routine            Line        Source
fms_am4.x          0000000005428F55  Unknown               Unknown  Unknown
fms_am4.x          00000000033D0C1E  mpp_mod_mp_mpp_er          68  mpp_util_mpi.inc
fms_am4.x          000000000324D850  fms_io_utils_mod_         164  fms_io_utils.F90
fms_am4.x          00000000037BF5DD  netcdf_io_mod_mp_         257  netcdf_io.F90
fms_am4.x          000000000317AFE4  interpolator_mod_        3534  interpolator.F90
fms_am4.x          00000000031789E6  interpolator_mod_        1733  interpolator.F90
fms_am4.x          0000000000BF16B4  atmos_carbon_aero        2725  atmos_carbon_aerosol.F90
fms_am4.x          0000000000B84139  atmos_tracer_driv        2530  atmos_tracer_driver.F90
fms_am4.x          00000000005BD429  atmos_model_mod_m         494  atmos_model.F90
fms_am4.x          000000000040D42E  MAIN__                    871  coupler_main.F90
fms_am4.x          000000000040A432  Unknown               Unknown  Unknown
fms_am4.x          0000000005507499  Unknown               Unknown  Unknown
```

**To Reproduce**
This was seen with a custom version of `AM4`, built to include the new radiation scheme `RTE-RRTMGP`.  This error does not appear to be related to the radiation, though.  All repositories
except for `atmos_param` and `GFDL_atmos_cubed_sphere` were built using the `master` branch.
`GFDL_atmos_cubed_sphere` used the `dev/gfdl` branch.  I've only seen the error once, so I'm
not sure how repeatable it is.  The experiment run was `c96L33_amp40` from a variant of
the `xanadu awg` xml.

**Expected behavior**
The same code does not crash when all repositories are built with the `xanadu` tag.  It was
expected that this version of the model would behave similarly.

**System Environment**
- OS: Gaea, c3
- Compiler: Intel 19.0.5.281
- MPI type, and version: Cray MPICH 7.4.0
- netCDF Version: Cray netcdf 4.4.0
- Configure options: `prod` flags included by `fremake`

**Additional context**
This may be related to an issue seen by @nikizadehgfdl.  Niki, can you please provide information about the crash you are seeing?

**Comment by nikizadehgfdl** [comment]
I do not get FATAL  in AM4p1 , instead I get a SIGTERM with a different stack (see below).
So, the crash mode is different from yours, probably because you don't have tropchem?
Also, I have only seen this for the least number of pes (216), it goes away when I use 432 pes.

```
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
fms_am4.1_compile  00000000031294EC  netcdf_io_mod_mp_         388  netcdf_read_data.inc
fms_am4.1_compile  000000000302480D  interpolator_mod_        3532  interpolator.F90
fms_am4.1_compile  0000000003022603  interpolator_mod_        1715  interpolator.F90
fms_am4.1_compile  0000000000EC5DDE  tropchem_driver_m        2464  tropchem_driver.F90
fms_am4.1_compile  0000000000B2A713  atmos_tracer_driv        2561  atmos_tracer_driver.F90
fms_am4.1_compile  000000000058BD51  atmos_model_mod_m         494  atmos_model.F90
fms_am4.1_compile  000000000040E1F0  MAIN__                    871  coupler_main.F90
```

**Comment by thomas-robinson** [comment]
This was likely a hardware issue.  If this error persists, please reopen.
