### ISSUE TITLE
Netcdf error when compiling FMS 2020.02-beta2 tag on gaea

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#390]
**Describe the bug**
Compiling FMS  as part of the AM4 test suite with the 2020.02-beta2 tag on gaea using FRE produces the following error:

`/lustre/f2/dev/$USER/awg_timings_2020.01/src/FMS/fms2_io/netcdf_io.F90(26): error #7013: This module file was not generated by any release of this compiler.   [NETCDF]
use netcdf`

**To Reproduce**
```
module unload cray-netcdf cray-hdf5 fre
module unload PrgEnv-pgi PrgEnv-intel PrgEnv-gnu PrgEnv-cray
module load PrgEnv-intel/6.0.3
module swap intel intel/16.0.3.210
module load fre/test
module load cray-hdf5/1.8.16
module load git

setenv KMP_STACKSIZE 512m
setenv NC_BLKSZ 1M
setenv F_UFMTENDIAN big

fremake -x /lustre/f2/dev/$USER/awg_2020.01-beta1.xml -t debug -p ncrc4.intel cm4p12_2020.01-beta1
```
Then run the resulting build script. 

**Expected behavior**
Executable compiles successfully as it does with 2020.02-beta1.

**System Environment**
Describe the system environment, include:
- OS: 4.4.143-94.47.1.16060.2.PTF.1107299-default 
- Compiler(s): intel 18.0.6 and Gnu 7.3.1
- MPI type, and version: Intel MPI Library for Linux* OS, Version 2018 Update 5 Build 20190404
- netCDF Version: 4.4.0
- Configure options: Any additional flags, or macros passed to configure

**Comment by uramirez8707** [comment]
you can just do 
```
module load fre/test
fremake -x /lustre/f2/dev/$USER/awg_2020.01-beta1.xml -t debug -p ncrc4.intel cm4p12_2020.01-beta1
```

**Comment by uramirez8707** [comment]
@wrongkindofdoctor actually not anymore, fre/test is only usable in cle7/t4 now (as of this morning ... ) 

so you will have to change the xml to use bronx-16 
` <property name="FRE_VERSION" value=bronx-16`

and do `module load fre/bronx-16`

**Comment by wrongkindofdoctor** [comment]
Sweet! Glad this was an easy one to solve. Thanks @uramirez8707.
