### ISSUE TITLE
diag_manager writing a default fill value when there is no data

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/FMS#391]
**Is your feature request related to a problem? Please describe.**
The diag_manager outputs a NETCDF default fill value if a buffer is to be written without being initialized.  The buffer is initialized with this value.  This happens when running a GFDL model for 0 days.

**Describe the solution you'd like**
Up for debate is what should happen in the case.  Should there be no file?  If the missing_value attribute is added, should the array be filled with the `missing_value` specified in the code?  If `_fillvalue` is defined, should it use that value? 

**Describe alternatives you've considered**

**Additional context**

**Comment by thomas-robinson** [comment]
@uramirez8707 We were just talking about this.  Let's put it on the agenda for the next FMS meeting

**Comment by thomas-robinson** [comment]
In the new diag manager, we will open the file when it's time to write (has data to write) and write the meta data at the first open.  This is a change in behavior that needs to be documented clearly.

**Comment by uramirez8707** [comment]
Fixed in #1505
See [documentation](https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/README.md#7-history-files-data-output-changes) for more details
