### ISSUE TITLE
Interpolator opening a file A LOT of times 

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#404]
**Describe the bug**
I ran AM4.1 (2 day run with 216 cores on C4) and I used Darshan to analyze performance. 

Based on Darshan, interpolator is opening a file a ridiculous amount of times, and interpolator in 2020.02.beta2 is **a lot** worse. 
For example, for the file `depvel_gc_am3_tran.nc`
In **Xandu** code:
```
POSIX_OPENS     432
POSIX_BYTES_READ        23072059264
```
It looks like it is opened for every PE twice ... 

But, in **2020.02.beta3** code:
```
POSIX_OPENS     15552
POSIX_BYTES_READ        98672961024
```
Probably twice for PE times the number of times interpolator_init is called, but I am not sure yet.

Note that the size of this file is approx `32088080` bytes

Darshan output for xanadu is located in: `/lustre/f2/darshan/2020/4/28/Uriel.Ra_fms_am4.1_compile.x_id63878_4-28-63468-6255916749374673842_1.darshan`
Darshan output for 2020.02.beta3 is located in:  `/lustre/f2/darshan/2020/4/28/Uriel.Ra_fms_am4.1_compile.x_id1420_4-28-64073-2454477259627255601_1.darshan`

**To Reproduce**
Run AM4.1 while having Darshan loaded. 

**Expected behavior**
A file should not opened by every PEs, TWICE... 
and there is something strange happening with interpolator with new io. 

**System Environment**
Describe the system environment, include:
This is issue is not dependent on the system environment

**Additional context**
Found this while investigating issue #384

**Comment by thomas-robinson** [comment]
It appears #445 closes this issue, so I'm closing it
