### ISSUE TITLE
regional diagnostics are different when using Ocean mask_table 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#409]
**Describe the bug**
Updating FMS and FMScoupler to 2020.02-beta3 caused the ocean regional diagnostics be different when using a mask_table from none mask_table version. The region is different (has smaller longitudinal extent with the mask_table).
The number of diag_axis are different!

```
%  ncdump -h /lustre/f2/scratch/Niki.Zadeh/work/19480101.ocean_Bering_Strait_xanadu.nc | grep 'xh_sub01 = '
xh_sub01 = 6 ;
% ncdump -h /lustre/f2/scratch/Niki.Zadeh/work/19480101.ocean_Bering_Strait_no_mask_xanadu.nc | grep 'xh_sub01 = '  
xh_sub01 = 6 ;
% ncdump -h /lustre/f2/scratch/Niki.Zadeh/work/19480101.ocean_Bering_Strait_no_mask_2020.02.nc | grep 'xh_sub01 = '
xh_sub01 = 6 ;
% ncdump -h /lustre/f2/scratch/Niki.Zadeh/work/19480101.ocean_Bering_Strait_2020.02.nc | grep 'xh_sub01 = '
xh_sub01 = 3 ;
```
Honestly, I don't know what the  xh_sub01 value should be. But the region looks totally different.

Note: The non-mask_table file is bitwise identical to xanadu non-mask_table file!

**To Reproduce**
```
git clone -b RTS git@gitlab.gfdl.noaa.gov:mdt/xml.git mdt_xml_RTS
cd mdt_xml_RTS
fremake -x OM4_COBALT_postxanadu.xml -p ncrc4.intel16 -t prod MOM6_SIS2_compile
frerun -x OM4_COBALT_postxanadu.xml -p ncrc4.intel16 -t prod -r debug1 OM4p5_CORE2_IAF_COBALT_abio_csf_mle200
```
compare  the history file 19480101.ocean_Bering_Strait.nc between the 512 (non mask_table) and 432 (mask_table) runs.

**Expected behavior**
The history files should be identical between mask_table and non-mask_table runs
like it was in xanadu. At the least they regions should look the same.

**System Environment**
ncrc4.intel16

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by thomas-robinson** [comment]
@nikizadehgfdl 
1. This is only an issue for the mask table?  
2. How can we determine which is correct?  Is part of the data being masked out?

**Comment by nikizadehgfdl** [comment]
Here are the locations of uncombined history files:
```
xanadu, no_mask_table
/lustre/f2/scratch/Niki.Zadeh/xanadu_esm4_20190304_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_512x1o/history/

xanadu, mask_table
/lustre/f2/scratch/Niki.Zadeh/xanadu_esm4_20190304_mom6_ESM4_v1.0.3_0/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_442x1o/history/

2020.02, no_mask_table
/lustre/f2/scratch/Niki.Zadeh/FMS2020.02_mom6_ESM4_v1.0.3/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_512x1o/history/

2020.02, mask_table
/lustre/f2/scratch/Niki.Zadeh/FMS2020.02_mom6_ESM4_v1.0.3/OM4p5_CORE2_IAF_COBALT_abio_csf_mle200/ncrc3.intel16-prod/archive/1x0m2d_442x1o/history/
```
Indeed it looks like uncombined regional files are consistent between masked and non-masked runs as @menzel-gfdl  suggested. 

So, this might be an issue with mppnccombine needing an update to work with fms2 regional diagnostics. mppnccombine could be confused about sub-axis feature of fms2 ?  

This might be related to issue #87 of xanadu.
