### ISSUE TITLE
Dummy argument for CT_data_override_* should be intent(inout)

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/FMS#41]
This involves code on head of branch: coupler_type_reform_rwh (@Hallberg-NOAA)

Calls to `data_override()` from `CT_data_override_2d()` and `CT_data_override_3d()` are updating values inside a dummy argument (`var`) that has `intent(in)`.

mpiifort on NCEP's wcoss platform reports:
```
coupler_types.F90(3740): error #6780: A dummy argument with the INTENT(IN) attribute shall not be defined nor become undefined.   [VAR]
    call data_override(gridname, var%bc(n)%field(m)%name, var%bc(n)%field(m)%values, Time)
```

Solution is the dummy argument `var` should have `intent(inout)`.

Relevent code: 
https://github.com/NOAA-GFDL/FMS/blob/3d8f68c0788e69e4ed91123db6ebc20109d6fa9e/coupler/coupler_types.F90#L3731-L3757

Issue first reported by @jiandewang

**Comment by underwoo** [comment]
The commit 9ebe1da3 has been merged into master 9f56841d
