### ISSUE TITLE
urgent update needed to 2020.02 for fv3gfs/make.rules

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/FMS#416]
**Describe the bug**
The wrong comment character delimiter was used when adding the license header.
Added fms2_io/include to the include search list.

**To Reproduce**
N/A

**Expected behavior**
Make using the updated file will not fail with "missing separator"

**System Environment**
All

**Additional context**
N/A

**Comment by colingladueNOAA** [comment]
Does this need to be patched in as well?

**Comment by bensonr** [comment]
Unfortunately, yes it does.
