### ISSUE TITLE
Loosen F2000 restrictions

### ISSUE THREAD

**Issue by mathomp4** [NOAA-GFDL/FMS#42]
Hello all. I currently maintain the FMS instance inside of the GEOS model here at Goddard.  While we have some plans to perhaps just use your Github as a submodule, for now it's sort of walled off and merged into our base.

But, until that point, I did have a request from my work with FMS. It would be to let all compilers be F2000 compliant. At present `include/fms_platform.h` only allows Intel as such:
```
#if defined(__INTEL_COMPILER)
#define _F95
#define _F2000
#endif
```
when in truth, GCC and PGI are quite easily so and NAG should be as well (I haven't gotten NAG to build FMS yet because it is fundamentally impossible at the moment; I've emailed Raymond Menzel about that). So, if anything, the ALLOCATABLE component version of FMS should be default and the pointer one the option.

In my local copy, I've just removed the test, and I could easily do a pull request for that off a fork, but I didn't know if you had a better thought on how to handle it.

**Comment by underwoo** [comment]
@mathomp4, thank you for the request.  I've been slaking in my job at looking at the github issues.  I have taken this request into an internal discussion (NOAA policies make it difficult for many of our developers to participate at the moment).  When we have a decision, I will let you know.

**Comment by mathomp4** [comment]
@underwoo Thanks. Frankly the "destroy all Cray Pointers" would be first on my list as it means NAG Fortran absolutely cannot build FMS. (Not sure if it has an issue, but I know I've talked to Ray Menzel about it in the past.)

**Comment by underwoo** [comment]
We have updated the `include/fms_platform.h` file.  It may be closer to what you need.  Let us know if there is more that is required.  

Unfortunately, we still have cray pointers and we probably will for a while.

**Comment by underwoo** [comment]
If the current `inlcude/fms_platform.h` isn't sufficient, please reopen this issue.
