### ISSUE TITLE
FMS2io sets default file format as NC_FORMAT_64BIT

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#425]
**Is your feature request related to a problem? Please describe.**
FMS2io sets the default file format as `NC_FORMAT_64BIT` and the only way to change it is with code changes, which is not very flexible ...

**Describe the solution you'd like**
The file format should be set as a namelist parameter or some other way. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by menzel-gfdl** [comment]
Also, update `nf90_hdf5` to `nf90_netcdf4` since `nf90_hdf5` is deprecated.
