### ISSUE TITLE
Plan for a CMake build?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#432]
Is there a plan for a CMake build? If so, what's the status?

Right now the ufs_weather_model has a cmake build that builds FMS, but its failing for me.

**Comment by edwardhartnett** [comment]
An alternative, which may work better, is that we (i.e. the NOAA weather models) can just use the autotools build for FMS. That way, we benefit from your maintenance of the package. (As it is now, we must maintain a build system that tracks your build system - not a good long-term solution.)

**Comment by edwardhartnett** [comment]
OK, I am going to close this issue. You don't need a CMake build to meet NOAA needs, we can use the existing (and wonderful) autotools build. And that is what we are now planning on doing.

**Comment by edwardhartnett** [comment]
See the discussion in #276 for an excellent example of why the existing, well-maintained autotools system should be used.

**Comment by thomas-robinson** [comment]
@edhartnett we are working on a cmake build.  The goal is to have both options available.

**Comment by edwardhartnett** [comment]
Excellent. Best of luck!! ;-)

We do that for netcdf-c and netcdf-fortran. The trick of course is to ensure that everything you are setting in config.h, you also set in the CMake build. The way netcdf-c does it is with a separate conflgi.h.cake.in which gets turned into config.h for CMake builds, as well, of course as config.h.in which becomes config.h for autotools builds.

The other big difference is shared object so numbers. Autotools generates the number, and then it is hand-coded into the cmake file.
