### ISSUE TITLE
incorrect time_bnds in history files with the FMS shared code version 2020.01.

### ISSUE THREAD

**Issue by hguo-gfdl** [NOAA-GFDL/FMS#448]
**Describe the bug**
Recently I upgraded my source codes to the FMS shared code version 2020.01. I did a production run and noticed that the time_bnds variable was incorrect in the "atmos_month" history files. For example, 
 /archive/Huan.Guo/awg/xanadu/c96L33_am4p0_testTime/gfdl.ncrc3-intel18-prod-openmp/history/19790101.nc.tar

The time_bnds for "atmos_month" was 
time_bnds =
  "1979-01-01", "1979-02-01",
  "1979-02-01", "1979-03-01",
  "1979-03-01", "1979-04-01",
  "1979-04-01", "1979-05-01",
  "1979-05-01", "1979-06-01",
  "1979-06-01", "1979-07-01",
  "1979-07-01", "1979-08-01",
  "1979-08-01", "1979-09-01",
  "1979-09-01", "1979-10-01",
  "1979-10-01", "1979-11-01",
  "1979-11-01", "1979-12-01",
  **"1979-01-01", "1979-02-01"** 

As a result, a number of analysis plots failed. 

**To Reproduce**
The xml: 
    gaea:/ncrc/home2/Huan.Guo/awg/xanadu/xml_xanadu_2020.02/awg_xanadu.xml

The experiment: c96L33_am4p0_testTime

**Expected behavior**
The time_bnds for "atmos_month" was 
time_bnds =
  "1979-01-01", "1979-02-01",
  "1979-02-01", "1979-03-01",
  "1979-03-01", "1979-04-01",
  "1979-04-01", "1979-05-01",
  "1979-05-01", "1979-06-01",
  "1979-06-01", "1979-07-01",
  "1979-07-01", "1979-08-01",
  "1979-08-01", "1979-09-01",
  "1979-09-01", "1979-10-01",
  "1979-10-01", "1979-11-01",
  "1979-11-01", "1979-12-01",
  **"1979-12-01", "1980-01-01"**

**Comment by uramirez8707** [comment]
#512 closes this issue.
