### ISSUE TITLE
mpp_io vs. fms2_io?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#460]
I have been looking at fms2_io as the I/O code for FMS.

But recently I came across the mpp_io module, which seems to be a different way of doing I/O.

Are both used? Or is mpp_io no longer used?

**Comment by thomas-robinson** [comment]
mpp_io is the "old io" while fms2_io is the "new io".  To make it more confusing, there is fms_io, which is supposed to be a layer above mpp_io.  Right now, both are being used in different component models as we transition to fms2_io.  All of the IO that's being done in this repository (FMS) should be using fms2_io.

**Comment by edwardhartnett** [comment]
Does fms2_io use mpp_io?

**Comment by uramirez8707** [comment]
@edwardhartnett fms2io does not use mpp_io.

**Comment by edwardhartnett** [comment]
Thanks! Good to know.
