### ISSUE TITLE
diag_manager overwrites time_bnds for each variable that was register 

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#463]
**Describe the bug**
After diag-manager_end is called: 

1. It loops through the number of files and calls `closing_file`: 
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3697-L3699
2. In `closing_file` it loops through the num_fields and calls `writing_field`
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3727
...
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3760
3. In `writing_field`, `diag_data_out` is called
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_manager.F90#L3535
4. In `diag_data_out`, it loops through the num_fields **AGAIN** and it writes out the time_bnds, if`num == field`
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_util.F90#L2555-L2581

This means that time_bnds is going to be rewritten for every field because of the **FIRST**  loop through the num_fields in step 2 and the values for the last variables in `num_field` will win :) 
It looks like the same thing is happening with `Time` as well...

This may cause the problem in issue #448 if the last field was registered but data was never sent since `start_dif` will be set to the initial model time. 

**To Reproduce**
Run the awg_xml in 448. Time_bnds is wrong because send_data is never called on the last variable that gets registered (the last variable in the loop in step 2). 

I was able to reproduce the issue using the diag_table and input_nml in `/lustre/f2/scratch/gfdl/Uriel.Ramirez/work/c96L33_am4p0_1x12m0d_432x1a.o268649219`
where I only write 1 history file with two variables for two days. 

**Expected behavior**
`Time_bnds` should be written correctly and maybe only once?

**System Environment**
Describe the system environment, include:
This occurs in any system. 

**Additional context**
N/A

**Comment by ngs333** [comment]
Consider writing a version of diag_data_out that is field independent (that does not take field as an argument.) This would be called from inside the first loop (for each file) but outside (before) the second loop. Functionality common to both diag_data_out may be abstracted.

**Comment by uramirez8707** [comment]
diff is defined based on the time that you send in:
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_util.F90#L2499

start_dif and end_diff are defined here
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_util.F90#L2545-L2552

Add a check here, to only write the time_bnds if diff is between the start_diff and end_diff 
https://github.com/NOAA-GFDL/FMS/blob/37a607ae03ee9e05d4404606e602f5a6796e5339/diag_manager/diag_util.F90#L2559

**Comment by thomas-robinson** [comment]
This is done to make sure that the time of the variable is between the start and end time of the time step.  If it's not within that range, you should not write the time_bnds, averageT1, average_t2, and average_dt.

**Comment by thomas-robinson** [comment]
@ren1776 please take a shot at fixing
