### ISSUE TITLE
Does FMS require netcdf to support HDF5? Or does FMS work with netCDF classic-only builds?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#466]
(Some background: netcdf supports multiple formats, including HDF5 and those formats we refer to as "classic formats." But it is possible to build netCDF in a way that HDF5 is not required. In this case, only classic formats can be read and written.)

OK, here's a question: does FMS always require netCDF to support netCDF/HDF5?

That is, is FMS intended to also work on classic-only netCDF builds?

If so, we must put a little magic in the configure.ac to detect whether netCDF supports netCDF/HDF, and then we must change tests to only attempt to use netCDF/HDF5 format when the underlying netcdf-c library supports it.

Alternatively, if you say that HDF5 is always to be supported, we need to add a check in configure.ac to ensure that is the case, and give the user a good error message at configure-time.

**Comment by thomas-robinson** [comment]
It's also possible that one of our developers is working on something that will require HDF5.

**Comment by edwardhartnett** [comment]
OK, I will put a test for it in configure.ac, and require that netCDF be built with HDF5 support. If not, there will be a configure error. 

If, at some point in the future, you decide to support classic only, we can change it then. ;-)
