### ISSUE TITLE
Build system does not correctly handle changes to .inc files

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#470]
While working on #100 I discovered that changes to the .inc files are not properly handled by make.

That is, I can change an .inc file like mpp/include/mpp_comm_mpi.inc and then run make in the mpp directory, and nothing is done, although (at least) mpp.mod depends on the .inc file I've just changed.

How do you guys build this code after an inc file change?

The problem is easily solved by listing these extra dependencies in the Makefile.am. For example, in mpp/Makefile.am I add:

`libmpp_la_DEPENDENCIES = include/mpp_comm.inc include/mpp_comm_mpi.inc
`

Now, when I change mpp_comm_mpi.inc, make properly rebuilds mpp.mod with the changed code.

If you were using .F90 files, you would have to list as part of the code required to build mpp.mod, and the automake system would track the dependencies automatically. Since you are using .inc files, there is no way for autotools to know about them, and you must explicitly list them as dependencies for all modules that use them.

**Comment by thomas-robinson** [comment]
I believe someone is working on eliminating the .inc files.  It will take time to do.

**Comment by edwardhartnett** [comment]
OK, but that's no reason to live with the pain. ;-) We can fix it, and as you move away from .inc files, we retire the fix as well.
