### ISSUE TITLE
Where is fms2_io used?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#479]
I am working with the new fms2_io code.

Where is this code used in the rest of FMS? That is, where in FMS does netCDF data get written out?

I do not see any place where writing is taking place...

**Comment by uramirez8707** [comment]
@edwardhartnett 
Reading with netcdf takes place inside modules like `interpolator`, `time_interp_external2`, `axis_utils2`
Writing takes place inside `diag_manager`, specifically `diag_output.F90` with `write_data` calls.

**Comment by edwardhartnett** [comment]
Does diag_manager just write out diagnostics?

**Comment by thomas-robinson** [comment]
diag_manager doesn't do any IO.  It sends the data to fms2_io, and fms2_io writes the data to a netcdf file.  The actual writes are in .inc files

[netcdf_write_data.inc](https://github.com/NOAA-GFDL/FMS/blob/master/fms2_io/include/netcdf_write_data.inc)

**Comment by edwardhartnett** [comment]
When a model that uses FMS writes out its timestep worth of data, where does that happen?

**Comment by edwardhartnett** [comment]
Thanks for the answers to this question, they were very helpful!
