### ISSUE TITLE
Should we add doxygen documentation builds to the build system?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#487]
I see you are using doxygen everywhere. That's a good thing!

Do you want me to build in doxygen builds into the configure and makefile? Such as is done for netcdf-c, PIO, and other projects?

It's easy - I will just cut and paste.

When complete, there is an --enable-docs option to configure. If used, doxygen is found and the documentation directory is included in the list of directories to be built. It contains the Doxyfile. (In many projects there is a Doxyfile.in, and configure can do some substitutions there to give some configure control of what docs get built.)

Let me know if this is of interest and I'll put up a PR.

**Comment by colingladueNOAA** [comment]
I am interested in this. I have been trying to clean up our doxygen, but have not looked into this enhancement. Sounds simple and useful.
