### ISSUE TITLE
MOM6 tests seg. fault crash under FMS2020.01 and  PGI19 , in diag_manager

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#498]
**Describe the bug**
All MOM6-solo regression tests seg fault under PGI19 when FMS is upgraded to 2020.01 and 2020.03-alpha1 , probably in diag_manager
Here's -O2 mode crash:
```
srun: error: nid01005: task 0: Segmentation fault
srun: Terminating job step 268657286.7
slurmstepd: error: *** STEP 268657286.7 ON nid01005 CANCELLED AT 2020-06-28T03:03:02 ***
srun: error: nid01005: tasks 1-7: Terminated

```
**To Reproduce**
1. Build executable with 
```
fremake -x /ncrc/home2/Niki.Zadeh/xmls/xanadu/mdt_xml_RTS/MOM6_solo_postxanadu.xml -p ncrc4.pgi19 -t repro mom6_solo_compile
```
Edit the compile script to add "-l" to list_paths
sed -e 's/list_paths/list_paths -l /' -i PATH_TO_YOUR_COMPILE_SCRIPT

2. cd mom6/ocean_only/DOME ; mkdir RESTART
3. srun -n 8 fms_mom6_solo_compile.x (on a compute node)

**Expected behavior**
Tests should run with PGI19. They all passed under FMS2019.01.02

**System Environment**
gaea, CLE7

**Additional context**
These tests all passed under FMS2019.01.02 (same MOM6 commit) with the same compiler PGI19  and CLE7.
This definitely comes from FMS.

**Comment by nikizadehgfdl** [comment]
ddt gives this stack at crash
```
register_global_attributes line 14     err = nf90_put_att(fileobj%ncid, &
diag_output                       line 241  call register_global_attribute(fileob, 'title', TRIM(file_title))
```

Indeed the tests run with an empty diag_table.

**Comment by nikizadehgfdl** [comment]
Is there any way to bubble up these netcdf errors to stdout ?

**Comment by thomas-robinson** [comment]
@nikizadehgfdl this looks like the same problem as #480 where the global attribute is a string.  @uramirez8707 @menzel-gfdl  what do you think?
