### ISSUE TITLE
FMS2: Need to move some functions into fms_mod from fms_io_mod

### ISSUE THREAD

**Issue by laurenchilutti** [NOAA-GFDL/FMS#544]
**Is your feature request related to a problem? Please describe.**
As discussed in the FMS I/O Meeting on July 20th, the following subroutines are in ```fms_io_mod```.  As we move from the use of ```fms_io_mod``` to ```fms2_io_mod``` in GFDL_atmos_cubed_sphere dycore, these functions will need to be used still and are not in ```fms2_io_mod```.  
~~[set_domain](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L7417)
[nullify_domain](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L7437)~~
[string](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L526)

**Describe the solution you'd like**
The group decided that these should be moved from ```fms_io_mod``` to ```fms_mod```.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by uramirez8707** [comment]
`set domain` just saves the domain as a module variable in fms_io_mod, which then may be used in the io operations. 
https://github.com/NOAA-GFDL/FMS/blob/b96f1f50e0fc5be8b3558dfc9f167ad869bcb200/fms/fms_io.F90#L492
https://github.com/NOAA-GFDL/FMS/blob/b96f1f50e0fc5be8b3558dfc9f167ad869bcb200/fms/fms_io.F90#L7411-L7426

`current_domain` is only used in these files:
fms/read_data_4d.inc
fms/fms_io.F90
fms/read_data_3d.inc
fms/write_data.inc
fms/read_data_2d.inc

In fms2_io, the domain is passed in when opening file, therefore this is will not be required when we move to fms2_io. Same thing with `nullify_domain` `get_domain_decomp`  and `return_domain`.
do you agree? @menzel-gfdl @bensonr 

`string` should still me moved to FMS.F90.

**Comment by laurenchilutti** [comment]
Just to make sure we have this instance covered, the dycore calls ```set_domain``` and ```nullify_domain``` in the file ```fv_nggps_diag.F90```, and this file only uses those two calls from fms_io, a comment on line 72 says the set_domain is required for diag manager.  How would I replace these calls? 

https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/blob/9212f09214ca21e59b81c5166af9d10eddc2401c/tools/fv_nggps_diag.F90#L72

https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/blob/9212f09214ca21e59b81c5166af9d10eddc2401c/tools/fv_nggps_diag.F90#L256

**Comment by uramirez8707** [comment]
I think diag_manager gets the domain from the `diag_axis_init` calls:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/41c096b29d771bc86f0ed0eb520493583b4ba4f7/tools/fv_diagnostics.F90#L254-L257

I think these call just won't be required, once fms_io is not used.

**Comment by menzel-gfdl** [comment]
I agree with @uramirez8707 .  @laurenchilutti can you try deleting those two calls and running using fms2_io?

**Comment by bensonr** [comment]
@laurenchilutti - Before testing, please consult with me to ensure we are running an appropriate test.

**Comment by laurenchilutti** [comment]
@bensonr I will talk to you first.  I am currently merging over the current master branch of GFDL_atmos_cubed_sphere into my fms2io branch, and plan to have that complete this evening.  After I complete this process I will get in touch with you (tomorrow probably) and then test the removal of these 2 calls in fv_nggps_diag.F90

**Comment by laurenchilutti** [comment]
Just to let you all know I am still working on this - before I could test out removing any calls to set/nullify_domain I had to first finish updating the old io calls in some files. I should have an update for you today on how removing these does or does not affect the code run and answers.
