### ISSUE TITLE
FMS2: Need to use write_version_number, open_namelist_file, and close_file that are only in fms_io_mod

### ISSUE THREAD

**Issue by laurenchilutti** [NOAA-GFDL/FMS#546]
**Is your feature request related to a problem? Please describe.**
As discussed in the FMS I/O Meeting on July 20th, the following subroutines are in ```fms_io_mod```. As we move from the use of ```fms_io_mod``` to ```fms2_io_mod``` in GFDL_atmos_cubed_sphere dycore, these functions will need to be used still and are not in ```fms2_io_mod```.
[write_version_number](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L8620)
[open_namelist_file](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L7220)
[close_file](https://github.com/NOAA-GFDL/FMS/blob/master/fms/fms_io.F90#L7379)

**Describe the solution you'd like**
The group decided that we should handle these functions in the same way that the ASCII I/O gets handled (possibly move these to ```fms_mod```)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by laurenchilutti** [comment]
@uramirez do you think this will be brought into fms_mod?

**Comment by uramirez8707** [comment]
@laurenchilutti I think these will need to go into fms2_io_mod with the new ascii io 
@GFDL-Eric?

**Comment by uramirez8707** [comment]
@laurenchilutti 

In fv3, there is code like:
https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/blob/424cc1d8733287cd1e067c64b5c7a7a339075ce5/GFDL_tools/fv_ada_nudge.F90#L1524-L1537

Because `INTERNAL_FILE_NML` **should** always be defined, you can just do:
```F90
read(input_nml_file, nml = fv_ada_nudge_nml, iostat = io)
ierr = check_nml_error(io,'fv_ada_nudge_nml')
```
As long `open_namelist_file` is used to open only namelist files and not other ascii files, we can remove the need for it.

**Comment by uramirez8707** [comment]
@thomas-robinson 
Can (should?) [write_version_number](https://github.com/NOAA-GFDL/FMS/blob/4dcc9a795d9ba0cc959ebd93dda5be5f8473545c/fms/fms_io.F90#L8613-L8644) be moved/copied to fms_mod?

This is already made public in fms_mod:
https://github.com/NOAA-GFDL/FMS/blob/4dcc9a795d9ba0cc959ebd93dda5be5f8473545c/fms/fms.F90#L216
and it is always(?) included as `use fms_mod, only: write_version_number`

**Comment by GFDL-Eric** [comment]
@uramirez8707 To the extent that there's a use case for it (which is questionable in my eyes)... it should be in fms. It has nothing to do with I/O, it's a logging tool. I'll let @thomas-robinson weigh in though.

**Comment by laurenchilutti** [comment]
@uramirez8707 I'll try out replacing ```open_namelist_file``` and ```close_file``` with what you suggest.

**Comment by thomas-robinson** [comment]
@uramirez I think it should be kept, but it needs to be modified because it calls fms_io_init.

**Comment by laurenchilutti** [comment]
> @uramirez8707 I'll try out replacing `open_namelist_file` and `close_file` with what you suggest.

My tests ran fine with what you suggested Uriel.
