### ISSUE TITLE
hardcoded mpirun in test_mpp_memutils.sh prevents test from running on gaea 

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#565]
**Describe the bug**
`test_mpp_memutils.sh` currently runs tests using `mpirun` instead of the `run_test` wrapper function, which causes it to fail on systems that use different calls (e.g., srun) to launch mpi jobs, including gaea.

**To Reproduce**
configure and run the autotools test suite on gaea, and test_mpp_memutils fails
**Expected behavior**
Tests should run using the generic run_test wrapper.
**System Environment**
Describe the system environment, include:
- OS: CLE7
- Compiler(s): gnu9, intel19
- MPI type, and version: Cray mpi
- netCDF Version: For both C and Fortran

**Comment by thomas-robinson** [comment]
This is part of the test suite, so I will merge it in whenever it's ready.  No need to hold up 2020.03 for it.
