### ISSUE TITLE
mpp_io bug: Not reading lat_bnds correctly which leads to data_override answer changes

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#578]
**Describe the bug**
If, _for some reason_, you are using a file that has a c null character in the string attributes, the *bnds are not going to be read correctly when you are using mpp io which will lead to "wrong" answers in the corresponding data_override calls for that file ...  

The *_bnds are all read and buffered when `mpp_open` is called, which calls `mpp_read_meta`  

In `mpp_read_meta` there is this logic:
https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/mpp/include/mpp_io_read.inc#L813
which when it is true, it reads the *_bnds, otherwise it will end up here:
https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/mpp/include/mpp_io_read.inc#L874-L875

The logic is **never** going to be true. 
`bounds_name` is read as the `bounds` attribute to the variable (`lat`) (which has the null character) and `name` is obtained as the name of the variable in the file. 

so you will end up with something like this and the *bnds will never be read
```f90
if (trim('lat_bnds') .eq. trim('lat_bnds\000'))
```

Then when you call `get_axis_bounds` in [data_override](https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/data_override/data_override.F90#L2305), `bounds_found` will never be true so you will end up in this if clause, which calculates the bnds instead of reading them. 

https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/axis_utils/axis_utils.F90#L176-L191

@nikizadehgfdl fms2io actually reads the bnds so that explains the "answer changes" in the "OM4p5_BLING_JRA55do1.4_cycle1" experiment. The mpp_io answers are "wrong" 

I printed the `lat_bnds` and this is what I get from [mpp_io](https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/data_override/data_override.F90#L2312):
**-89.8485462603989**       -89.2916328408143
  -88.7330749838675       -88.1725011410287       -87.6114148125410    
  -87.0501193471326       -86.4887175679754       -85.9272542346880  
  -85.3657520244323       -84.8042236749131       -84.2426768993163
  -83.6811166442275       -83.1195462292232       -82.5579679655716
  -81.9963835123501       -81.434794091489**6** ... 

and this if from [fms2io](https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/data_override/data_override.F90#L825):
**-90.0000000000000**       -89.2916328408143     
  -88.7330749838675       -88.1725011410287       -87.6114148125410     
  -87.0501193471326       -86.4887175679754       -85.9272542346880     
  -85.3657520244323       -84.8042236749131       -84.2426768993163     
  -83.6811166442275       -83.1195462292232       -82.5579679655716     
  -81.9963835123501       -81.434794091489**7** ...

The main and probably the most significant difference is the first point, but there are also some places where the last decimal place is different. 

**To Reproduce**
Try to read *_bnds with any file that has the c null character in the *_bounds attribute and you will see it is not exactly the same as in the file. 

**Expected behavior**
If the *_bnds exist in the file then mpp_io should read it from the file, otherwise do the calculation in [get_axis_bounds](https://github.com/NOAA-GFDL/FMS/blob/2ff5e09985ffa7a5a8a51c40c4ffc5619128bf8e/axis_utils/axis_utils.F90#L176)

**System Environment**
Describe the system environment, include:
This happens in any system. 

**Additional context**
N/A

**Comment by nikizadehgfdl** [comment]
Nice work @uramirez8707 . Do we have to notify model runners that ran with JRA dataset in the past to update to fms2_io to evaluate the impact of this bug on their runs?

**Comment by MJHarrison-GFDL** [comment]
This may be the issue @kshedstrom encountered in her Arctic configuration.

**Comment by thomas-robinson** [comment]
@MJHarrison-GFDL what is the data set you are using for the data override?

**Comment by MJHarrison-GFDL** [comment]
The model grid files are here:

https://drive.google.com/drive/folders/1-FZQ1RTfCrDRrhnyGMntwdBl224v7Hr_?usp=sharing

A data override using JRA shortwave shows the problem along the dateline.

**Comment by kshedstrom** [comment]
I thought my problem was something else entirely. I have a domain which is not reentrant in x, but FMS doesn't do the right thing at the dateline with the forcing unless your domain is reentrant. It wrongly assumes that both the model and the forcing have the same topology.

**Comment by MJHarrison-GFDL** [comment]
I will setup a test case for the FMS team to debug.
