### ISSUE TITLE
mkmf build having trouble with MPI functions...

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#58]
I am getting this error with my mkmf build:

./mpp/include/mpp_alltoall_nocomm.h:62:25-25:

 subroutine MPP_ALLTOALLW_(sbuf, ssize, sdispl, stype, &
                         1
Error: Procedure ‘mpp_alltoallw_’ at (1) is already defined at (2)
./mpp/include/mpp_alltoall_nocomm.h:62:25-25:

 subroutine MPP_ALLTOALLW_(sbuf, ssize, sdispl, stype, &
                         1
```
Error: Procedure ‘mpp_alltoallw_’ at (1) is already defined at (2)
./mpp/include/mpp_alltoall_nocomm.h:62:25-25:

 subroutine MPP_ALLTOALLW_(sbuf, ssize, sdispl, stype, &
                         1
Error: Procedure ‘mpp_alltoallw_’ at (1) is already defined at (2)
./mpp/include/mpp_comm_nocomm.inc:1113:42:

     call mpp_error(NOTE, 'MPP_TYPE_FREE: ' &
                                          1

```

Any idea what might be causing this?

**Comment by underwoo** [comment]
What was the `mkmf` command you used to create the Makefiles?

**Comment by edhartnett** [comment]
mkmf -c '-DNDEBUG' -I /usr/local/netcdf-c-4.6.2/include -t \
/home/ed/Downloads/mkmf-19.2.0/templates/linux-gnu.mk -p libFMS.a path_names

**Comment by underwoo** [comment]
Try adding `-Duse_libMPI -Duse_netCDF` as well to the `-c` option.  I think with your options you are attempting to build a configuration we do not test (and likely don't support anymore).

**Comment by edhartnett** [comment]
OK, that was the magic ingredient! Now the build completes successfully and builds libFMS.a.

Thanks for the help!!
