### ISSUE TITLE
2020.03-beta3 tag, mom6 test crash under pgi19 build with FATAL from PE     0: unsupported type.

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#581]
**Describe the bug**
A few of MOM6 solo test cases that run with 2019.01.03 are crashing under 2020.03-beta2 with a very obscure FATAL error and no traceback:

```
FATAL from PE     0: unsupported type.
```

**To Reproduce**
```
module load fre/test
fremake -x /ncrc/home2/Niki.Zadeh/frerts/FMS2020.03-beta3_mom6_20200921/_0/MOM6_solo_postxanadu.xml.20200921154340 -p ncrc4.pgi19 -t repro mom6_solo_compile
frerun -x /ncrc/home2/Niki.Zadeh/frerts/FMS2020.03-beta3_mom6_20200921/_0/MOM6_solo_postxanadu.xml.20200921154340 -p ncrc4.pgi19 -t repro mom6_solo_global_ALE_z -r basic
```

**Expected behavior**
test not crash

**System Environment**
Describe the system environment, include:
whatever fre/test gives on gaea

**Additional context**
These tests passed with 2019.01.03 and pass with -Duse_mpp_io in 2020.03-beta3

**Comment by uramirez8707** [comment]
Did this test worked with any of the 2020s?

**Comment by nikizadehgfdl** [comment]
Yes, these pass with Intel and gnu, only crash with pgi19 for all FMS2020's. 
It passes for pgi19 with -Duse_mpp_io. 
It passes with xanadu and FMS2019.01.03..

Here's a pseudo-stack I got from ddt, some axis thingy (axis_name="scalar_axis       "    is bothering diag_manager_end: 
```
"depth","Processes","Function"
"0","1","mom_main (MOM_driver.F90:654)"
"1","1","diag_manager_mod::diag_manager_end (diag_manager.F90:3700)"
"2","1","diag_manager_mod::closing_file (diag_manager.F90:3770)"
"3","1","diag_manager_mod::writing_field (diag_manager.F90:3535)"
"4","1","diag_util_mod::diag_data_out (diag_util.F90:2626)"
"5","1","diag_util_mod::check_and_open (diag_util.F90:2772)"
"6","1","diag_util_mod::opening_file (diag_util.F90:2036)"
"7","1","diag_output_mod::write_axis_meta_data (diag_output.F90:550)"
"8","1","netcdf_io_mod::register_variable_attribute_0d (register_variable_attribute.inc:60)"
"9","1","fms_io_utils_mod::error (fms_io_utils.F90:164)"
"10","1","mpp_mod::mpp_error_basic (mpp_util_mpi.inc:72)"
"11","1","mpi_abort__"
```
ddt snapshot /home/nnz/ddt_snap.png

**Comment by thomas-robinson** [comment]
@nikizadehgfdl is this a supported model configuration and compilation?  Should we make a new beta tag for this?

**Comment by nikizadehgfdl** [comment]
Yes, this test (and 8 more that crash with the same symptom) are among the 16 or so  MOM6-exmples/ocean_only tests that MOM6 dev runs every time they evaluate a PR. If any crash or even change answers they won't accept the change. That means we cannot sell 2020.03 **without -Duse_mpp_io** . It is not advised to do that anyway because of the performance hit in ocean-ice models.
