### ISSUE TITLE
Diag_manager crash with fms2io 

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#604]
**Describe the bug**
A UFS regression test crashes with the following error and partial stack:

```
NetCDF: Variable not found
```
```
150: fcst.exe           00000000081B3428  mpp_mod_mp_mpp_er          68  mpp_util_mpi.inc
150: fcst.exe           0000000007E96E95  fms_io_utils_mod_         164  fms_io_utils.F90
150: fcst.exe           0000000007FB56DF  netcdf_io_mod_mp_         284  netcdf_io.F90
150: fcst.exe           0000000007FB5F0D  netcdf_io_mod_mp_         364  netcdf_io.F90
150: fcst.exe           000000000800BEA2  netcdf_io_mod_mp_          41  register_variable_attribute.inc
150: fcst.exe           000000000963E0CC  diag_output_mod_m         632  diag_output.F90
150: fcst.exe           0000000007B527B1  diag_util_mod_mp_        2019  diag_util.F90
```

The crash occurs because diag_manager is trying to add a variable attribute to a variable that does not exist (in this case the variable is "Time"). Diag_output.F90 is suppose to call `register_field` but for some reason it is not going to the correct [if block](https://github.com/NOAA-GFDL/FMS/blob/40c6cb9663f574b902ee8d832828be8f04c64feb/diag_manager/diag_output.F90#L582-L612)

The crash seems to occur with when the filename is defined in the diag_table as:
"ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", **6, "hours", "1901 1 1 0 0 0"**

The crash does not occur when using mpp_io. 

**To Reproduce**
I created a simple test program that reproduces this crash: 
[test_diag_manager_time.F90](https://github.com/uramirez8707/FMS/blob/diag_manager_crash/test_fms/ufs_crash/test_diag_manager_time.F90)

ON GAEA: 
```
module load fre/bronx-18 
git clone -b diag_manager_crash git@github.com:uramirez8707/FMS.git

autoreconf --install
./configure --disable-shared FCFLAGS="-fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -qopenmp `nf-config --fflags` -O0 " CPPFLAGS="`nc-config --cflags` -I/opt/intel/2019_up2/impi/2019.2.187/intel64/include/" FC="ftn" CC="cc"
make
cd test_fms/ufs_crash

#In an interactive session
make check 
```
**Expected behavior**
The model should run just like it does with mpp_io. 

**System Environment**
Describe the system environment, include:
This happens in any system. 

**Additional context**
Adding the following hack before the register_variable_attribute seems to make the model work, but we should find a more ... elegant ... solution 
``` F90
          if (.not. variable_exists(fileob, axis_name)) then
               call register_axis(fptr, trim(axis_name), unlimited )
               call register_field(fptr, axis_name, "double", (/axis_name/) )
          endif
```

**Comment by uramirez8707** [comment]
@thomas-robinson @ngs333 @mlee03

**Comment by thomas-robinson** [comment]
@uramirez8707 can you put the test in the diag_manager test folder, and then I can merge it into my fork and work from there.
