### ISSUE TITLE
How to run FMS tests?

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#61]
I see in various directories what seems to be test code. For example, in mpp there is a program test_mpp.F90.

When I build this and run it I don't get good results. Am I doing something wrong? How do you build this? How do you run the tests?

The mkmf system seems to lump these test files into the build of the library. Is that expected?

**Comment by underwoo** [comment]
Within many of the FMS directories, there are test programs.  Unfortunately, the documentation on how to run these is lacking (completely missing for some).  Internally at GFDL, we are working on how to run these tests automatically as we attempt to move towards a continuous testing model.  The work you did in #60 will help us a lot to automate the build process.  I'll see if I can get some documentation on how to run a few of the tests for your work.  We are in the middle of a rewrite of some of the code in the FMS repository (specifically fms and mpp).  Part of the work is to better define the tests, and have documentation on how to run those tests.  

As you mentioned, `mkmf` does lump the files that contain the tests into the library.  This is expected, although not ideal.  All of the tests should require a specific CPP macro to be defined to build the test program.

**Comment by edhartnett** [comment]
Just change your test programs to run and return 0 for success, and some other value for a failure. If you can provide me with such a program I can turn it into an automated test in the build system very easily.

Take a look at some of the netcdf-fortran tests, for example https://github.com/Unidata/netcdf-fortran/blob/master/nf_test/f03tst_vars.F

As you can see, the test calls various netcdf library functions and checks the results. If anything goes wrong, the program stops and returns a non-zero value. 

The tests should not accept command line arguments or any user input, nor should they rely on user inspection of results, though they can output whatever may seem helpful or entertaining. But all that matters is whether they each return 0.

If you have tests that need to run on multiple cores (ex. with mpiexec) I can also show you how to do that. For example, netcdf-fortran has some parallel I/O tests that run on 4 tasks.

Autotools  has a good way to run all the tests and give you nice output (make check). This integrates well into CI.

I have already set up a CI system for this code, of course at the moment it only builds the code, since there are no tests. I am using Jenkins. It's trivial to set up, so if we can get some test code, you can have a CI testing system at any time.

**Comment by menzel-gfdl** [comment]
I've taken a shot at getting [one of our unit tests running (but not yet passing) with autotools.](https://github.com/menzel-gfdl/FMS/commit/3268d2b9e4fbd18af4234d1cedd6713b0a185bb3) @underwoo, I've basically just taken the work you did to get the diag_manager unit tests running with [bats](https://github.com/sstephenson/bats), and put the test program and all the necessary input data into a subdirectory of test_fms.  I'm not sure what the autotools conventions are for this sort of thing, but at least it's a start.

**Comment by edhartnett** [comment]
OK I have taken a look at your branch. Not sure what bats is or why you would want to use it, and it's not clear why you are installing it under FMS. Seems that bats should be it's own system. For example, it has an install script. Are you planning on installing your test system somewhere?

The way autotools tests work is very simple. Test programs are built and run, and if they return 0 they have passed, anything else is considered a failure. Tests and their framework are not installed on the user machine. The idea is that you do a ./configure && make test install, then delete the source code directory, and with it, all tests and test output.

Autotools give you a reasonably formatted output for running all your tests. And that's it. You don't need any other framework.

I can help you sort out the bats autotools stuff, if you can figure out what you want it to do.

I suggest that you guys just start simple and add some unit tests to your code without bringing in another framework. However, I understand that programmers love complexity and can rarely be talked out of it once they have set their mind on using a tool. So in that case I suggest that you not mix your test framework with FMS. Instead, write simple unit tests which are part of FMS, and use your fancy test system elsewhere to also test FMS.

The problem with adding bats to FMS is that you will then be shipping it to and supporting it on all user installations. Is that what you want? Or do you just want to use bats as a local resource, which tests FMS but is not shipped with it?

Do you want this bats stuff to be run when the user types make check?

**Comment by menzel-gfdl** [comment]
Thank you for looking over my branch.  The goal of this is not to increase complexity, but simply to get our current unit tests running.  Unfortunately, I do not think the built-in autotools way of testing will be sufficient for our unit tests (at least with how they are written now) because:

- All tests for a module use the same test program, but require different configurations (i.e., sets of namelist parameters) and sometimes specific input data files.

- We attempt to test the code's failure modes.  Most of the FMS code doesn't allow the user to handle errors, but instead prints a message and (MPI) aborts when an error occurs (all errors return the same value).  So some kind of system is needed that can both check the return code for the program and parse the stderr for a particular error message to make sure that the model is failing in the expected way.

If autotools can handle these requirements natively, I'd be more than happy to remove bats.  I agree that we do not want to have to install/support bats on all user systems; I grabbed it for now because it's essentially just a few bash scripts and @underwoo had already set it up to run these specific tests.

**Comment by edhartnett** [comment]
I believe autotools can handle both of those cases.

In terms of running the programs, can it be done from the command line? If so, we write a test script(s). This is how ncgen/ncdump are tested in netcdf. 

We can also handle expected errors. In other words, we can run a command and require that it fails with a certain error code.

**Comment by edhartnett** [comment]
@menzel-gfdl can you put up a PR with just the F90 test code and a namelist and command line that runs one variant of the test? Then I will wire it into the build system for you...

**Comment by menzel-gfdl** [comment]
@edhartnett I put in [this pull request](https://github.com/NetCDF-World-Domination-Council/FMS/pull/4).
Please look in the directory test_fms/data_override.

**Comment by edhartnett** [comment]
OK, apparently there is a testing effort underway which I hope will soon be merged to master. So I will close this issue. When that testing branch is merged to master I look forward to running those tests! ;-)
