### ISSUE TITLE
mpp_get_UG_domain_tile_pe_inf does not return information in arguments correctly

### ISSUE THREAD

**Issue by slm7826** [NOAA-GFDL/FMS#623]
**Describe the bug**
Subrutine `mpp_get_UG_domain_tile_pe_inf` incorrectly uses optional arguments, resulting in segmentation fault if `npes` is present, but `root_pe` is not; returns incorrect number of `npes` in either case.

**To Reproduce**
```
  integer tile_npes
  ...
  call mpp_get_UG_domain_tile_pe_inf(lnd%ug_domain, npes=tile_npes)
```
Model crashes with SIGSEGV:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fms_code.x         00000000015E565D  Unknown               Unknown  Unknown
fms_code.x         0000000000F16060  Unknown               Unknown  Unknown
fms_code.x         0000000000A10B0C  mpp_domains_mod_m         534  mpp_unstruct_domain.inc
...
```
**Expected behavior**
call finishes successfully and return correct values for optional arguments, in any combination of presence or absence. 

**System Environment**
Describe the system environment, include:
- OS: SUSE Linux Enterprise Server 15 SP1
- Compiler(s): Intel 18.0.6.288

**Comment by slm7826** [comment]
Since it is scheduled for a later release, would it be possible to plan on adding unit tests for the rest of the functionality in the unstructured grid `mpp` module?

I am not sure what your policy is on the unit tests, or if they are even feasible, but I think they would be nice to have, if possible.

**Comment by thomas-robinson** [comment]
There is a mpp_domains test and a subroutine in there that tests the unstructured grid. https://github.com/NOAA-GFDL/FMS/blob/master/test_fms/mpp/test_mpp_domains.F90#L3416
It doesn't call `mpp_get_UG_domain_tile_pe_inf` though.  

I think the unstructured grid test is skipped though for our CI testing.  Maybe @uramirez8707 knows why.

**Comment by slm7826** [comment]
Ah, great, that sounds like it is only a question of tuning it on in some future.
