### ISSUE TITLE
Additional flexibility to choose the time string suffix for output file names 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#626]
**Is your feature request related to a problem? Please describe.**
When history files are periodically created following the specification in the ``diag_table``, e.g.,

"ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", 6, "hours", "1901 1 1 0 0 0",

the mid-point of the time bounds are used for the time string suffix.  For example, the output files from the above entry would produce

     ocn_2016_10_03_03.nc for the time bound [0,6]
     ocn_2016_10_03_09.nc for the time bound [6,12]

For an hourly write-out,

"ocn%4yr%2mo%2dy%2hr",      1,  "hours", 1, "hours", "time", 1, "hours", "1901 1 1 0 0 0",

the output files would be 

     ocn_2016_10_03_00.nc for the time bound [0,1]
     ocn_2016_10_03_01.nc for the time bound [1,2]

Here, the mid-point of the time bounds are at 30 minute intervals and are not used in the filename, which could lead to confusion.  Furthermore, comparing outputs from the 6-hour and 1-hour write-out becomes complicated because of the file names.  

**Describe the solution you'd like**
Instead of using the mid-point of the time bounds, is there an option to choose the _beginning_ or the _endpoint_ of the time bounds for file naming?  For example, for the files to be named

     ocn_2016_10_03_00.nc for the time bound [0,6]
     ocn_2016_10_03_06.nc for the time bound [6,12]

**Describe alternatives you've considered**
The namelist variable option, ``mix_snapshot_average_fields=.true.``, uses the endpoint of the time bounds for filenames but this does not seem like the best and a safe option.

**Additional context**
All files required to test the above mentioned behavior is in ``test_fms/diag_manager`` with unit test ``test_diag_manager_time`` and ``diag_table_24``

**Comment by mlee03** [comment]
I will tag @jiandewang who has requested for this additional feature.

**Comment by uramirez8707** [comment]
Fixed in #660
