### ISSUE TITLE
compilation fails without MPI

### ISSUE THREAD

**Issue by slm7826** [NOAA-GFDL/FMS#635]
**Describe the bug**
If use_libMPI is not defined, compilation fails on `mpp.F90`. There are many errors that see to indicate that a large number of procedures is not defined in nocomm includes. Here are few examples:
```
/lustre/f2/dev/Sergey.Malyshev/tmp/src/FMS/mpp/mpp.F90(504): error #7950: Procedure name in MODULE PROCEDURE statement must be the name of accessible module procedure.   [MPP_TYPE_CREATE_CMPLX4]
      module procedure mpp_type_create_cmplx4
-----------------------^
/lustre/f2/dev/Sergey.Malyshev/tmp/src/FMS/mpp/mpp.F90(505): error #7950: Procedure name in MODULE PROCEDURE statement must be the name of accessible module procedure.   [MPP_TYPE_CREATE_CMPLX8]
      module procedure mpp_type_create_cmplx8
-----------------------^
/lustre/f2/dev/Sergey.Malyshev/tmp/src/FMS/mpp/mpp.F90(750): error #7950: Procedure name in MODULE PROCEDURE statement must be the name of accessible module procedure.   [MPP_ALLTOALL_CMPLX4]
     module procedure mpp_alltoall_cmplx4
```

**To Reproduce**
Try compiling without MPI. If it is any help, my scripts are in directory `/lustre/f2/dev/Sergey.Malyshev/2020.04-nompi-compile-issue` on gaea.

To reproduce, copy files `checkout`, `compile`, and directory `tools` from there and do this:
```
./checkout
./compile
```

**Expected behavior**
The code should compile and run without MPI library, as previous versions did. This is important for single-point runs that we use extensively in research and development, and I think this will also be important for single-column model that is being currently resurrected.

**Comment by underwoo** [comment]
I might have a fix for this. I'll check some of my local working directories to see what I did with it.

**Comment by underwoo** [comment]
I couldn't find what I did before, but the fix was straight forward. PR #637 should resolve the issue.
