### ISSUE TITLE
redundancy in data output for history files written out periodically

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#636]
**Describe the bug**
For diagnostic files written out periodically during a run, data set corresponding to all the previous time_bounds gets written out to each output file. 

For example, given the following diag_table specification 

``"ocn%4yr%2mo%2dy%2hr",      6,  "hours", 1, "hours", "time", 6, "hours", "1901 1 1 0 0 0"``
 
the file ``ocn_2016_10_03_09.nc`` contains the data set already printed in ``ocn_2016_10_03_03.nc``

**To Reproduce**
The ``test_diag_manager_time`` unit test in ``diag_manager`` reproduces this problem.

**Expected behavior**
Data corresponding to the current time_bound should only be written out to its corresponding file.

**System Environment**
This behavior will occur on all systems.

**Additional context**
The UFS models require this fix in order to use fms2_io.

**Comment by uramirez8707** [comment]
Fixed in #642
