### ISSUE TITLE
What should be installed?

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#64]
With your mkmf build system, there does not seem to be a "make install" target. In the autotools system, of course there is. ;-) 

Right now "make install" installs only the libFMS library (static and shared). It is installed in the lib directory under whatever was provided to the configure script prefix argument. For example:

./configure --prefix=/home/ed/test_fms && make install

will build the FMS library and install it in  /home/ed/test_fms/lib, creating directories as needed.

With netcdf-fortran and some other fortran packages I work with, we also install the .mod files. With netcdf-fortran we also install a netcdf.inc file, and some man pages.

So the question is, do we know of anything we want to install other than libFMS?

**Comment by underwoo** [comment]
We will need most of the *.mod files, and some of the *.h and *.inc.  For this first draft, please install all the *.mod and the two *.h files in the include directory.  We can widdle down the number of *.mod files later if we feel it is too many, or there are some we do not want the external components to call.  (Note, fueled by the work on #60 you have done, we are thinking about ways to better limit the routines we expose with the FMS library.)

@edhartnett, again thank you for the work you are doing for this autotools build.

**Comment by edhartnett** [comment]
I hope you find the Makefile.am files to be useful in understanding your dependencies.

I will add the install files you requested. It's easy to change from one that's installed to one that is not.

**Comment by edhartnett** [comment]
For netcdf-fortran we end up with a mod file that contains the entire netcdf F90 API, so the user just has to do use netcdf.

But in your case you have a lot of mod files, is that correct? So the user has to know which mods files to install for the functionality they want?

**Comment by underwoo** [comment]
That is correct, many module files (for better or for worse).

We have had several conversations of how to better organize the FMS source, and which of the __many__ modules we would like exposed from the library.  This is something we will address during the FMS/MPP rewrite  (ongoing).

**Comment by edhartnett** [comment]
OK, I am putting in some extra stuff to deal with mod files. THey are a bit tricky.

I will mark all of them for install, but if you later decide you only want to install some of them, that's easy too.

**Comment by edhartnett** [comment]
I have updated the automake files to properly handle the mod files, including installing all of them.

Also there are some .h and .inc files in a few of the directories (for example, the drifers directory has:

`drifters_compute_k.h drifters_push.h drifters_set_field.h fms_switches.h
`

I am installing all of these, but if you don't want them installed, let me know.

**Comment by underwoo** [comment]
Thank you.  We'll leave these files for now.  We need to review the other model component code to ensure someone isn't using them.  We can remove them later if needed.
