### ISSUE TITLE
names of nest files change with fms2_io

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#655]
**Describe the bug**
Filenames for nest files differ between mpp_io and fm2_io.  For example, ``atmos_4xdaily.nest02.tile7.nc`` file from mpp_io becomes ``atmos_4xdaily.nest02.nc`` with fms2_io 

**To Reproduce**
All runs using nested grid and outputting nest files will show this behavior.

**Expected behavior**
The filenames should be the same between mpp_io and fm2_io

**System Environment**
The filename changes occur on all systems.

**Additional context**
This fix is required for 2020.04.01

**Comment by uramirez8707** [comment]
Fixed in #657
