### ISSUE TITLE
is netcdf required for FMS build?

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#67]
We have the preprocessor macro use_netCDF, which we are always setting.

Does FMS build without netCDF? Or is netcdf always required?

**Comment by underwoo** [comment]
This is one of those legacy items that we haven’t dealt with yet. I don’t believe it is possible to run a GFDL model without NetCDF. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edhartnett** [comment]
Well why would you ever want to run a model without netCDF? That would be maddness! ;-)

I will change the configure so that, as with MPI, a lack of netCDF will cause configure to stop.

What we are trying to achieve with configure is that it checks everything that can be checked, and finds all potential build problems before they occur. Instead of getting a compiler or linker error, the user should get a message from configure explaining what is wrong, and configure will refuse to continue until it is fixed.

So if the user tries to build FMS without a netCDF install, they will get a message explaining that, instead of a compiler error the first time "use netcdf" is encountered in the code.
