### ISSUE TITLE
Fms2io replace types with those defined in platform_mod

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#674]
**Describe the bug**
One of the changes in https://github.com/NOAA-GFDL/FMS/pull/664, was replace 
```F90 
type is (integer(kind=int32)) 

```
to 
```F90
type is (integer(kind=i4_kind))
```
similarly with int64, real32, real64 to i8_kind, r4_kind, r8_kind in fms2io. 

This was not done in:
1.axis_utils2.F90
2. compressed_write.inc 
3. register_variable_attribute.inc
4. get_global_attribute.inc
5. test_fms/fms2_io/land_compressed_restart_file_test.inc
6. test_fms/fms2_io/land_unstructured_restart_file_test.inc
7. test_fms/fms2_io/setup.F90

**To Reproduce**
N/A

**Expected behavior**
Code should we consistent. 

**System Environment**
Any

**Additional context**
N/A

**Comment by uramirez8707** [comment]
fyi @wrongkindofdoctor

**Comment by wrongkindofdoctor** [comment]
*Sigh* Always something with these typedefs. Thanks for listing the files. I'll fix them.
