### ISSUE TITLE
Test "binaries" were accidently commited to the repo

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#675]
**Describe the bug**
The "binaries" generated by autotools (after `make check`) were accidentally committed to the repo. 

These need to be removed because they are not needed, since they are generated after each fresh build.

test_fms/mpp/test_clock_init
test_fms/mpp/test_domains_simple
test_fms/mpp/test_mpp
test_fms/mpp/test_mpp_broadcast
test_fms/mpp/test_mpp_domains
test_fms/mpp/test_mpp_gatscat
test_fms/mpp/test_mpp_get_ascii_lines
test_fms/mpp/test_mpp_mem_dump
test_fms/mpp/test_mpp_memuse
test_fms/mpp/test_mpp_memutils_begin_2x
test_fms/mpp/test_mpp_memutils_begin_end
test_fms/mpp/test_mpp_memutils_end_before_begin
test_fms/mpp/test_mpp_npes
test_fms/mpp/test_mpp_pe
test_fms/mpp/test_mpp_print_memuse_stats_file
test_fms/mpp/test_mpp_print_memuse_stats_stderr
test_fms/mpp/test_mpp_root_pe
test_fms/mpp/test_mpp_sum
test_fms/mpp/test_mpp_update_domains
test_fms/mpp/test_peset
test_fms/mpp/test_read_ascii_file
test_fms/mpp/test_read_input_nml
test_fms/mpp/test_stderr
test_fms/mpp/test_stdout
test_fms/mpp/test_system_clock

input.nml and input_alternative.nml are generated by the test scripts and they should also not have been committed ...
https://github.com/NOAA-GFDL/FMS/blob/b96f1f50e0fc5be8b3558dfc9f167ad869bcb200/test_fms/mpp/test_read_input_nml2.sh#L37
https://github.com/NOAA-GFDL/FMS/blob/b96f1f50e0fc5be8b3558dfc9f167ad869bcb200/test_fms/mpp/test_read_input_nml2.sh#L44

**To Reproduce**
N/A

**Expected behavior**
FMS should not have these "binaries" committed ...

**System Environment**
N/A

**Additional context**
N/A

**Comment by thomas-robinson** [comment]
It might be better to rebase so these files are included in the history.  Do we know which PR these came in with?

**Comment by thomas-robinson** [comment]
It looks like it's #664 which is a big one
