### ISSUE TITLE
FMS2_io in coupler/coupler_types.F90

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#677]
**Is your feature request related to a problem? Please describe.**
coupler/coupler_types.F90 has interfaces `coupler_type_register_restarts` and `coupler_type_restore_state`, which are basically wrappers for `register_restarts` and `restore_state` calls.
https://github.com/NOAA-GFDL/FMS/blob/b96f1f50e0fc5be8b3558dfc9f167ad869bcb200/coupler/coupler_types.F90#L272-L283

These subroutines are called in FMScoupler/coupler_main.F90 and SIS2 (`coupler_type_register_restarts`). 
I think they end up being used in the OMIP experiments. 

**Describe the solution you'd like**
Since mpp_io will soon be deprecated, fms2_io will need to be implemented in these routines. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thomas-robinson** [comment]
Do you want to wrap the new routines?
