### ISSUE TITLE
add sample Fortran test to the autotools build

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#68]
I will put in a Fortran test in the autotools builds. The tests will simply return 0 (i.e. pass). But that's where you can insert some test code for your library.

To do this I will add a test directory, which will be compiled *after* libFMS, which is the directory where the combined libFMS library is built. The library must be built before the test is run, so the tests must be in their own directories. This also makes it easy to organize tests. (For example in the netcdf-c build we have test directories nctest, nc_test, nc_test4, dap_test, hdf4_test, etc.)

I will add a directory test_fms, and put a simple test in there. This test will be run by "make check" so it's a starting point for your continuous integration.

**Comment by menzel-gfdl** [comment]
Thank you.  I have started working on putting some of our tests and their associated input data into their own directories which can be included in the test_fms directory you have created.  Once I have some ready, I'll put a in a pull request.

**Comment by edhartnett** [comment]
OK, much better to start with the first one you have working, instead of getting several working and then telling me. Let's stay in close coordination. As soon as you get a test program running, tell me, and I can put it into the build.

You should also set up a CI system. It takes about 5 minutes and is very useful to ensure that we don't break stuff. I have a CI system (Jenkins) and it is running this branch every time I commit changes to it.

**Comment by underwoo** [comment]
We do have some tests that run on our internal system using [GitLab-CI](https://about.gitlab.com/product/continuous-integration/).  We will update the `gitlab-ci.yml` file to begin testing with autotools as well.  We also have plans to get a [Travis-CI](https://travis-ci.org/) working so other collaborators can configure their own Travis-CI account to run on their fork.

**Comment by edhartnett** [comment]
Those are great. I also have my own system that I use personally in my browser (Jenkins). It's very useful.

Anyway, if you can give me some working fortran code to insert I am happy to do so. Just cut and paste it here...
