### ISSUE TITLE
Github Actions tests fail after merging mixed precision and Makefile updates

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#684]
**Describe the bug**
The Github actions tests to fail with 'module not found' errors in some of the new test_fms/mpp unit tests after a build attempt for a test tag, e.g.:
```
compare_data_checksums_int.F90:23:4:

 use mpp_mod, only : mpp_root_pe, mpp_chksum, mpp_error, mpp_sync_self, mpp_pe
    1
Fatal Error: Can't open module file 'mpp_mod.mod' for reading at (1): No such file or directory
compilation terminated.
```
PR [#676](https://github.com/NOAA-GFDL/FMS/pull/676) introduced new tests with accessory modules for common subroutines that were defined in the test_fms/mpp [makefile.am](https://github.com/NOAA-GFDL/FMS/blob/master/test_fms/mpp/Makefile.am) file as follows:
```
# Each mod file depends on the .lo (library object) file.
compare_data_checksums.mod : compare_data_checksums.lo
compare_data_checksums_int.mod : compare_data_checksums_int.lo
fill_halo.mod : fill_halo.lo
test_mpp_update_domains_real.mod : test_mpp_update_domains_real.lo
test_mpp_update_domains_int.mod : test_mpp_update_domains_int.lo
test_domains_utility_mod.mod : test_domains_utility_mod.lo

# Some mods are dependant on other mods in this directory
test_mpp_update_domains_main.lo : test_mpp_update_domains_real.mod test_mpp_update_domains_int.mod
test_mpp_update_domains_real.lo : fill_halo.mod compare_data_checksums.mod
test_mpp_update_domains_int.lo: fill_halo.mod compare_data_checksums_int.mod
test_update_domains_performance.lo : compare_data_checksums.mod compare_data_checksums_int.mod
test_mpp_update_domains_ad.lo : compare_data_checksums.mod
test_mpp_domains.lo : compare_data_checksums.mod test_domains_utility_mod.mod
test_mpp_global_field.lo : compare_data_checksums.mod compare_data_checksums_int.mod
test_mpp_global_field_ug.lo : compare_data_checksums.mod compare_data_checksums_int.mod

# Mod files are built and then installed as headers.
MODFILES = compare_data_checksums.mod \
	compare_data_checksums_int.mod \
	fill_halo.mod \
	test_mpp_update_domains_real.mod \
	test_mpp_update_domains_int.mod \
	test_domains_utility_mod.mod
```

These definitions appear to no longer be compatible with the changes introduced in [#651](https://github.com/NOAA-GFDL/FMS/pull/651), leading to failure when running `make distcheck` via the CI.

**To Reproduce**
Merge PR #651 and PR #676 
**Expected behavior**
CI passes (yay!)

**System Environment**
Describe the system environment, include:
see [here ](https://github.com/NOAA-GFDL/FMS/actions/runs/558635717/workflow)for the workflow config file
**Additional context**
See [here](https://github.com/NOAA-GFDL/FMS/actions/runs/558635717) for the Actions output logs

**Comment by underwoo** [comment]
@wrongkindofdoctor I think I have a fix for this.  Keep an eye open for a PR to your repository.

**Comment by underwoo** [comment]
PR wrongkindofdoctor/FMS#91 submitted.
