### ISSUE TITLE
parallel builds not actually working...

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#70]
I had told you that make -j would work on this new build system, but that's not quite true yet, though I hope it will be soon.

Until further notice, don't use make -j, it will not work well.

The issue is that some of the mod files depend on other mod files being built first. I have to record these dependencies in the makefiles before parallel builds will work.

**Comment by edhartnett** [comment]
OK, parallel builds are working now, so make -j can be used safely.

It does result in about ~%25 speedup. This percentage will increase as and if you add tests, since they are usually very parallelizable to compile and run.

**Comment by underwoo** [comment]
Can this issue be closed now?

**Comment by edhartnett** [comment]
Like a bunch of others it will be closed when the PR is merged to master, but if you want to close it early we can.

**Comment by underwoo** [comment]
It appears the parallel builds are not functioning fully yet, at least not with the Intel compiler.  I might have a solution.  I need to run the build many more times (as this is intermittently hit).

**Comment by edhartnett** [comment]
OK, another way to check is to put this in the Makefile.am where you suspect a problem:

```
# Turn off parallel builds in this directory.
.NOTPARALLEL:

```

**Comment by underwoo** [comment]
I'll have an update pushed after the tests finish.  But the solution that appears to solve the problem is to modify the `Makefile.am`s that list mods that are dependent on other mods to use the `.mod` file as the dependency instead of the object file.  For example, the `diag_manager/Makefile.am` (since this is the component that hit the parallel build problem) will become:

```make
# Some mods are dependant on other mods in this dir.
diag_axis.$(OBJEXT): diag_data_mod.mod
diag_manifest.$(OBJEXT): diag_data_mod.mod
diag_output.$(OBJEXT): diag_axis_mod.mod diag_data_mod.mod
diag_util.$(OBJEXT): diag_data_mod.mod diag_axis_mod.mod diag_output_mod.mod diag_grid_mod.mod
diag_table.$(OBJEXT): diag_data_mod.mod diag_util_mod.mod
diag_manager.$(OBJEXT): diag_axis_mod.mod diag_data_mod.mod diag_util_mod.mod diag_output_mod.mod diag_grid_mod.mod diag_table_mod.mod diag_manifest_mod.mod
```

I'm not sure ATT if this may cause other issues, but it does appear to resolve the parallel build issue I was encountering.

**Comment by edhartnett** [comment]
The only reason I did not do it that way was to avoid the potential problem of mod names being uppercased, which we have not hit yet apparently. So I think this will be fine.
