### ISSUE TITLE
Query about EditorConfig File

### ISSUE THREAD

**Issue by mathomp4** [NOAA-GFDL/FMS#702]
I saw that FMS added a `.editorconfig` file in the 2021.01 release and had question about it. From how I read the file, it looks like FMS will use tabs everywhere. I see:
```editorconfig
# Settings for _all_ files
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2
trim_trailing_whitespace = true

# Settings for specific files, or file patterns.  [{Makefile,*.am}]
indent_style = tab
indent_size = 1
```
I think those last two were meant only for Make:
```editorconfig
# Settings for specific files, or file patterns.
[{Makefile,*.am}]
indent_style = tab
indent_size = 1
```

If so, I can make a PR (very easily).

**Comment by rem1776** [comment]
You're right looks like a typo, it should definitely be 2 space indents for F90 files. Feel free to make a PR whenever you get a chance

**Comment by mathomp4** [comment]
Ah whoops. This fell off my plate. Sorry about that, and thanks for fixing it!
