### ISSUE TITLE
FMS2021.01 PGI run crashes with meaningless  FATAL: unsupported type.

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#704]
**Describe the bug**
Ocean-ice models crash with PGI (19) executable in FMS2020.04 and FMS2021.01 

Prod mode exec gives no output/error message or traceback of any sort. It just crashes with:
NOTE frsrun: error: nid01901: tasks 0-7: Segmentation fault

Debug mode exec gives:
FATAL from PE     6: unsupported type.

**To Reproduce**
```
module load fre/test
fremake -x /ncrc/home2/Niki.Zadeh/frerts/FMS2020.04_mom6_20210308/_0/OM4_extra.xml.20210308124657 -p ncrc4.pgi19 -t debug MOM6_SIS2_compile

frerun -x /ncrc/home2/Niki.Zadeh/frerts/FMS2020.04_mom6_20210308/_0/OM4_extra.xml.20210308124657 -p ncrc4.pgi19 -t debug MOM6_SIS2_Baltic --no-transfer -s
```
**Expected behavior**
Experiment should run fine with PGI as it does with Intel and GNU and as it did in xanadu.

**System Environment**
-p ncrc4.pgi19

**Additional context**
Prod  mode produces a core file , but pgdbg does not work on c4
```
pgdbg /lustre/f2/dev/Niki.Zadeh/FMS2021.01-beta1_mom6_20210218/MOM6_SIS2_compile/ncrc4.pgi19-prod/exec/fms_MOM6_SIS2_compile.x core
pgdbg-Error-Required tool java was not found
```

Why is there no traceback? I compiled with -g -traceback !

**Comment by nikizadehgfdl** [comment]
Here's the stack from ddt:
```
atmos_land_ice_exchange.F90 line 883
data_override.F90                      line 647
data_override.F90                      line 855 
time_interp_external2.F90         line 448
axis_util2.F90                             line 104
get_variable_attribute.inc           line 68
fms_io_utils                                line 164
```

Looks like data_override/netcdf issue.  @uramirez @GFDL-Eric could you take a look? Thanks.
Here's the workdir on gaea:
```
/lustre/f2/scratch/Niki.Zadeh/work/FMS2021.01-beta1_mom6_20210218/MOM6_SIS2_Baltic_1x1m0d_8x1o.o268765449
```
and debug executable
```
/lustre/f2/dev/gfdl/Niki.Zadeh/FMS2020.04_mom6_20210308/MOM6_SIS2_compile/ncrc4.pgi19-debug/exec/fms_MOM6_SIS2_compile.x
```

**Comment by nikizadehgfdl** [comment]
Inside subroutine get_variable_attribute_0d() , the 4th argument, which was passed in as string "cart", is defined as: 
class(*), intent(inout) :: attribute_value 
ddt shows it is "not allocated"!  What's this class(*) magic? Is it in FORTRAN standards?

**Comment by GFDL-Eric** [comment]
Hi Niki,

class(*) is supported by Fortran standards (such as those standards exist),
though I think some compilers (including PGI) and debuggers (ddt) have a
tough time with them. It "works", but for PGI we need some special magic.
We might be able to do this with a 2 line change in axis_utils2.F90, lines
102 and 104:

102 old: call get_variable_attribute(fileobj, axisname, "cartesian_axis",
cart)
104 old: call get_variable_attribute(fileobj, axisname, "axis", cart)

102 new: call get_variable_attribute(fileobj, axisname, "cartesian_axis",
cart(1:1))
104 new: call get_variable_attribute(fileobj, axisname, "axis", cart(1:1))

I don't know if it's worth a test with just implementing that change
directly? If it doesn't work, we can explore some other possible solutions.

Eric

**Comment by nikizadehgfdl** [comment]
Thanks Eric, that mod carried the model a little bit further where it crashed with the same FATAL message (in debug mode), this time in netcdf_io.F90 line 1897 , unsupported type for variable_missing

  call get_variable_attribute(fileobj, variable_name, "missing_value", variable_missing)

At this point  real(kind=r8_kind) :: variable_missing  is not initialized.  I thought that might be the issue so I set it to -999. before invoking the above call, but it crashed the same way. ddt shows  variable_missing inside get_variable_attribute as being "Not Allocated"!
 I don't understand what's going on other than PGI is not getting what class(*) means.

**Comment by GFDL-Eric** [comment]
Niki, I'm not sure any of us really "get" where/why PGI is misinformed
about class(*), and so we're putting in hacky hints like trim and length
bounds to sort of force PGI to recognize that this is indeed a string. For
reals, I'm not sure that such a "hint" exists... it's possible that it
would work by recasting: real(variable_missing, kind=r8_kind), but it's
also possible that for some reason r8, class(*), and PGI just don't mix. I
suppose we could try real(kind=r4_kind) :: variable_missing and see if that
makes it work (then at least we'd know it was an issue specific to r8). I'm
hoping we don't have to get rid of class(*) to make PGI work but maybe
that's where we're headed.

**Comment by nikizadehgfdl** [comment]
Thanks, but the r8_kind to r4_kind change didn't change the issue, crashed the same.

BTW, was the rational behind introducing class(*) to avoid defining a few (2?) more interfaces for get_variable_attribute ? 
Is it possible that class(*) is also responsible for crash before printing the FATAL message in -O3 mode?

**Comment by thomas-robinson** [comment]
Is there a small test case that can demonstrate the problem we are having?

**Comment by nikizadehgfdl** [comment]
Yes, see "To Reproduce" above. The test runs on 8 cores.

**Comment by thomas-robinson** [comment]
I mean a very small example that I could send to PGI

**Comment by GFDL-Eric** [comment]
@nikizadehgfdl for what it's worth, most (all?) of the include files in fms2_io have class(*), so it would take a pretty substantial rewrite to flesh it all out into interfaces (I think that was the reason it was put into class(*) in the first place). Of course, I'm still not sure what our options are if class(*) isn't really supported by PGI (and if we, in turn, must support PGI).

**Comment by nikizadehgfdl** [comment]
I tired PGI20 on the gpu box, crashed the same way.

**Comment by marshallward** [comment]
We intend to keep supporting PGI Fortran in MOM6, and it could be difficult (though not necessarily impossible) to do so if FMS drops support.

Some of the reasons we support it:
* PGI (via Nvidia) are actively developing and releasing their compilers, including the LLVM-based flang.
* They include GPU support, which could push users on GPU-heavy machines towards PGI
* Often PGI will give different answers when GNU and Intel are identical, so we're getting additional tests out of it.
* Adopting newer features in Fortran is always tenuous, so (in my opinion) PGI acts as a good baseline for adoption.
