### ISSUE TITLE
data_override_init does not work with regional runs

### ISSUE THREAD

**Issue by laurenchilutti** [NOAA-GFDL/FMS#709]
**Describe the bug**
It was reported by the FV3 development team that a regional run does not work with ```data_override_init```. In the regional case, the grid size got from grid_spec.nc contains halo grids and therefore is larger than the grid size specified in the namelist (npx and npy). This causes data_override_init() to fail.

**To Reproduce**
Use data_override_init() in a regional grid and it will fail.

**Expected behavior**
data_override_init should not fail

**System Environment**
Describe the system environment, include:
Reporting on behalf of FV3 Team.  Unsure of specific system environment 

**Additional context**
N/A

**Comment by GFDL-Eric** [comment]
@laurenchilutti is this something that had worked with previous versions of data_override? Is the team using a specific tag of FMS? I know we put in a fix for halos a while back but I don't think that had anything to do with regional runs.

**Comment by laurenchilutti** [comment]
They see this issuie with 2021.01

**Comment by GFDL-Eric** [comment]
Was this working in 2020.04 or 2020.03? There weren't any functional changes to data_override between 2020.04 and 2021.01 (there were between 2020.03 and 2020.04, namely the choice in I/O). Is there output available somewhere, perhaps a traceback?

**Comment by laurenchilutti** [comment]
This is the location of the stdout file produced from their run: 
/lustre/f2/scratch/Kai-yuan.Cheng/SHiELD_stdout/C402_REG_regression.csh.o205042830

I will find out if they ever were able to run with it, but I can confirm that Kai sees this error with both 2020.04 and 2021.01.

**Comment by bensonr** [comment]
For previous SHiELD runs, data_override_init was called without an argument.  It didn't matter then, because they weren't using data_override.  I don't think this every worked as GFDL models did not operate on discrete regions (doubly-periodic notwithstanding).  Now that they are trying to use the functionality, it has become an issue.

**Comment by GFDL-Eric** [comment]
@bensonr FWIW, the data_table in the rundir is blank, but I guess they're just trying to kick the tires on it? @uramirez8707 found that the grid_spec.nc is specifying a grid file that has all the halos included (nx,ny=232, which corresponds to the error where data_override sees an nlat,nlon of 116 from grid_spec.nc). However, there is another grid file in that directory (/lustre/f2/scratch/gfdl/Kai-yuan.Cheng/SHiELD/R-SHiELD_202009/20200920.00Z.DEBUG_REG_.nh.32bit.non-mono/rundir/INPUT) with the suffix halo0.nc... which has nx,ny=216, which would result in an nlat,nlon of 108, which is what data_override was expecting. Is it possible that the grid_spec.nc is referencing the wrong file? Would they still be able to run "with halos" even if the grid_spec.nc is pointing to a grid file without halos, or is that the way it's supposed to be in the first place?

**Comment by bensonr** [comment]
@GFDL-Eric & @uramirez8707 The grid_spec.nc is pointing to C402_grid.tile7.nc which is the same as C402_grid.tile7.halo4.nc.  Instead of trying to do this via the issue here, let's have a voice discussion where more explanation can be given as to what's going on.

**Comment by uramirez8707** [comment]
@bensonr @laurenchilutti is this still a issue?

**Comment by laurenchilutti** [comment]
I have confirmed with Kai that this is no longer an issue.
