### ISSUE TITLE
monin_obukhov_kernel.F90 names its mod file monin_obukhov_inter.mod

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#71]
Here's a note that I just put into monin_obukhov/Makefile.am:

```
# Note that the name of the mod is different from the name of the F90
# code for monin_obukhov_kernel.F90. Also note that the mod file for
# this one does not have "_mod" in the name.

```

So this module is not named after its code, and also does not have the "_mod" in the name of the mod file (which I think is fine, but does not match the rest of the code base).

**Comment by underwoo** [comment]
Thank you for pointing that out.  It shouldn't matter, but it is something we should address in a future "city" release of the FMS library.  It will be done at that time as it will require modifications to the component source as well.

**Comment by edhartnett** [comment]
Awesome. I will list this issue to be closed with the PR merge.
