### ISSUE TITLE
2021.02-alpha1 runs crash with allocatable array or pointer is not allocated

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#711]
**Describe the bug**
Regression test crash with:
```
forrtl: severe (153): allocatable array or pointer is not allocated
Image              PC                Routine            Line        Source
fms_MOM6_SIS2_com  000000000258C9FA  Unknown               Unknown  Unknown
fms_MOM6_SIS2_com  0000000001C9DEBC  coupler_types_mod        3188  coupler_types.F90
fms_MOM6_SIS2_com  000000000040BB5C  coupler_main_IP_c        1868  coupler_main.F90
fms_MOM6_SIS2_com  0000000000402082  MAIN__                    612  coupler_main.F90

```
stdout:
```
/lustre/f2/scratch/Niki.Zadeh/FMS2021.02-alpha1_mom6_20210330_0/MOM6_GOLD_SIS2_bergs/ncrc4.intel18-prod/stdout/run/MOM6_GOLD_SIS2_bergs_1x1m0d_64x1o.o268776363
```
**To Reproduce**
Run any MOM6-SIS2 regression test
/ncrc/home2/Niki.Zadeh/xmls/xanadu/mdt_xml_RTS/OM4_extra.xml

**Expected behavior**
Regression tests should run

**System Environment**
ncrc4.intel18

**Comment by nikizadehgfdl** [comment]
@uramirez  I think there is a logic bug here:
https://github.com/NOAA-GFDL/FMS/blob/main/coupler/coupler_types.F90#L3169

The two if's should be combined like:
if( to_read .and. variable_exists(bc_rest_files(f), var%bc(n)%field(m)%name)) then

Otherwise dim_names might not get allocated and then we get a crash when deallocating it on line 3188.

**Comment by uramirez8707** [comment]
@nikizadehgfdl Yeah you are correct. 

If the you are reading the file and the variable does not exist dim_names is never going to get allocated. 

If you combine the if do the tests run?

**Comment by nikizadehgfdl** [comment]
@uramirez , yes, the tests ran and reproduced after combining the ifs.
