### ISSUE TITLE
2021.02-alpha1 ice restarts xaxis_1 and yaxis_1 have an extra attribute domain_decomposition when io_layout=1,1

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#712]
**Describe the bug**
Some restarts do not reproduce across io_layout change because the axis have an extra attribute "domain_decomposition" when io_layout=1,1 . Why is this attribute needed?

io_layout=1,1
```
netcdf ice_ocmip2_cfc.res {
dimensions:
	xaxis_1 = 360 ;
	yaxis_1 = 210 ;
	Time = UNLIMITED ; // (1 currently)
variables:
	double xaxis_1(xaxis_1) ;
		xaxis_1:domain_decomposition = 1, 360, 1, 360 ;
		xaxis_1:axis = "x" ;
	double yaxis_1(yaxis_1) ;
		yaxis_1:domain_decomposition = 1, 210, 1, 210 ;
		yaxis_1:axis = "y" ;
	double cfc_11_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_11_flux_flux_ice:checksum = "               0" ;
...
```

io_layout=1,4
```
netcdf ice_ocmip2_cfc.res {
dimensions:
	xaxis_1 = 360 ;
	yaxis_1 = 210 ;
	Time = UNLIMITED ; // (1 currently)
variables:
	double xaxis_1(xaxis_1) ;
		xaxis_1:axis = "x" ;
	double yaxis_1(yaxis_1) ;
		yaxis_1:axis = "y" ;
	double cfc_11_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_11_flux_flux_ice:checksum = "               0" ;
	double cfc_12_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_12_flux_flux_ice:checksum = "               0" ;
}

```

**To Reproduce**
MOM6-SIS2 regression test

**Expected behavior**
Why is this needed

**System Environment**
ncrc4.intel18

**Comment by uramirez8707** [comment]
The attribute is required when the io_layout is not (1,1) because it is needed by the combiner to combine the restart files. 

Is the data the same?

**Comment by nikizadehgfdl** [comment]
data is the same.
The extra attribute is there when io_layout=1,1  !!

When/how was the combiner failing?

**Comment by uramirez8707** [comment]
FMS2_io **always** adds this attribute. 

If you have an io_layout of 1,4 there are going to be four restarts created foo.res.nc.000X, without this attribute the combiner will not combine the file correctly foo.res.nc will be the same as foo.res.nc.0001. I guess that when the file is combined, the attribute is not added back. 

If you have an io_layout of 1,1 there is only going to be one file foo.res.nc, so i guess fre/combiner is smart enough to know not to combine the file and just leaves the file with the attribute. 

We can change the code to only write the attribute when the layout of not 1,1 ??

on https://github.com/NOAA-GFDL/FMS/blob/a1ef7248b29f084a46ac706a175266abb727a517/fms2_io/fms_netcdf_domain_io.F90#L487

add this to the top of the subroutine
```F90
integer, dimension(2) :: io_layout

io_layout = mpp_get_io_domain_layout(fileobj%domain)
if (io_layout(1)  .eq. 1 .and. io_layout(2) .eq. 1) return

```

**Comment by nikizadehgfdl** [comment]
@uramirez8707 , @menzel-gfdl  I am still not sure this is a requirement for mppnccombine to handle restart files as I have not seen or heard it failing without that attribute so far. Is this perhaps related to the regional history files that were not being combined correctly in a previous 2020 version? I though that issue was resolved, no?

**Comment by uramirez8707** [comment]
Niki, 
This has always been a requirement. 
If you look at files written with **fms_io** for io_layouts .ne. to 1,1 and look at the **uncombined** files you will get the domain decomposition attribute and not for the **combined** files. 

For io_layouts .eq. to 1,1 you won't get this attribute at all. 

#724 makes fms2_io consistent with fms_io. 

In case you want to take a look at mpp_io code:
https://github.com/NOAA-GFDL/FMS/blob/c616f01862e1d39b6505c9ade575786e98a5af96/mpp/include/mpp_io_write.inc#L527-L530

**Comment by nikizadehgfdl** [comment]
Got it, thanks @uramirez
