### ISSUE TITLE
FMS2021-01-alpha1: cartesian_axis attributes are missing from restart files

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/FMS#713]
**Describe the bug**
The cartesian_axis attributes are missing in the new restart files. Aren't they needed for workflow?
```
netcdf ice_ocmip2_cfc.res {
dimensions:
	xaxis_1 = 360 ;
	yaxis_1 = 210 ;
	Time = UNLIMITED ; // (1 currently)
variables:
	double xaxis_1(xaxis_1) ;
		xaxis_1:axis = "x" ;
	double yaxis_1(yaxis_1) ;
		yaxis_1:axis = "y" ;
	double cfc_11_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_11_flux_flux_ice:checksum = "               0" ;
	double cfc_12_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_12_flux_flux_ice:checksum = "               0" ;
}
```

In FMS2019.01.03 ( and I think in xanadu):
```
netcdf ice_ocmip2_cfc.res {
dimensions:
	xaxis_1 = 360 ;
	yaxis_1 = 210 ;
	Time = UNLIMITED ; // (1 currently)
variables:
	double xaxis_1(xaxis_1) ;
		xaxis_1:long_name = "xaxis_1" ;
		xaxis_1:units = "none" ;
		xaxis_1:cartesian_axis = "X" ;
	double yaxis_1(yaxis_1) ;
		yaxis_1:long_name = "yaxis_1" ;
		yaxis_1:units = "none" ;
		yaxis_1:cartesian_axis = "Y" ;
	double Time(Time) ;
		Time:long_name = "Time" ;
		Time:units = "time level" ;
		Time:cartesian_axis = "T" ;
	double cfc_11_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_11_flux_flux_ice:long_name = "cfc_11_flux_flux_ice" ;
		cfc_11_flux_flux_ice:units = "none" ;
		cfc_11_flux_flux_ice:checksum = "               0" ;
	double cfc_12_flux_flux_ice(Time, yaxis_1, xaxis_1) ;
		cfc_12_flux_flux_ice:long_name = "cfc_12_flux_flux_ice" ;
		cfc_12_flux_flux_ice:units = "none" ;
		cfc_12_flux_flux_ice:checksum = "               0" ;

// global attributes:
		:filename = "RESTART/ice_ocmip2_cfc.res.nc" ;
}

```

**To Reproduce**
xml: /ncrc/home2/Niki.Zadeh/xmls/xanadu/mdt_xml_RTS/OM4_extra.xml
experiment: MOM6_GOLD_SIS2_bergs

**Expected behavior**
Aren't these attributes needed for workflow?

**System Environment**
ncrc4.intel18 

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by nikizadehgfdl** [comment]
Location of restarts for reference
FMS2021-01-alpha1
```
/lustre/f2/scratch/Niki.Zadeh/FMS2021.02-alpha1_mom6_20210330_fix_coupler_types/MOM6_GOLD_SIS2_bergs/ncrc4.intel18-prod/archive/1x1m0d_128x1o/restart/
```
FMS2019.01.03 (xanadu)
```
/lustre/f2/scratch/Niki.Zadeh/FMS2019.01.03_mom6_20210204_0/MOM6_GOLD_SIS2_bergs/ncrc4.intel18-prod/archive/1x1m0d_64x1o/restart
```

**Comment by nikizadehgfdl** [comment]
@ceblanton , I seem to remember these cartesian_axis attributes were being used somewhere in the workflow. Do you? If not we can close this issue.

**Comment by thomas-robinson** [comment]
This was changed in [2020.01](https://github.com/NOAA-GFDL/FMS/releases/tag/2020.01) 
```
The diag_manager IO is handled by fms2_io instead of mpp_io. Default behavior assumes that the mpp_io namelist variable is set to cf_compliant = .true.
```

**Comment by ceblanton** [comment]
As far as I know, FRE does not process the restart files after they are staged, so I think in any case these restart file attribute changes are safe for FRE.

In general, `axis` is CF compliant while `cartesian_axis` was a GFDL-ism that is being phased out (history files already have `axis` only, I think), so this is a positive change. (The conventions seem to prefer a capital X, Y, or Z though instead of the lowercase above)

**Comment by nikizadehgfdl** [comment]
So, mine must be a false memory. 

Closing this issue as "works as designed".
