### ISSUE TITLE
diag_manager doesn't correctly strip tileX off nest diagnostic files when tile number is greater than  9.

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/FMS#717]
**Describe the bug**
diag_manager doesn't correctly strip tileX off nest diagnostic files when tile number is greater than 9 when using fms2_io bindings.

**To Reproduce**
Any test with > 3 nests active

**Expected behavior**
Tile name to be properly stripped.

**System Environment**
Describe the system environment, include:
Happens in all system environments.

**Additional context**
N/A

**Comment by uramirez8707** [comment]
So here diag_manager is adding tileX to the filename:
https://github.com/NOAA-GFDL/FMS/blob/c616f01862e1d39b6505c9ade575786e98a5af96/diag_manager/diag_util.F90#L1680-L1684

And here it is removing:
https://github.com/NOAA-GFDL/FMS/blob/c616f01862e1d39b6505c9ade575786e98a5af96/diag_manager/diag_output.F90#L183-L197

so why is the filename added just to be removed later and then added again in the io?

**Comment by bensonr** [comment]
@uramirez8707 - I am working with the FV3 team to have all domain-based files contain the tile designator.  We are in the process of working through the conventions, but all of this may just go away.
