### ISSUE TITLE
Support semantic vesioning in the same way that other projects do, with a 3-digit version number like 2.3.0...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/FMS#738]
Here at NOAA we are hardening our build systems so that the UFS finds dependent libraries of the correct version and features.

For example, with the netcdf-c library, so applications require version 4.7.4 or better, and we can check that at build time, to make sure we have what we need.

Unfortunately, FMS does not use semantic versioning (i.e. a version number like "4.7.4"). Semantic versioning is recommended by GitHub and is what everyone else uses. See more info here: https://semver.org/

Can the FMS team transition to using semantic versioning? They we can easily identify FMS versions and tell when one version is more recent than another, via built-in tools in CMake and autoconf.

**Comment by rem1776** [comment]
Hi Ed, after discussing with our team, we do actually use a form of semantic versioning. We use the year, increment the second digit for updates as they happen, but leave out the third digit unless we have to do a patch for a previous release. We also append '-dev' for in between releases, but that is removed for each released version of the code. These versions should still work for CMake and autoconf.

The version definitions for CMake can be found [here]() and for autotools [here](https://github.com/NOAA-GFDL/FMS/blob/9d55115a331685e4c6e01f2dfb3b770a9f80fa37/configure.ac#L28).
We also increment libtool's version info for libFMS on every release, [here](https://github.com/NOAA-GFDL/FMS/blob/9d55115a331685e4c6e01f2dfb3b770a9f80fa37/libFMS/Makefile.am#L31).

**Comment by edwardhartnett** [comment]
Yes but your form of semantic versioning is not understood by cmake, and the form of semantic versioning used by everyone else is.

So although you may consider your method preferable in some way, it's going to make a bunch of extra work for every package developer that has to use FMS. Including us here at NOAA. So can I modify this request to be, can you support semantic versioning like everyone else does, so that CMake can easily tell whether a version of FMS comes before or after another version? Without us having to write and support a bunch of cmake code?

Sometimes being different is expensive. Why not just do what everyone else does instead?

**Comment by rem1776** [comment]
Is it the year in the version number that is messing with the CMake detection? Or am I correct in assuming it's the lack of a third digit?

There's a tendency to stick to including the year for our releases, but including the extra digit (ie. 2021.02.0), at least in our build systems, seems like a change we can discuss to address some of those issues. Would that be beneficial?

**Comment by edwardhartnett** [comment]
Yes, that would be beneficial.
