### ISSUE TITLE
Modify max_fields_per_file via diag_manager namelist?

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/FMS#747]
**Is your feature request related to a problem? Please describe.**
The maximum number of variables allowed in a history file is controlled by:

https://github.com/NOAA-GFDL/FMS/blob/9d55115a331685e4c6e01f2dfb3b770a9f80fa37/diag_manager/diag_data.F90#L124

If I'm not mistaken, diagnostics are limited to 4D `(lon, lat, z, time)`.  I am working on updates to the radiation code that require an additional spectral dimension.  The work-around right now is to create one variable per spectral point, but this leads a very large number of variables and sometimes exceeds the hard limit set in the code above.  Unfortunately this limit is a compile-time constant, so if you want to change it you must recompile.  Can this instead be a run-time parameter accessible via the `diag_manager_nml` namelist?

**Describe the solution you'd like**
Remove the `parameter` attribute and add this variable to the `diag_manager_nml` namelist.

**Describe alternatives you've considered**
Ideally allow 5D (and possible more) diagnostics, but I know that given the current state of the modules this is not feasible.

**Comment by rem1776** [comment]
@menzel-gfdl Do you still need this change in the diag_manager? The issue will be addressed in the rewrite but that will take some time, so we can add this in the meantime if needed.
