### ISSUE TITLE
FMS CMake build works only with CMake version 3.12 and newer 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#751]
**Describe the bug**
The FMS CMake build only works with CMake version 3.12 higher due to the variable [HOMEPAGE_URL](https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_HOMEPAGE_URL.html) in the project description.  The `cmake_minimum_required` version range at the top of the file should be changed from  
cmake_minimum_required(VERSION `3.7`...3.15 FATAL_ERROR) to cmake_minimum_required(VERSION `3.12`... `3.20` FATAL_ERROR)

**To Reproduce**
`cmake ..` with CMake version less than 3.12 

**Expected behavior**
FMS should compile with CMake 

**System Environment**
This will occur on any systems

**Additional context**

**Comment by mlee03** [comment]
The UFS Weather Model builds with CMake 3.20.1.  Thus, the max version number should also be changed from 3.15 to 3.20 and tested.

**Comment by underwoo** [comment]
@mlee03, the "max" version is not required in `cmake_minimum_required`.  Unless there is a change to CMake that keeps the _current_ versions from working, we should not list a maximum version.

```
cmake_minimum_required(VERSION 3.12)
```

**Comment by mlee03** [comment]
@underwoo, got it.  And as you previously mentioned, I'll also check to see that CMakeLists.txt is flexible enough for all users.

**Comment by mlee03** [comment]
This was resolved by PR #794
