### ISSUE TITLE
`axis_edges`: `buffer in `get_variable_attribute` call has unknown type

### ISSUE THREAD

**Issue by marshallward** [NOAA-GFDL/FMS#763]
**Describe the bug**
FMS reports an "unsupported type" in these `get_variable_attribute` calls
https://github.com/NOAA-GFDL/FMS/blob/caf4466241698a41e3272becbc2ed419a8d3c248/axis_utils/axis_utils2.F90#L162-L182

**To Reproduce**
Run the [MOM6 OM_1deg](https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/gfdl/ice_ocean_SIS2/OM_1deg) regression test.

**Expected behavior**
`get_variable_attribute` should identify as a string.

**System Environment**
Describe the system environment, include:
- OS: Linux gaea13 4.12.14-197.40-default
- Compiler(s): PGI Fortran 20.4
- MPI type, and version: Cray MPI
- netCDF Version: C: 4.6.3, Fortran: 4.4.5
- Configure options: [Gaea "repro" flags](https://github.com/NOAA-GFDL/mkmf/blob/master/templates/ncrc-pgi.mk)

**Additional context**
Fixed if `buffer` is replaced with `buffer(1:128)`.  (I have a PR ready)

**Comment by menzel-gfdl** [comment]
@marshallward Can the `reproduce_null_char_bug` flag be removed?  Not sure why we'd want to reproduce results that we now know were incorrect?  Admittedly, the handling of possible null characters in netcdf files is kind of a mess, but I think there should be a better way of determining whether or not to read or calculate the axis bounds.

**Comment by marshallward** [comment]
@menzel-gfdl Yes, many groups require results to be reproducible, even if they are known to be incorrect.  I believe one reason is to support code updates of ongoing projects which cannot tolerate answer changes.

MOM6 has many flags to support legacy solutions.  They are gradually phased out over time.  (But I have never removed any, so I can't tell you the exact process.)
