### ISSUE TITLE
Tests fail on GitHub Actions CI, but pass on Hera

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [NOAA-GFDL/FMS#823]
**Is your question related to a problem? Please describe.**
I made changes to `diag_manager.F90` for mixedmode support. When I push the code changes to [my repo](https://github.com/MinsukJi-NOAA/FMS/tree/fms_mixedmode_new), CI tests fail. Failed tests are 9.1, 10.1, and 23: see [here](https://github.com/MinsukJi-NOAA/FMS/runs/3667380612?check_suite_focus=true). When I check out the same code onto Hera and invoke `make -k check`, there are no failed tests: `/scratch2/NCEPDEV/stmp1/Minsuk.Ji/FMS_NEW/build/test_fms/diag_manager/*.log`

**Describe what you have tried**
In [my repo](https://github.com/MinsukJi-NOAA/FMS/tree/fms_mixedmode_new), hash `81cc34` modified `send_data`, but all CI tests passed. For the later hash `76408c`, `register_diag_field` and `register_static_field` were modified, but the errors are confusingly coming from `send_data` and `unstruct_test`.

**Comment by rem1776** [comment]
Hi Minsuk, did you try running on hera with mixed mode disabled? The CI runs with a few different configurations and it looks like it's failing on a run with mixed mode disabled, so you may need to configure and rebuild without the mixed mode flag first to reproduce the error from the CI.

**Comment by uramirez8707** [comment]
@MinsukJi-NOAA What compiler did you use when you ran in Hera? Github actions is using gnu.

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA What compiler did you use when you ran in Hera? Github actions is using gnu.

@uramirez8707 I used intel/2020.2 and impi/2020.2

**Comment by MinsukJi-NOAA** [comment]
@rem1776
- On Hera, I did not configure with `--enable-mixed-mode`; I don't see `OVERLOAD_R4` and `OVERLOAD_R8` flags in the compile log.
- My earlier commit `81cc34` did pass all CI tests: see [here](https://github.com/MinsukJi-NOAA/FMS/actions/runs/1258364181).

**Comment by MinsukJi-NOAA** [comment]
```
...
test9.1 fails: err_msg=test_diag_manager_mod/bk Bounds of data do not match those of buffer. Buffer bounds=  1: 10,  1:  1,  1:  1  Actual bounds=  1:  2,  1:  1,  1:  1
2259
test9.2 successful: err_msg=test_diag_manager_mod/bk Bounds of data do not match those of buffer. Buffer bounds=  1: 10,  1:  1,  1:  1  Actual bounds=  1:  2,  1:  1,  1:  1
...
test10.1 fails: err_msg=test_diag_manager_mod/bk Bounds of data do not match those of buffer. Buffer bounds=  1: 10,  1:  1,  1:  1  Actual bounds=  1:  2,  1:  1,  1:  1
2313
test10.2 successful: err_msg=test_diag_manager_mod/bk Bounds of data do not match those of buffer. Buffer bounds=  1: 10,  1:  1,  1:  1  Actual bounds=  1:  2,  1:  1,  1:  1
...
Test 23: Unstructured grid
...
FATAL: diag_manager_mod::send_data_3d: UG_unit_test/unstructured_real_1D_field_data Bounds of data do not match those of buffer. Buffer bounds=  1: 32,  1:  1,  1:  1  Actual bounds=  1:  2,  1:  1,  1:  1
```
I am wondering why tests 9.2 and 10.2 are successful when bounds do not match.

**Comment by rem1776** [comment]
@MinsukJi-NOAA Looks like it's a compiler related issue with the GNU compilers. The CI runs with gcc 7.4.0 but I got a similar error when I ran it with gcc 9.3.0 and impi 2020.2.

**Comment by MinsukJi-NOAA** [comment]
Inconsistencies in tests 9.1 and 10.1 were identified. `test_fms/diag_manager/test_diag_manager.F90` sends a 10-element 1D array to `send_data_1d` in `diag_manager.F90`, but it becomes a 2-element 1D array on arrival: see [here](https://github.com/MinsukJi-NOAA/FMS/runs/3679915110?check_suite_focus=true#step:6:2896) (takes a while to load up the log). I did change `REAL` to `CLASS(*)`, but this should not be a problem. I am really confused.

**Comment by MinsukJi-NOAA** [comment]
These are the same lines from tests on Hera using Intel compiler:
```
WARNING: diag_manager_mod::register_diag_field: module/output_field test_mod/dat2 NOT found in diag_table

 HELLO====ALLOCATE OUTPUT_FIELDS BUFFER #4====
          10           1           1           1
 ====HELLO FROM TEST_DIAG_MANAGER====
          10          10
 ====HELLO FROM SEND_DATA_1D====
          10          10          10
          10          10           1           1
 ====HELLO FROM SEND_DATA_3D BEGINNING====
           1          10           1           1           1           1
           0           0          10           1
 ====UPDATE_BOUND #12====
           1          10           1           1           1           1
test9.1 successful.

```

**Comment by MinsukJi-NOAA** [comment]
I identified the code changes causing the CI tests to fail: https://github.com/MinsukJi-NOAA/FMS/commit/000df8f24002ecc84028457f842d5c4dc2c3534f
But tests call this subroutine without the optional argument `range`: i.e. these code changes should not even matter as far as these tests are concerned.

**Comment by MinsukJi-NOAA** [comment]
How can I address the failing CI with suspected GNU compiler issue? We have lots of code changes in the pipeline for mixed mode support. Should we just use the Intel compiler on, say, Hera? Is passing CI tests a requirement in order for code changes to be merged into the FMS repository?

Do you have a set up to build and run unit tests on Hera using GNU 9 and MPICH 3?

**Comment by thomas-robinson** [comment]
@MinsukJi-NOAA how are you testing on hera with gnu 9 and mpich 3?  I don't see a module for mpich on hera.

**Comment by MinsukJi-NOAA** [comment]
We can use the hpc-stack:
```
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-gnu/9.2.0
module load hpc-mpich/3.3.2
module load hdf5/1.10.6
module load netcdf/4.7.4
```
netcdf/4.7.2 is also available but 4.7.0 is not.

**Comment by MinsukJi-NOAA** [comment]
On Hera:
```
git clone https://github.com/NOAA-GFDL/FMS FMS_2021_03
cd FMS_2021_03/
git checkout 2021.03
module purge
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-gnu/9.2.0
module load hpc-mpich/3.3.2
module load hdf5/1.10.6
module load netcdf/4.7.4
export FC=mpifort
export F77=mpifort
export CC=mpicc
export CXX=mpicxx
export CFLAGS="-O0 -g -I$NETCDF/include/"
export FCFLAGS="-O0 -g -I$NETCDF/include/"
export LDFLAGS="-O0 -g -L$NETCDF/lib/"
mkdir build_01 && cd build_01
autoreconf -i ../configure.ac 
../configure 
```
Results in:
`configure: error: Can't find the netCDF C library.  Set LDFLAGS/LIBS`

**Comment by MinsukJi-NOAA** [comment]
Changing `netcdf/4.7.4` to `netcdf/4.7.2` allows the build, but the majority of unit tests fails when `make -k check` is invoked.

**Comment by rem1776** [comment]
@MinsukJi-NOAA I think a workaround would be in `register_static_field` to just remove the DIMENSION attribute on the range argument and make it a deferred length:

`CLASS(*), OPTIONAL, INTENT(in) :: range(:)`

And then if range is present give a fatal error if the length is not two. This seems to fix the failing tests with gcc 9 and gcc 7 from the CI container environment.

**Comment by MinsukJi-NOAA** [comment]
@rem1776 I verified that your suggestion of using a deferred length allows the CI tests with gcc to pass!
