### ISSUE TITLE
Issue while inserting boundary conditions on MOM6

### ISSUE THREAD

**Issue by nlaureanti** [NOAA-GFDL/FMS#897]
I'm trying to run MOM6 for a South American domain and having some issues with the boundary conditions

I'm using the following script to generate the obc files: https://github.com/ESMG/regionalMOM6_notebooks/blob/master/creating_obc_input_files/panArctic_OBC_from_global_MOM6.ipynb
MOM_input:
`OBC_SEGMENT_001_DATA = "U=value:0.0,V=value:0.0,SSH=value:0.0,TEMP=file:obc_ts_north.nc(temp)" !`
ncdump -h workdir/INPUT/obc_ts_north.nc:
```
netcdf obc_ts_north {
dimensions:
	Time = UNLIMITED ; // (1 currently)
	locations = 321 ;
	z_l = 34 ;
	dim_0 = 1 ;
variables:
	int locations(locations) ;
	double z_l(z_l) ;
		z_l:_FillValue = 1.e+20 ;
		z_l:long_name = "Depth at cell center" ;
		z_l:units = "meters" ;
		z_l:cartesian_axis = "Z" ;
		z_l:positive = "down" ;
		z_l:edges = "z_i" ;
	double Time(Time) ;
		Time:_FillValue = 1.e+20 ;
		Time:long_name = "Time" ;
		Time:units = "days since 0001-01-01 00:00:00" ;
		Time:cartesian_axis = "T" ;
		Time:calendar_type = "NOLEAP" ;
		Time:calendar = "gregorian" ;
		Time:bounds = "Time_bnds" ;
		Time:modulo = " " ;
	double lon(locations) ;
		lon:_FillValue = 1.e+20 ;
	double lat(locations) ;
		lat:_FillValue = 1.e+20 ;
	double temp_segment_001(Time, z_l, dim_0, locations) ;
		temp_segment_001:_FillValue = 1.e+20 ;
		temp_segment_001:regrid_method = "nearest_s2d" ;
		temp_segment_001:coordinates = "lon lat" ;
	double salt_segment_001(Time, z_l, dim_0, locations) ;
		salt_segment_001:_FillValue = 1.e+20 ;
		salt_segment_001:regrid_method = "nearest_s2d" ;
		salt_segment_001:coordinates = "lon lat" ;
	double dz_temp_segment_001(Time, z_l, dim_0, locations) ;
		dz_temp_segment_001:_FillValue = 1.e+20 ;
		dz_temp_segment_001:coordinates = "lon lat" ;
	double dz_salt_segment_001(Time, z_l, dim_0, locations) ;
		dz_salt_segment_001:_FillValue = 1.e+20 ;
		dz_salt_segment_001:coordinates = "lon lat" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.6.2,hdf5=1.10.4" ;
}

```
Unfortunelly, the model stop with the following error 
`FATAL from PE     0: field temp_segment_001 Array size mismatch in time_interp_external. Array "data" is too small. shape(data)=     1   81   34`

Instead of reading 321 locations, the temp field appears with 81. Does anyone have any hint of what could be wrong here?

**Comment by kshedstrom** [comment]
Which version of FMS are you using? There's a known difference between FMS1 and FMS2 in reading the OBC files. I believe the plan is to sort it out soonish.

**Comment by nlaureanti** [comment]
@kshedstrom I'm using FMS1, I believe it is from march 2020..

**Comment by kshedstrom** [comment]
This is likely a MOM6 issue at this point. What are the dimensions of your grid? Which direction is your OBC?

**Comment by nlaureanti** [comment]
@kshedstrom  

It is the northern boundary and the grid is 320x160 as in:

netcdf ocean_hgrid {
dimensions:
	string = 255 ;
	nx = 320 ;
	ny = 160 ;
	nxp = 321 ;
	nyp = 161 ;
variables:
	char tile(string) ;
		tile:standard_name = "grid_tile_spec" ;
		tile:geometry = "spherical" ;
		tile:north_pole = "0.0 90.0" ;
		tile:discretization = "logically_rectangular" ;
		tile:conformal = "true" ;
	double x(nyp, nxp) ;
		x:standard_name = "geographic_longitude" ;
		x:units = "degree_east" ;
	double y(nyp, nxp) ;
		y:standard_name = "geographic_latitude" ;
		y:units = "degree_north" ;
	double dx(nyp, nx) ;
		dx:standard_name = "grid_edge_x_distance" ;
		dx:units = "meters" ;
	double dy(ny, nxp) ;
		dy:standard_name = "grid_edge_y_distance" ;
		dy:units = "meters" ;
	double area(ny, nx) ;
		area:standard_name = "grid_cell_area" ;
		area:units = "m2" ;
	double angle_dx(nyp, nxp) ;
		angle_dx:standard_name = "grid_vertex_x_angle_WRT_geographic_east" ;
		angle_dx:units = "degrees_east" ;
	char arcx(string) ;
		arcx:standard_name = "grid_edge_x_arc_type" ;
		arcx:north_pole = "0.0 90.0" ;

// global attributes:
		:grid_version = "0.2" ;
		:code_version = "$Name: fre-nctools-bronx-10 $" ;
		:history = "make_hgrid --grid_type regular_lonlat_grid --nxbnd 2 --nybnd 2 --xbnd -60,-20 --ybnd -40,-20 --dlon 0.25,0.25 --dlat 0.25,0.25 --grid_name ocean_hgrid --center c_cell" ;
}

**Comment by kshedstrom** [comment]
We should close this issue and take this to the MOM6 forum or elsewhere unless it turns out to indeed be an FMS issue.

**Comment by rem1776** [comment]
@nlaureanti @kshedstrom It looks like the `time_interp_external` routine was called somewhere with a `data` argument that has different dimensions than the field it's trying to read from the file so it gives an error. Without a stack trace I'm not sure where the call is coming from, but it looks external to FMS.

I would transfer this issue over to the MOM6 github page, but since it's under a different organization I'm not able to so you'll have to make a new issue. I'll close this for now, we could re-open if needed.
