### ISSUE TITLE
Remove @wrongkindofdoctor from FMS maintainer role

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/FMS#968]
My MDTF-diagnostics role has taken over my life, and it would be prudent to remove me from the code FMS and FMScoupler maintainers list. I can still review as-needed if you want my input.

-Jess

**Comment by thomas-robinson** [comment]
@wrongkindofdoctor You have been deemed irreplaceable in the eyes of FMS, and none shall follow you.  We shall build a large structure in your honor.

**Comment by wrongkindofdoctor** [comment]
My legacy is in the comments, but I recommend you erect a new building in my honor: 
"The @wrongkindofdoctor center for people who can't code good and want to learn to do other stuff good, too"

**Comment by mlee03** [comment]
Can the structure be made out of dark chocolate?

**Comment by wrongkindofdoctor** [comment]
@mlee03 Only if I can help everyone eat it.
