### ISSUE TITLE
Minor typos 

### ISSUE THREAD

**Issue by mlee03** [NOAA-GFDL/FMS#974]
**Describe the bug**
The typo of the variable 'success' throughout [yaml_parser.F90](https://github.com/NOAA-GFDL/FMS/blob/main/parser/yaml_parser.F90#L209) and the use of the Fortran keyword 'optional' as a [variable](https://github.com/NOAA-GFDL/FMS/blob/main/parser/yaml_parser.F90#L269) could be bothersome to certain users.     

Also, the assignment of the gridname to  ['non'](https://github.com/NOAA-GFDL/FMS/blob/main/data_override/data_override.F90#L232) instead of none leads one to think it's a typo.  Could a comment be added to say why it's 'non' and not 'none'? 

**To Reproduce**
The 'bug' does nor create any runtime issues  

**Expected behavior**

**System Environment**

**Additional context**
They're just minor "OCD" issues encountered while looking through the code.... only striving to make FMS more perfect.

**Comment by rem1776** [comment]
I changed it to 'non' instead of 'none' because `gridname` is a 3-character string so it'd produce a warning and get the 'e' cut off anyway. Might be good to make it something more clear like 'n/a' but I'm not sure if that would mess with anything else down the line that's why i left it as is.

**Comment by mlee03** [comment]
@rem1776, I'll add what you said as the comment :)

**Comment by thomas-robinson** [comment]
@j-lentz Can you work on this?
