### ISSUE TITLE
can we run some of the tests in the mpp directory?

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/FMS#98]
My work is taking me around to FMS again! ;-) I will need to do some work on the IO code for NOAA to try using PIO.

Before I start, I would love to get some automatic tests for the code in the mpp directory. I notice there are a lot of fortran test codes in the directory. Can we turn these on as tests?

**Comment by underwoo** [comment]
We are in the process of pulling all the tests into their own files, and configuring the autotools build to run them. That work is nearing completion.

**Comment by marshallward** [comment]
BTW I recently learned that my alltoallw changes are failing some of the MPP tests for the complex number C4 and C8 overloads (test_mpp_pset.F90, I think), so I will send a patch soon.

**Comment by edhartnett** [comment]
@underwoo can you tell me what branch that testing work is taking place on so I can take a look?

Thanks!

**Comment by uramirez8707** [comment]
The testing work is in my fork git@github.com:uramirez8707/FMS.git under the branch unit_tests. 

The mpp tests are in the directory test_fms/mpp.

**Comment by edhartnett** [comment]
OK, I am looking at this branch now. Seems like nice work getting these tests in place.

Can you merge these changes soon so that I can start using them?

**Comment by edhartnett** [comment]
OK, I am happy to see that you guys are writing all these fine tests!  I am happy to see that you guys are moving to a more advanced process, and I am sure these great tests will help a lot. And as travis is already set up for this project, you can start using continuous integration for future PRs. 

@uramirez8707 you have correctly set up the automake files for the tests. Nice work! I am very happy to see that you guys are successfully adapting to the new build system. ;-)

When I run the tests, I get some failures:

```
ed@mikado:~/tmp/fms_test/test_fms/diag_manager$ bash -x test_diag_manager.sh
+ export PATH=/home/ed/Downloads/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:../bats/bin
+ PATH=/home/ed/Downloads/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:../bats/bin
+ bats test_diag_manager.bats
[1G   Test 1: Data array is too large in x and y direction[219G 1/23[2G[1G ✓ Test 1: Data array is too large in x and y direction
[1G   Test 2: Data array is too large in x direction[219G 2/23[2G[1G ✓ Test 2: Data array is too large in x direction
[1G   Test 3: Data array is too large in y direction[219G 3/23[2G[1G ✓ Test 3: Data array is too large in y direction
[1G   Test 4: Data array is too small in x and y direction, checks for 2 time steps[219G 4/23[2G[1G ✓ Test 4: Data array is too small in x and y direction, checks for 2 time steps
[1G   Test 5: Data array is too small in x directions, checks for 2 time steps[219G 5/23[2G[1G ✓ Test 5: Data array is too small in x directions, checks for 2 time steps
[1G   Test 6: Data array is too small in y direction, checks for 2 time steps[219G 6/23[2G[1G ✓ Test 6: Data array is too small in y direction, checks for 2 time steps
[1G   Test 7: Data array is too large in x and y, with halos, 2 time steps[219G 7/23[2G[1G ✓ Test 7: Data array is too large in x and y, with halos, 2 time steps
[1G   Test 8: Data array is too small in x and y, with halos, 2 time steps[219G 8/23[2G[1G ✓ Test 8: Data array is too small in x and y, with halos, 2 time steps
[1G   Test 9: Data array is too small, 1D, static global data[219G 9/23[2G[1G ✓ Test 9: Data array is too small, 1D, static global data
[1G   Test 10: Data array is too large, 1D, static global data[219G10/23[2G[1G ✓ Test 10: Data array is too large, 1D, static global data
[1G   Test 11: Missing je_in as an input[219G11/23[2G[1G ✓ Test 11: Missing je_in as an input
[1G   Test 12: Catch duplicate field in diag_table[219G12/23[2G[1G ✓ Test 12: Catch duplicate field in diag_table
[1G   Test 13: Output interval greater than runlength[219G13/23[2G[1G ✓ Test 13: Output interval greater than runlength
[1G   Test 14: Catch invalid date in register_diag_field call[219G14/23[2G[1G ✓ Test 14: Catch invalid date in register_diag_field call
[1G   Test 15: OpenMP thread test[219G15/23[2G[1G - Test 15: OpenMP thread test (skipped)
[1G   Test 16: Filename appendix added[219G16/23[2G[1G ✓ Test 16: Filename appendix added
[1G   Test 17: Root-mean-square[219G17/23[2G[1G ✗ Test 17: Root-mean-square
   (in test file test_diag_manager.bats, line 128)
     `[ "$status" -eq 0 ]' failed
[1G   Test 18: Added attributes, and cell_measures[219G18/23[2G[1G ✗ Test 18: Added attributes, and cell_measures
   (in test file test_diag_manager.bats, line 137)
     `[ "$status" -eq 0 ]' failed
[1G   Test 19: Area and Volume same field[219G19/23[2G[1G ✓ Test 19: Area and Volume same field
[1G   Test 20: Get diag_field_id, ID found and not found[219G20/23[2G[1G ✓ Test 20: Get diag_field_id, ID found and not found
[1G   Test 21: Add axis attributes[219G21/23[2G[1G ✗ Test 21: Add axis attributes
   (in test file test_diag_manager.bats, line 159)
     `[ "$status" -eq 0 ]' failed
[1G   Test 22: Get 'nv' axis id[219G22/23[2G[1G ✗ Test 22: Get 'nv' axis id
   (in test file test_diag_manager.bats, line 170)
     `[ "$status" -eq 0 ]' failed
[1G   Test 23: Unstructured grid[219G23/23[2G[1G ✓ Test 23: Unstructured grid

23 tests, 4 failures, 1 skipped
```

May I suggest that, rather than hold these changes until all tests are working, you comment out broken tests and merge the rest? Lots of tests do seem to work and that would be very, very helpful. Then the broken tests can be fixed incrementally.

I would like to start working on this code, helping to get tests working and added to the mpp directory. If you can get a working PR up, which can be merged to master, then I can add my efforts to yours and testing can be working even faster.

**Comment by edwardhartnett** [comment]
@uramirez8707 can we get some tests merged soon? I would like to start working on this code... Thanks!

**Comment by wrongkindofdoctor** [comment]
@edwardhartnett , our group is waiting for feedback from one of the team members on our new development merge policy. Once I have received the green light, I will work over the next couple of weeks to update the FMS master branch with the latest round of commits into dev/master, and will include the unit tests. I will tag a stable version for external users when I have completed the task, and leave a comment on this issue to confirm.

**Comment by edwardhartnett** [comment]
OK, thanks for the update.

**Comment by edwardhartnett** [comment]
How are we doing on this issue?

**Comment by uramirez8707** [comment]
@edwardhartnett see https://github.com/NOAA-GFDL/FMS/pull/139

We are still working to get the tests into master.

**Comment by underwoo** [comment]
@edhartnett with the tests we have (although somewhat incomplete), do you feel this issue should remain open?

**Comment by edwardhartnett** [comment]
No, this issue is complete, though of course our testing journey is just beginning. ;-)

I am super impressed with how you guys have started using CI with travis, and moved forward on this testing. Keep up the good work!
