### ISSUE TITLE
CT_write_chksums bug: chksums get written by every PE

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#989]
**Describe the bug**
CT_write_chksums write out the checksums at every PE
https://github.com/NOAA-GFDL/FMS/blob/444cd12244a6bbd1c78b2b14bde67a6b0a67f8df/coupler/coupler_types.F90#L3627-L3628
https://github.com/NOAA-GFDL/FMS/blob/444cd12244a6bbd1c78b2b14bde67a6b0a67f8df/coupler/coupler_types.F90#L3649-L3650

**To Reproduce**
Call CT_write_chksums and you will see that the chksums get written at every PE

**Expected behavior**
The chksums should be written by the root pe only. There should be an if (is_root_pe) block.

**System Environment**
Describe the system environment, include:
This happens in every system

**Additional context**
N/A

**Comment by rem1776** [comment]
fixed with #1006
